#!/bin/bash
fricas -nosman <<EOF
)fin 
(setf save-rt *readtable*)
(load "sl-on-cl.lisp")
*package*
(sl::plus 2 3)
(sl::explode "abcd")
(|spad|)
D(x^n,x)
--
)fin
(sl::standard-lisp)
cl::*package*
(cl::in-package :boot)
*package*
(setf *readtable* save-rt)
(|spad|)
D(sin x ,x )
12*4444
   

