\begin{framed}$$ \int_a^b f(x) dx  $$\end{framed}
\begin{verbatim}Good morning ....\end{verbatim}
\begin{verbatim}Good morning again ....\end{verbatim}
\begin{equation}\frac{x^n+sin x}{1-x^2}\end{equation}
\begin{equation}\frac{x^n+sin y}{1-x^p}\end{equation}
x -{{1 \over 6} \  {{x} \sp {3}}}+{{1 \over {120}} \  {{x} \sp {5}}} -{{1 \over {5040}} \  {{x} \sp {7}}}+{{1 \over {362880}} \  {{x} \sp {9}}}+{O \left( {{{x} \sp {{11}}}} \right)}
