(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'BIBASIS_INVOLUTIVE)) 
(PUT 'INIT 'NUMBER-OF-ARGS 0) 
(PUT 'INIT 'DEFINED-ON-LINE '37) 
(PUT 'INIT 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'INIT 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE INIT NIL
    (PROG (I)
      (SETQ I 0)
      (SETQ FLUIDBIBASISREVERSEDVARIABLES (REVERSE FLUIDBIBASISVARIABLES))
      (INITMONOMIALS)
      (SETQ I 0)
      (SETQ FLUIDBIBASISSINGLEVARIABLEMONOMIALSA
              (PROG (V FORALL-RESULT FORALL-ENDPTR)
                (SETQ V FLUIDBIBASISVARIABLES)
                (COND ((NULL V) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS
                                 ((LAMBDA (V)
                                    (CONS V
                                          (GETV
                                           FLUIDBIBASISSINGLEVARIABLEMONOMIALSS
                                           (SETQ I (PLUS I 1)))))
                                  (CAR V))
                                 NIL)))
               LOOPLABEL
                (SETQ V (CDR V))
                (COND ((NULL V) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS
                         ((LAMBDA (V)
                            (CONS V
                                  (GETV FLUIDBIBASISSINGLEVARIABLEMONOMIALSS
                                        (SETQ I (PLUS I 1)))))
                          (CAR V))
                         NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (SETTRESET)
      (SETQ FLUIDBIBASISSETQ (CONS NIL NIL))
      (SETQ FLUIDBIBASISREDUCTIONSMADE 0)
      (SETQ FLUIDBIBASISNORMALFORMS 0)
      (SETQ FLUIDBIBASISNONZERONORMALFORMS 0))) 
(PUT 'SORTEDPOLYNOMLISTINSERT 'NUMBER-OF-ARGS 2) 
(PUT 'SORTEDPOLYNOMLISTINSERT 'DEFINED-ON-LINE '55) 
(PUT 'SORTEDPOLYNOMLISTINSERT 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'SORTEDPOLYNOMLISTINSERT 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE SORTEDPOLYNOMLISTINSERT (POLYNOMLIST POLYNOM)
    (PROG (POLYNOMLISTITERATOR)
      (SETQ POLYNOMLISTITERATOR POLYNOMLIST)
      (PROG ()
       WHILELABEL
        (COND
         ((NOT
           (AND (CAR POLYNOMLISTITERATOR)
                (NEQ (POLYNOMCOMPARE (CAR POLYNOMLISTITERATOR) POLYNOM)
                     (MINUS 1))))
          (RETURN NIL)))
        (PROGN (SETQ POLYNOMLISTITERATOR (CDR POLYNOMLISTITERATOR)) NIL)
        (GO WHILELABEL))
      (RPLACA
       (RPLACD POLYNOMLISTITERATOR
               (CONS (CAR POLYNOMLISTITERATOR) (CDR POLYNOMLISTITERATOR)))
       POLYNOM))) 
(PUT 'POLYNOMLISTFINDDIVISOR 'NUMBER-OF-ARGS 3) 
(PUT 'POLYNOMLISTFINDDIVISOR 'DEFINED-ON-LINE '67) 
(PUT 'POLYNOMLISTFINDDIVISOR 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'POLYNOMLISTFINDDIVISOR 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE POLYNOMLISTFINDDIVISOR (POLYNOMLIST POLYNOM TOGROEBNER)
    (COND ((OR (NULL (CAR POLYNOM)) (NULL (CAR POLYNOMLIST))) NIL)
          (T
           (PROG (TMPMONOM CURRENTPOLYNOM BREAK)
             (SETQ TMPMONOM (CAR POLYNOM))
             (SETQ CURRENTPOLYNOM POLYNOMLIST)
             (PROG ()
              WHILELABEL
               (COND
                ((NOT (AND (CAR CURRENTPOLYNOM) (NOT BREAK))) (RETURN NIL)))
               (PROGN
                (COND
                 ((OR
                   (AND TOGROEBNER
                        (MONOMISDIVISIBLEBY TMPMONOM
                         (CAR (CAR CURRENTPOLYNOM))))
                   (AND (NOT TOGROEBNER)
                        (MONOMISPOMMARETDIVISIBLEBY TMPMONOM
                         (CAR (CAR CURRENTPOLYNOM)))))
                  (PROGN (SETQ BREAK T) NIL))
                 (T (PROGN (SETQ CURRENTPOLYNOM (CDR CURRENTPOLYNOM)) NIL)))
                NIL)
               (GO WHILELABEL))
             (RETURN (CAR CURRENTPOLYNOM)))))) 
(PUT 'POLYNOMLISTREDUCE 'NUMBER-OF-ARGS 3) 
(PUT 'POLYNOMLISTREDUCE 'DEFINED-ON-LINE '93) 
(PUT 'POLYNOMLISTREDUCE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'POLYNOMLISTREDUCE 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE POLYNOMLISTREDUCE (POLYNOMLIST POLYNOM TOGROEBNER)
    (PROG (RESULT DIVISOR)
      (SETQ RESULT (CONS NIL NIL))
      (COND ((NULL (CAR POLYNOM)) (PROGN (RETURN RESULT) NIL)))
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOM)) (RETURN NIL)))
        (PROGN
         (SETQ DIVISOR (POLYNOMLISTFINDDIVISOR POLYNOMLIST POLYNOM TOGROEBNER))
         (PROG ()
          WHILELABEL
           (COND ((NOT DIVISOR) (RETURN NIL)))
           (PROGN
            (POLYNOMREDUCEBY POLYNOM DIVISOR)
            (SETQ DIVISOR
                    (POLYNOMLISTFINDDIVISOR POLYNOMLIST POLYNOM TOGROEBNER))
            NIL)
           (GO WHILELABEL))
         (COND
          ((CAR POLYNOM)
           (PROGN
            (POLYNOMADD RESULT (CONS (CAR POLYNOM) (CONS NIL NIL)))
            (RPLACD (RPLACA POLYNOM (CADR POLYNOM)) (CDDR POLYNOM))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (RETURN RESULT))) 
(PUT 'POLYNOMLISTAUTOREDUCE 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMLISTAUTOREDUCE 'DEFINED-ON-LINE '120) 
(PUT 'POLYNOMLISTAUTOREDUCE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'POLYNOMLISTAUTOREDUCE 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMLISTAUTOREDUCE (POLYNOMLIST TOGROEBNER)
    (PROG (TMPPOLYNOMLIST TMPPOLYNOM TMPMONOM TMPPOLYNOMITERATOR)
      (SETQ TMPPOLYNOMLIST (CONS NIL NIL))
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOMLIST)) (RETURN NIL)))
        (PROGN
         (SETQ TMPPOLYNOM
                 (POLYNOMLISTREDUCE TMPPOLYNOMLIST (CAR POLYNOMLIST)
                  TOGROEBNER))
         (RPLACD (RPLACA POLYNOMLIST (CADR POLYNOMLIST)) (CDDR POLYNOMLIST))
         (COND
          ((CAR TMPPOLYNOM)
           (PROGN
            (SETQ TMPMONOM (CAR TMPPOLYNOM))
            (SETQ TMPPOLYNOMITERATOR TMPPOLYNOMLIST)
            (PROG ()
             WHILELABEL
              (COND ((NOT (CAR TMPPOLYNOMITERATOR)) (RETURN NIL)))
              (PROGN
               (COND
                ((MONOMISDIVISIBLEBY (CAR (CAR TMPPOLYNOMITERATOR)) TMPMONOM)
                 (PROGN
                  (PUSHBACK POLYNOMLIST (CAR TMPPOLYNOMITERATOR))
                  (RPLACD (RPLACA TMPPOLYNOMITERATOR (CADR TMPPOLYNOMITERATOR))
                          (CDDR TMPPOLYNOMITERATOR))
                  NIL))
                (T
                 (PROGN
                  (SETQ TMPPOLYNOMITERATOR (CDR TMPPOLYNOMITERATOR))
                  NIL)))
               NIL)
              (GO WHILELABEL))
            (PUSHBACK TMPPOLYNOMLIST TMPPOLYNOM)
            NIL)))
         NIL)
        (GO WHILELABEL))
      (SETQ TMPPOLYNOMITERATOR TMPPOLYNOMLIST)
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR TMPPOLYNOMITERATOR)) (RETURN NIL)))
        (PROGN
         (SETQ TMPPOLYNOM (CAR TMPPOLYNOMITERATOR))
         (RPLACD (RPLACA TMPPOLYNOMITERATOR (CADR TMPPOLYNOMITERATOR))
                 (CDDR TMPPOLYNOMITERATOR))
         (SETQ TMPPOLYNOM
                 (POLYNOMLISTREDUCE TMPPOLYNOMLIST TMPPOLYNOM TOGROEBNER))
         (COND
          ((AND TMPPOLYNOM (CAR TMPPOLYNOM))
           (PROGN
            (RPLACA
             (RPLACD TMPPOLYNOMITERATOR
                     (CONS (CAR TMPPOLYNOMITERATOR) (CDR TMPPOLYNOMITERATOR)))
             TMPPOLYNOM)
            (SETQ TMPPOLYNOMITERATOR (CDR TMPPOLYNOMITERATOR))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (RETURN TMPPOLYNOMLIST))) 
(PUT 'NORMALFORM 'NUMBER-OF-ARGS 1) 
(PUT 'NORMALFORM 'DEFINED-ON-LINE '169) 
(PUT 'NORMALFORM 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'NORMALFORM 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE NORMALFORM (POLYNOM)
    (PROG (INVOLUTIVEDIVISOR NORMALFORM)
      (SETQ NORMALFORM (CONS NIL NIL))
      (COND ((NULL (CAR POLYNOM)) (PROGN (RETURN NORMALFORM) NIL)))
      (SETQ FLUIDBIBASISNORMALFORMS (IADD1 FLUIDBIBASISNORMALFORMS))
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOM)) (RETURN NIL)))
        (PROGN
         (SETQ INVOLUTIVEDIVISOR (JANETTREEFIND (CAR POLYNOM)))
         (PROG ()
          WHILELABEL
           (COND ((NOT INVOLUTIVEDIVISOR) (RETURN NIL)))
           (PROGN
            (POLYNOMHEADREDUCEBY POLYNOM (GETV INVOLUTIVEDIVISOR 1))
            (COND
             ((CAR POLYNOM)
              (PROGN
               (SETQ INVOLUTIVEDIVISOR (JANETTREEFIND (CAR POLYNOM)))
               NIL))
             (T (PROGN (SETQ INVOLUTIVEDIVISOR NIL) NIL)))
            NIL)
           (GO WHILELABEL))
         (COND
          ((CAR POLYNOM)
           (PROGN
            (POLYNOMADD NORMALFORM (CONS (CAR POLYNOM) (CONS NIL NIL)))
            (RPLACD (RPLACA POLYNOM (CADR POLYNOM)) (CDDR POLYNOM))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (RETURN NORMALFORM))) 
(PUT 'CONSTRUCTINVOLUTIVEBASIS 'NUMBER-OF-ARGS 2) 
(PUT 'CONSTRUCTINVOLUTIVEBASIS 'DEFINED-ON-LINE '204) 
(PUT 'CONSTRUCTINVOLUTIVEBASIS 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_INVOLUTIVE.RED) 
(PUT 'CONSTRUCTINVOLUTIVEBASIS 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE CONSTRUCTINVOLUTIVEBASIS (POLYNOMLIST TOGROEBNER)
    (PROG (TMPTRIPLE TMPMONOM NORMALFORM NORMALFORMLM SETTITERATOR
           NEWTRIPLELIST)
      (SETQ POLYNOMLIST (POLYNOMLISTAUTOREDUCE POLYNOMLIST T))
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOMLIST)) (RETURN NIL)))
        (PROGN
         (SORTEDTRIPLELISTINSERT FLUIDBIBASISSETQ
          (CREATETRIPLE (CAR POLYNOMLIST)))
         (SETQ POLYNOMLIST (CDR POLYNOMLIST))
         NIL)
        (GO WHILELABEL))
      (PROG ()
       WHILELABEL
        (COND ((NOT (NOT (NULL (CAR FLUIDBIBASISSETQ)))) (RETURN NIL)))
        (PROGN
         (SETQ TMPTRIPLE (SETQGET))
         (SETQ TMPMONOM (CAR (GETV TMPTRIPLE 1)))
         (SETQ NORMALFORM (NORMALFORM (GETV TMPTRIPLE 1)))
         (SETQ NORMALFORMLM (CAR NORMALFORM))
         (COND
          (NORMALFORMLM
           (PROGN
            (SETQ FLUIDBIBASISNONZERONORMALFORMS
                    (IADD1 FLUIDBIBASISNONZERONORMALFORMS))
            (SETQ NEWTRIPLELIST (CONS NIL NIL))
            (SETQ SETTITERATOR FLUIDBIBASISSETT)
            (PROG ()
             WHILELABEL
              (COND ((NOT (CAR SETTITERATOR)) (RETURN NIL)))
              (PROGN
               (COND
                ((MONOMISDIVISIBLEBY (CAR (GETV (CAR SETTITERATOR) 1))
                  NORMALFORMLM)
                 (PROGN
                  (SETQDELETEDESCENDANTS (GETV (CAR SETTITERATOR) 0))
                  (SORTEDTRIPLELISTINSERT NEWTRIPLELIST (CAR SETTITERATOR))
                  (JANETTREEDELETE (CAR (GETV (CAR SETTITERATOR) 1)))
                  (RPLACD (RPLACA SETTITERATOR (CADR SETTITERATOR))
                          (CDDR SETTITERATOR))
                  NIL))
                (T (PROGN (SETQ SETTITERATOR (CDR SETTITERATOR)) NIL)))
               NIL)
              (GO WHILELABEL))
            (COND
             ((EQ TMPMONOM NORMALFORMLM)
              (PROGN
               (SETTINSERT
                (CREATETRIPLEWITHANCESTOR NORMALFORM (GETV TMPTRIPLE 2)))
               (TRIPLESETPROLONGSET (CAR FLUIDBIBASISSETT) (GETV TMPTRIPLE 3))
               NIL))
             (T (PROGN (SETTINSERT (CREATETRIPLE NORMALFORM)) NIL)))
            (SETTCOLLECTNONMULTIPROLONGATIONS NEWTRIPLELIST)
            (COND
             ((EQN (GETV NORMALFORMLM 0) 0)
              (PROGN (SETQ FLUIDBIBASISSETQ (CONS NIL NIL)) NIL))
             (T (PROGN (SETQINSERTLIST NEWTRIPLELIST) NIL)))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (SETQ POLYNOMLIST (CONS NIL NIL))
      (SETQ SETTITERATOR FLUIDBIBASISSETT)
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR SETTITERATOR)) (RETURN NIL)))
        (PROGN
         (SORTEDPOLYNOMLISTINSERT POLYNOMLIST (GETV (CAR SETTITERATOR) 1))
         (SETQ SETTITERATOR (CDR SETTITERATOR))
         NIL)
        (GO WHILELABEL))
      (SETQ POLYNOMLIST (POLYNOMLISTAUTOREDUCE POLYNOMLIST TOGROEBNER))
      (RETURN POLYNOMLIST))) 
(ENDMODULE) 