(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'BIBASIS_POLYNOM)) 
(PUT 'POLYNOMGETLM 'NUMBER-OF-ARGS 1) 
(PUTC 'POLYNOMGETLM 'INLINE '(LAMBDA (U) (CAR U))) 
(DE POLYNOMGETLM (U) (CAR U)) 
(PUT 'POLYNOMGETLM 'SETQFN '(LAMBDA (U V) (SETCAR U V))) 
(PUT 'SET_POLYNOMGETLM 'NUMBER-OF-ARGS 2) 
(PUTC 'SET_POLYNOMGETLM 'INLINE '(LAMBDA (U V) (SETCAR U V))) 
(DE SET_POLYNOMGETLM (U V) (SETCAR U V)) 
NIL 
(PUT 'POLYNOMCLONE 'NUMBER-OF-ARGS 1) 
(PUT 'POLYNOMCLONE 'DEFINED-ON-LINE '43) 
(PUT 'POLYNOMCLONE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMCLONE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE POLYNOMCLONE (POLYNOM)
    (PROG (TMPPOLYNOM POLYNOMITERATOR)
      (SETQ POLYNOMITERATOR POLYNOM)
      (PROG ()
       WHILELABEL
        (COND ((NOT POLYNOMITERATOR) (RETURN NIL)))
        (PROGN
         (SETQ TMPPOLYNOM (CONS (MONOMCLONE (CAR POLYNOMITERATOR)) TMPPOLYNOM))
         (SETQ POLYNOMITERATOR (CDR POLYNOMITERATOR))
         NIL)
        (GO WHILELABEL))
      (RETURN (REVERSE TMPPOLYNOM)))) 
(PUT 'POLYNOMMULTIPLYBYVARIABLE 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMMULTIPLYBYVARIABLE 'DEFINED-ON-LINE '56) 
(PUT 'POLYNOMMULTIPLYBYVARIABLE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMMULTIPLYBYVARIABLE 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMMULTIPLYBYVARIABLE (POLYNOM VARIABLE)
    (PROG (TMPPOLYNOMNOVARIABLE POLYNOMITERATOR)
      (SETQ POLYNOMITERATOR POLYNOM)
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOMITERATOR)) (RETURN NIL)))
        (PROGN
         (COND
          ((EQN (MONOMGETVARIABLEDEGREE (CAR POLYNOMITERATOR) VARIABLE) 0)
           (PROGN
            (SETQ TMPPOLYNOMNOVARIABLE
                    (CONS (CAR POLYNOMITERATOR) TMPPOLYNOMNOVARIABLE))
            (RPLACD (RPLACA POLYNOMITERATOR (CADR POLYNOMITERATOR))
                    (CDDR POLYNOMITERATOR))
            NIL))
          (T (PROGN (SETQ POLYNOMITERATOR (CDR POLYNOMITERATOR)) NIL)))
         NIL)
        (GO WHILELABEL))
      (SETQ TMPPOLYNOMNOVARIABLE (CONS NIL TMPPOLYNOMNOVARIABLE))
      (SETQ TMPPOLYNOMNOVARIABLE (REVERSE TMPPOLYNOMNOVARIABLE))
      (SETQ POLYNOMITERATOR TMPPOLYNOMNOVARIABLE)
      (PROG ()
       WHILELABEL
        (COND ((NOT (CAR POLYNOMITERATOR)) (RETURN NIL)))
        (PROGN
         (MONOMMULTIPLYBYVARIABLE (CAR POLYNOMITERATOR) VARIABLE)
         (SETQ POLYNOMITERATOR (CDR POLYNOMITERATOR))
         NIL)
        (GO WHILELABEL))
      (POLYNOMADD POLYNOM TMPPOLYNOMNOVARIABLE))) 
(PUT 'POLYNOMMULTIPLYBYMONOM 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMMULTIPLYBYMONOM 'DEFINED-ON-LINE '86) 
(PUT 'POLYNOMMULTIPLYBYMONOM 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMMULTIPLYBYMONOM 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMMULTIPLYBYMONOM (POLYNOM MONOM)
    (COND ((NULL POLYNOM) NIL)
          (T
           (PROG (TMPPOLYNOM EXPONENT)
             (SETQ TMPPOLYNOM (POLYNOMCLONE POLYNOM))
             (SETQ EXPONENT (GETV MONOM 1))
             (PROG ()
              WHILELABEL
               (COND ((NOT (CAR EXPONENT)) (RETURN NIL)))
               (PROGN
                (POLYNOMMULTIPLYBYVARIABLE TMPPOLYNOM (CAR EXPONENT))
                (SETQ EXPONENT (CDR EXPONENT))
                NIL)
               (GO WHILELABEL))
             (RETURN TMPPOLYNOM))))) 
(PUT 'POLYNOMADD 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMADD 'DEFINED-ON-LINE '102) 
(PUT 'POLYNOMADD 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMADD 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMADD (POLYNOM1 POLYNOM2)
    (PROG (TMPPOLYNOM1 TMPPOLYNOM2 MONOMCOMPARE)
      (SETQ MONOMCOMPARE 0)
      (SETQ TMPPOLYNOM1 POLYNOM1)
      (SETQ TMPPOLYNOM2 POLYNOM2)
      (PROG ()
       WHILELABEL
        (COND ((NOT (AND (CAR TMPPOLYNOM1) (CAR TMPPOLYNOM2))) (RETURN NIL)))
        (PROGN
         (SETQ MONOMCOMPARE (MONOMCOMPARE (CAR TMPPOLYNOM1) (CAR TMPPOLYNOM2)))
         (COND
          ((EQUAL MONOMCOMPARE 1)
           (PROGN (SETQ TMPPOLYNOM1 (CDR TMPPOLYNOM1)) NIL))
          ((EQUAL MONOMCOMPARE (MINUS 1))
           (PROGN
            (RPLACA
             (RPLACD TMPPOLYNOM1 (CONS (CAR TMPPOLYNOM1) (CDR TMPPOLYNOM1)))
             (CAR TMPPOLYNOM2))
            (SETQ TMPPOLYNOM1 (CDR TMPPOLYNOM1))
            (SETQ TMPPOLYNOM2 (CDR TMPPOLYNOM2))
            NIL))
          (T
           (PROGN
            (RPLACD (RPLACA TMPPOLYNOM1 (CADR TMPPOLYNOM1)) (CDDR TMPPOLYNOM1))
            (SETQ TMPPOLYNOM2 (CDR TMPPOLYNOM2))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (COND
       ((CAR TMPPOLYNOM2)
        (PROGN
         ((LAMBDA (Y) (RPLACD (RPLACA Y (CADR Y)) (CDDR Y)))
          (RPLACD TMPPOLYNOM1 TMPPOLYNOM2))
         NIL)))
      (RETURN POLYNOM1))) 
(PUT 'POLYNOMREDUCEBY 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMREDUCEBY 'DEFINED-ON-LINE '134) 
(PUT 'POLYNOMREDUCEBY 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMREDUCEBY 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMREDUCEBY (POLYNOM1 POLYNOM2)
    (PROG (BREAK TMPMONOM TMPPOLYNOM)
      (PROG ()
       WHILELABEL
        (COND ((NOT (NOT BREAK)) (RETURN NIL)))
        (PROGN
         (SETQ TMPPOLYNOM POLYNOM1)
         (PROG ()
          WHILELABEL
           (COND
            ((NOT
              (AND (CAR TMPPOLYNOM)
                   (NOT (MONOMISDIVISIBLEBY (CAR TMPPOLYNOM) (CAR POLYNOM2)))))
             (RETURN NIL)))
           (PROGN (SETQ TMPPOLYNOM (CDR TMPPOLYNOM)) NIL)
           (GO WHILELABEL))
         (COND ((NOT (CAR TMPPOLYNOM)) (PROGN (SETQ BREAK T) NIL))
               (T
                (PROGN
                 (SETQ TMPMONOM (MONOMDIVIDE (CAR TMPPOLYNOM) (CAR POLYNOM2)))
                 (POLYNOMADD POLYNOM1
                  (POLYNOMMULTIPLYBYMONOM POLYNOM2 TMPMONOM))
                 NIL)))
         NIL)
        (GO WHILELABEL))
      (SETQ FLUIDBIBASISREDUCTIONSMADE (IADD1 FLUIDBIBASISREDUCTIONSMADE)))) 
(PUT 'POLYNOMHEADREDUCEBY 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMHEADREDUCEBY 'DEFINED-ON-LINE '160) 
(PUT 'POLYNOMHEADREDUCEBY 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMHEADREDUCEBY 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMHEADREDUCEBY (POLYNOM1 POLYNOM2)
    (PROG (BREAK TMPMONOM)
      (PROG ()
       WHILELABEL
        (COND ((NOT (AND (CAR POLYNOM1) (NOT BREAK))) (RETURN NIL)))
        (PROGN
         (COND
          ((MONOMISDIVISIBLEBY (CAR POLYNOM1) (CAR POLYNOM2))
           (PROGN
            (SETQ TMPMONOM (MONOMDIVIDE (CAR POLYNOM1) (CAR POLYNOM2)))
            (POLYNOMADD POLYNOM1 (POLYNOMMULTIPLYBYMONOM POLYNOM2 TMPMONOM))
            NIL))
          (T (PROGN (SETQ BREAK T) NIL)))
         NIL)
        (GO WHILELABEL))
      (SETQ FLUIDBIBASISREDUCTIONSMADE (IADD1 FLUIDBIBASISREDUCTIONSMADE)))) 
(PUT 'POLYNOMCOMPARE 'NUMBER-OF-ARGS 2) 
(PUT 'POLYNOMCOMPARE 'DEFINED-ON-LINE '178) 
(PUT 'POLYNOMCOMPARE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMCOMPARE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE POLYNOMCOMPARE (POLYNOM1 POLYNOM2)
    (PROG (TMPPOLYITERATOR1 TMPPOLYITERATOR2 MONOMCOMPARE)
      (SETQ MONOMCOMPARE 0)
      (SETQ TMPPOLYITERATOR1 POLYNOM1)
      (SETQ TMPPOLYITERATOR2 POLYNOM2)
      (PROG ()
       WHILELABEL
        (COND
         ((NOT (AND (CAR TMPPOLYITERATOR1) (CAR TMPPOLYITERATOR2)))
          (RETURN NIL)))
        (PROGN
         (SETQ MONOMCOMPARE
                 (MONOMCOMPARE (CAR TMPPOLYITERATOR1) (CAR TMPPOLYITERATOR2)))
         (COND
          ((EQUAL MONOMCOMPARE 1)
           (PROGN (SETQ TMPPOLYITERATOR2 (CONS NIL NIL)) NIL))
          ((EQUAL MONOMCOMPARE (MINUS 1))
           (PROGN (SETQ TMPPOLYITERATOR1 (CONS NIL NIL)) NIL))
          (T
           (PROGN
            (SETQ TMPPOLYITERATOR1 (CDR TMPPOLYITERATOR1))
            (SETQ TMPPOLYITERATOR2 (CDR TMPPOLYITERATOR2))
            NIL)))
         NIL)
        (GO WHILELABEL))
      (COND ((CAR TMPPOLYITERATOR1) (PROGN (RETURN 1) NIL))
            ((CAR TMPPOLYITERATOR2) (PROGN (RETURN (MINUS 1)) NIL))
            (T (PROGN (RETURN 0) NIL))))) 
(PUT 'POLYNOMREAD 'NUMBER-OF-ARGS 1) 
(PUT 'POLYNOMREAD 'DEFINED-ON-LINE '216) 
(PUT 'POLYNOMREAD 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMREAD 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE POLYNOMREAD (POLYNOM)
    (COND ((NULL POLYNOM) (PROGN (CONS NIL NIL)))
          ((OR (ATOM POLYNOM) (ATOM (CAR POLYNOM)))
           (PROGN
            (COND
             ((EQN (REMAINDER POLYNOM 2) 1)
              (PROGN (CONS (CREATEMONOMUNIT) (CONS NIL NIL))))
             (T (PROGN (CONS NIL NIL))))))
          ((MEMBER (CAAAR POLYNOM) FLUIDBIBASISVARIABLES)
           (PROGN
            (POLYNOMADD
             (POLYNOMMULTIPLYBYMONOM (POLYNOMREAD (CDAR POLYNOM))
              (CDR
               (ASSOC (CAAAR POLYNOM) FLUIDBIBASISSINGLEVARIABLEMONOMIALSA)))
             (POLYNOMREAD (CDR POLYNOM)))))
          (T
           (PROGN
            (POLYNOMADD
             (POLYNOMMULTIPLYBYMONOM (POLYNOMREAD (CDAR POLYNOM))
              (CREATEMONOMUNIT))
             (POLYNOMREAD (CDR POLYNOM)))
            NIL)))) 
(PUT 'POLYNOMWRITE 'NUMBER-OF-ARGS 1) 
(PUT 'POLYNOMWRITE 'DEFINED-ON-LINE '244) 
(PUT 'POLYNOMWRITE 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMWRITE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE POLYNOMWRITE (POLYNOM)
    (COND ((NULL (CAR POLYNOM)) (PROGN NIL))
          ((EQUAL (GETV (CAR POLYNOM) 0) 0) (PROGN 1))
          (T
           (PROGN
            (CONS (MONOMWRITE (CAR POLYNOM)) (POLYNOMWRITE (CDR POLYNOM))))))) 
(PUT 'POLYNOMPRINT 'NUMBER-OF-ARGS 1) 
(PUT 'POLYNOMPRINT 'DEFINED-ON-LINE '259) 
(PUT 'POLYNOMPRINT 'DEFINED-IN-FILE 'BIBASIS/BIBASIS_POLYNOM.RED) 
(PUT 'POLYNOMPRINT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE POLYNOMPRINT (POLYNOM)
    (PROG (CURRENTMONOM)
      (SETQ CURRENTMONOM POLYNOM)
      (COND ((NULL (CAR CURRENTMONOM)) (PROGN (PRIN2 "0") NIL))
            (T
             (PROGN
              (MONOMPRINT (CAR CURRENTMONOM))
              (SETQ CURRENTMONOM (CDR CURRENTMONOM))
              (PROG ()
               WHILELABEL
                (COND ((NOT (CAR CURRENTMONOM)) (RETURN NIL)))
                (PROGN
                 (PRIN2 " + ")
                 (MONOMPRINT (CAR CURRENTMONOM))
                 (SETQ CURRENTMONOM (CDR CURRENTMONOM))
                 NIL)
                (GO WHILELABEL))
              NIL))))) 
(ENDMODULE) 