(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'DEFINTC)) 
(FLUID '(MELLIN-TRANSFORMS* MELLIN-COEFFICIENTS*)) 
(SETQ MELLIN-TRANSFORMS* (MKVECT 200)) 
(PUTV MELLIN-TRANSFORMS* 0 '(1 . 1)) 
(PUTV MELLIN-TRANSFORMS* 1 '(NIL (1 0 0 1) NIL (NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 2
      '(NIL (1 0 0 2) NIL ((QUOTIENT 1 2) NIL) (SQRT PI)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 25
      '(NIL (1 0 0 2) NIL ((QUOTIENT 1 2) NIL) (MINUS (SQRT PI))
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 3
      '(NIL (1 0 0 2) NIL (NIL (QUOTIENT 1 2)) (SQRT PI)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 7
      '(NIL (2 0 2 2) (1 1) (NIL (QUOTIENT 1 2)) (QUOTIENT (SQRT PI) 2)
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 8
      '(NIL (0 2 2 2) ((QUOTIENT 1 2) 1) (NIL NIL) (QUOTIENT (SQRT PI) 2)
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 9
      '(NIL (1 2 2 2) ((QUOTIENT 1 2) 1) ((QUOTIENT 1 2) NIL) (QUOTIENT 1 2)
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 10
      '(NIL (1 0 1 3) (1) ((QUOTIENT 1 2) 1 NIL) (EXPT PI (QUOTIENT 3 2))
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 11
      '(NIL (1 0 1 3) ((QUOTIENT 1 2)) (NIL (QUOTIENT 1 2) (QUOTIENT 1 2))
        (EXPT PI (QUOTIENT 3 2)) (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 30 '(NIL (1 0 1 1) (1) (NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 31 '(NIL (0 1 1 1) (1) (NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 32 '(NIL (2 0 2 2) (1 1) (NIL NIL) -1 X)) 
(PUTV MELLIN-TRANSFORMS* 33 '(NIL (0 2 2 2) (1 1) (NIL NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 34 '(NIL (1 2 2 2) (1 1) (1 NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 35 '(NIL (2 1 2 2) (NIL 1) (NIL NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 36 '(NIL (2 0 1 2) (1) (NIL NIL) -1 X)) 
(PUTV MELLIN-TRANSFORMS* 37
      '(NIL (1 1 1 3) (1) ((QUOTIENT 1 2) NIL NIL) (QUOTIENT (SQRT PI) 2)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 38
      '(NIL (2 0 1 3) (1) (NIL NIL (QUOTIENT 1 2)) (QUOTIENT (SQRT PI) -2)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 39
      '(NIL (1 1 2 4) (1 NIL) ((QUOTIENT 1 2) NIL NIL NIL)
        (QUOTIENT (EXPT PI (QUOTIENT 3 2)) -2) (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 41
      '(NIL (1 1 1 2) (1) ((QUOTIENT 1 2) NIL) (QUOTIENT 1 (SQRT PI))
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 42
      '(NIL (2 0 1 2) (1) (NIL (QUOTIENT 1 2)) (QUOTIENT 1 (SQRT PI))
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 43
      '(NIL (1 1 1 3) (1) ((QUOTIENT 3 4) NIL (QUOTIENT 1 4)) (QUOTIENT 1 2)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 44
      '(NIL (1 1 1 3) (1) ((QUOTIENT 1 4) NIL (QUOTIENT 3 4)) (QUOTIENT 1 2)
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 45 '((N) (1 1 1 2) (1) (N NIL) 1 X)) 
(PUTV MELLIN-TRANSFORMS* 50
      '((N) (1 0 0 2) NIL ((QUOTIENT N 2) (MINUS (QUOTIENT N 2))) 1
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 51
      '((N) (2 0 1 3) ((QUOTIENT (MINUS (PLUS N 1)) 2))
        ((QUOTIENT N 2) (MINUS (QUOTIENT N 2)) (QUOTIENT (MINUS (PLUS N 1)) 2))
        1 (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 52
      '((N) (1 0 1 3) ((PLUS (QUOTIENT 1 2) (QUOTIENT N 2)))
        ((QUOTIENT N 2) (MINUS (QUOTIENT N 2))
         (PLUS (QUOTIENT 1 2) (QUOTIENT N 2)))
        PI (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 53
      '((N) (2 0 0 2) NIL ((QUOTIENT N 2) (MINUS (QUOTIENT N 2)))
        (QUOTIENT 1 2) (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 54
      '((N) (1 1 1 3) ((QUOTIENT (PLUS N 1) 2))
        ((QUOTIENT (PLUS N 1) 2) (MINUS (QUOTIENT N 2)) (QUOTIENT N 2)) 1
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 55
      '((N) (1 1 2 4) ((QUOTIENT (PLUS N 1) 2) NIL)
        ((QUOTIENT (PLUS N 1) 2) NIL (QUOTIENT N 2) (MINUS (QUOTIENT N 2)))
        (TIMES (MINUS PI) (SEC (TIMES (QUOTIENT (MINUS N) 2) PI)))
        (QUOTIENT (EXPT X 2) 4))) 
(PUTV MELLIN-TRANSFORMS* 56
      '((N) (2 0 2 2) ((MINUS N) (PLUS N 1)) (NIL NIL) 1
        (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 57
      '((N) (0 2 2 2) (1 1) ((MINUS N) (PLUS N 1)) 1 (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 58
      '((N) (2 0 2 2) ((DIFFERENCE (QUOTIENT 1 2) N) (PLUS (QUOTIENT 1 2) N))
        (NIL (QUOTIENT 1 2)) (SQRT PI) (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 59
      '((N) (0 2 2 2) (NIL (QUOTIENT 1 2)) (N (MINUS N)) (SQRT PI)
        (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 60
      '((N) (2 0 2 2)
        ((PLUS (QUOTIENT 3 2) N) (DIFFERENCE (MINUS (QUOTIENT 1 2)) N))
        (NIL (QUOTIENT 1 2)) (QUOTIENT (PLUS N 1) (TIMES 2 (SQRT PI)))
        (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 61
      '((N) (0 2 2 2) ((QUOTIENT 3 2) 2) ((MINUS N) (PLUS N 2))
        (QUOTIENT (PLUS N 1) (TIMES 2 (SQRT PI))) (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 62
      '((N) (1 0 1 2) (PLUS (QUOTIENT N 2) 1)
        ((DIFFERENCE (QUOTIENT N 2) (QUOTIENT N 2))
         (DIFFERENCE (QUOTIENT 1 2)
                     (DIFFERENCE (QUOTIENT N 2) (QUOTIENT N 2))))
        (TIMES (EXPT (MINUS 1) (QUOTIENT N 2)) (SQRT PI) (FACTORIAL N))
        (EXPT X 2))) 
(PUTV MELLIN-TRANSFORMS* 63
      '((N L) (1 0 1 2) ((PLUS N 1)) (0 (MINUS L)) (GAMMA (PLUS L N 1)) X)) 
(PUTV MELLIN-TRANSFORMS* 64
      '((N L) (2 0 2 2)
        ((PLUS L N (QUOTIENT 1 2)) (DIFFERENCE (QUOTIENT 1 2) (QUOTIENT 1 N)))
        (0 (DIFFERENCE (QUOTIENT 1 2) L))
        (QUOTIENT (TIMES 2 L (GAMMA (PLUS L (QUOTIENT 1 2)))) (FACTORIAL N))
        (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 65
      '((N L) (0 2 2 2) ((PLUS L (QUOTIENT 1 2)) (TIMES 2 L))
        ((MINUS N) (PLUS (TIMES 2 L) N))
        (QUOTIENT (TIMES 2 L (GAMMA (PLUS L (QUOTIENT 1 2)))) (FACTORIAL N))
        (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 66
      '((N R S) (2 0 2 2) ((PLUS R N 1) (DIFFERENCE (MINUS S) N)) (0 (MINUS S))
        (QUOTIENT (GAMMA (PLUS R N 1)) (FACTORIAL N)) (QUOTIENT (PLUS X 1) 2))) 
(PUTV MELLIN-TRANSFORMS* 67
      '((N R S) (0 2 2 2) ((PLUS R 1) (PLUS R S 1)) ((MINUS N) (PLUS R S N 1))
        (QUOTIENT (GAMMA (PLUS R N 1)) (FACTORIAL N)) (QUOTIENT (PLUS X 1) 2))) 
(SETQ MELLIN-COEFFICIENTS* (MKVECT 200)) 
(ENDMODULE) 