(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'F5PARAM)) 
(REVISION 'F5PARAM "$Id: f5param.red 6359 2022-07-29 06:13:09Z thomas-sturm $") 
(COPYRIGHT 'F5PARAM "(c) 2022 A. Demin, T. Sturm, MPI Informatics, Germany") 
(FLUID
 '(PARAM_ASSUMPTIONSSPOL* PARAM_ASSUMPTIONSRED* PARAM_ASSUMPTIONSINPUT*
   PARAM_ASSUMPTIONSNORMALIZE*)) 
(MKOP 'NEQ) 
(INFIX (LIST 'NEQ)) 
(NEWTOK '((< >) NEQ)) 
(FLAG '(NEQ) 'SPACED) 
(PUT 'PARAM_ISCONSTASSUMPTION 'NUMBER-OF-ARGS 1) 
(DE PARAM_ISCONSTASSUMPTION (POLY)
    (OR (ATOM (CAR POLY)) (ATOM (CAR (CAR POLY))))) 
(PUT 'PARAM_PREPAREINEQ 'NUMBER-OF-ARGS 1) 
(DE PARAM_PREPAREINEQ (POLY)
    (PROG (NUM)
      (SETQ NUM (CAR POLY))
      (COND ((MINUSF NUM) (SETQ NUM (NEGF NUM))))
      (SETQ NUM (SFTO_SQFPARTF NUM))
      (RETURN (LIST 'NEQ (PREPF NUM) 0)))) 
(PUT 'PARAM_ADDASSUMPTIONSPOL 'NUMBER-OF-ARGS 1) 
(DE PARAM_ADDASSUMPTIONSPOL (POLY)
    (COND
     ((NOT (PARAM_ISCONSTASSUMPTION POLY))
      (SETQ PARAM_ASSUMPTIONSSPOL*
              (LTO_INSERT (PARAM_PREPAREINEQ POLY) PARAM_ASSUMPTIONSSPOL*))))) 
(PUT 'PARAM_ADDASSUMPTIONRED 'NUMBER-OF-ARGS 1) 
(DE PARAM_ADDASSUMPTIONRED (POLY)
    (COND
     ((NOT (PARAM_ISCONSTASSUMPTION POLY))
      (SETQ PARAM_ASSUMPTIONSRED*
              (LTO_INSERT (PARAM_PREPAREINEQ POLY) PARAM_ASSUMPTIONSRED*))))) 
(PUT 'PARAM_ADDASSUMPTIONINPUT 'NUMBER-OF-ARGS 1) 
(DE PARAM_ADDASSUMPTIONINPUT (POLY)
    (COND
     ((NOT (PARAM_ISCONSTASSUMPTION POLY))
      (SETQ PARAM_ASSUMPTIONSINPUT*
              (LTO_INSERT (PARAM_PREPAREINEQ POLY) PARAM_ASSUMPTIONSINPUT*))))) 
(PUT 'PARAM_ADDASSUMPTIONNORMALIZE 'NUMBER-OF-ARGS 1) 
(DE PARAM_ADDASSUMPTIONNORMALIZE (POLY)
    (COND
     ((NOT (PARAM_ISCONSTASSUMPTION POLY))
      (SETQ PARAM_ASSUMPTIONSNORMALIZE*
              (LTO_INSERT (PARAM_PREPAREINEQ POLY)
                          PARAM_ASSUMPTIONSNORMALIZE*))))) 
(PUT 'PARAM_CLEARASSUMPTIONS 'NUMBER-OF-ARGS 0) 
(DE PARAM_CLEARASSUMPTIONS NIL
    (PROGN
     (SETQ PARAM_ASSUMPTIONSSPOL* NIL)
     (SETQ PARAM_ASSUMPTIONSRED* NIL)
     (SETQ PARAM_ASSUMPTIONSNORMALIZE* NIL)
     (SETQ PARAM_ASSUMPTIONSINPUT* NIL))) 
(PUT 'PARAM_DUMPASSUMPTIONS 'NUMBER-OF-ARGS 0) 
(DE PARAM_DUMPASSUMPTIONS NIL
    (LTO_UNIONN
     (LIST PARAM_ASSUMPTIONSSPOL* PARAM_ASSUMPTIONSRED*
           PARAM_ASSUMPTIONSNORMALIZE* PARAM_ASSUMPTIONSINPUT*))) 
(ENDMODULE) 