(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(FLUID '(GB_RCSID* GB_COPYRIGHT*)) 
(SETQ GB_RCSID* "$Id: gb.red 5872 2021-07-29 14:53:49Z arthurcnorman $") 
(SETQ GB_COPYRIGHT* "Copyright (c) 1999-2009 A. Dolzmann and T. Sturm") 
(MODULE (LIST 'GB)) 
(LOAD-PACKAGE 'EZGCD) 
(SWITCH
 (LIST 'GBLTBASIS 'GROEBOPT 'CGBSTAT 'CGBFULLRED 'CGBVERBOSE 'CGBCONTRED
       'CGBCOUNTHF 'CGBCHECKG)) 
(FLUID
 '(*GLTBASIS *GROEBOPT *CGBSTAT *CGBFULLRED *CGBVERBOSE *CGBCONTRED *CGBCOUNTHF
   *CGBCHECKG *CGBSLOPPY *CGBSUGAR)) 
(OFF1 'CGBSTAT) 
(ON1 'CGBFULLRED) 
(OFF1 'CGBVERBOSE) 
(OFF1 'CGBCONTRED) 
(OFF1 'CGBCOUNTHF) 
(OFF1 'CGBCHECKG) 
(SETQ *CGBSLOPPY T) 
(SETQ *CGBSUGAR NIL) 
(SWITCH (LIST 'CGBUPDB)) 
(FLUID '(CGB_UPDBCOUNT* CGB_UPDBCOUNTP* CGB_UPDBCALLS* *CGBUPDB)) 
(OFF1 'CGBUPDB) 
(FLUID '(INTVDPVARS*)) 
(FLUID '(*GCD *EZGCD *FACTOR *EXP DMODE* DEPL* *BACKTRACE)) 
(FLUID '(SECONDVALUE* THIRDVALUE*)) 
(FLUID '(DIP_VARS* VDP_PCOUNT*)) 
(FLUID
 '(CGB_HCOUNT* CGB_HZEROCOUNT* CGB_TR1COUNT* CGB_TR2COUNT* CGB_TR3COUNT*
   CGB_B4COUNT* CGB_STRANGECOUNT* CGB_PAIRCOUNT* CGB_HFACCOUNT* CGB_GCOUNT*
   CGB_GSTAT* CGB_GBCOUNT*)) 
(GLOBAL '(GVARSLAST GLTB)) 
(SETQ GLTB (PROGN (SETQ ALGLIST* (CONS NIL NIL)) (LIST 'LIST))) 
(FLUID '(CGB_CONTCOUNT* CGB_MINCONTRED*)) 
(SETQ CGB_MINCONTRED* 20) 
(PUT 'GB_MKINTERFACE 'DEFINED-ON-LINE '96) 
(PUT 'GB_MKINTERFACE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_MKINTERFACE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DM GB_MKINTERFACE (ARGL)
    (PROG (A2SL1 A2SL2 DEFL XVFN S2A S2S S MODES ARGS BNAME LEN SM PRGN AMI SMI
           PSVAL POSTFIX)
      (SETQ BNAME (EVAL (NTH ARGL 2)))
      (SETQ A2SL1 (EVAL (NTH ARGL 3)))
      (SETQ A2SL2 (EVAL (NTH ARGL 4)))
      (SETQ DEFL (EVAL (NTH ARGL 5)))
      (SETQ XVFN (EVAL (NTH ARGL 6)))
      (SETQ S2A (EVAL (NTH ARGL 7)))
      (SETQ S2S (EVAL (NTH ARGL 8)))
      (SETQ S (EVAL (NTH ARGL 9)))
      (SETQ POSTFIX (EVAL (NTH ARGL 10)))
      (SETQ MODES (EVAL (NTH ARGL 11)))
      (SETQ LEN (LENGTH A2SL1))
      (SETQ ARGS
              (PROG (I FORALL-RESULT FORALL-ENDPTR)
                (SETQ I 1)
                (COND ((MINUSP (DIFFERENCE (PLUS LEN 3) I)) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR (CONS (MKID 'A I) NIL)))
               LOOPLABEL
                (SETQ I (PLUS2 I 1))
                (COND
                 ((MINUSP (DIFFERENCE (PLUS LEN 3) I)) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR (CONS (MKID 'A I) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (SETQ SM (INTERN (COMPRESS (APPEND '(G B _) (EXPLODE BNAME)))))
      (COND
       ((OR (NULL MODES) (EQ MODES 'SM))
        (PROGN
         (SETQ SMI (INTERN (COMPRESS (NCONC (EXPLODE SM) (EXPLODE POSTFIX)))))
         (SETQ PRGN
                 (CONS (LIST 'PUT (MKQUOTE SMI) ''NUMBER-OF-ARGS (PLUS LEN 3))
                       PRGN))
         (SETQ PRGN
                 (CONS
                  (LIST 'DE SMI ARGS
                        (LIST 'GB_INTERFACE$ (MKQUOTE SM) (MKQUOTE A2SL1)
                              (MKQUOTE A2SL2) (MKQUOTE DEFL) (MKQUOTE XVFN)
                              (MKQUOTE S2A) (MKQUOTE S2S) (MKQUOTE S) T
                              (CONS 'LIST ARGS)))
                  PRGN)))))
      (COND
       ((OR (NULL MODES) (EQ MODES 'AM))
        (PROGN
         (SETQ AMI BNAME)
         (SETQ PSVAL (INTERN (COMPRESS (NCONC (EXPLODE AMI) '(! $)))))
         (SETQ PRGN
                 (CONS (LIST 'PUT (MKQUOTE AMI) ''PSOPFN (MKQUOTE PSVAL))
                       PRGN))
         (SETQ PRGN (CONS (LIST 'PUT (MKQUOTE PSVAL) ''NUMBER-OF-ARGS 1) PRGN))
         (SETQ PRGN
                 (CONS (LIST 'PUT (MKQUOTE PSVAL) ''CLEANUPFN ''GB_CLEANUP)
                       PRGN))
         (SETQ PRGN
                 (CONS
                  (LIST 'DE PSVAL '(ARGL)
                        (LIST 'GB_INTERFACE$ (MKQUOTE SM) (MKQUOTE A2SL1)
                              (MKQUOTE A2SL2) (MKQUOTE DEFL) (MKQUOTE XVFN)
                              (MKQUOTE S2A) (MKQUOTE S2S) (MKQUOTE S) NIL
                              'ARGL))
                  PRGN)))))
      (RETURN (CONS 'PROGN PRGN)))) 
(DE GB$ (ARGL)
    (GB_INTERFACE$ 'GB_GB '(GB_A2S-PSYS) '(GB_A2S2-PSYS) 'NIL 'GB_XVARS-PSYS
     'GB_S2A-GBX 'GB_S2S-GB 'T NIL ARGL)) 
(PUT 'GB$ 'CLEANUPFN 'GB_CLEANUP) 
(PUT 'GB$ 'NUMBER-OF-ARGS 1) 
(PUT 'GB 'PSOPFN 'GB$) 
(DE GB_GBF (A1 A2 A3 A4)
    (GB_INTERFACE$ 'GB_GB '(GB_A2S-PSYS) '(GB_A2S2-PSYS) 'NIL 'GB_XVARS-PSYS
     'GB_S2A-GBX 'GB_S2S-GB 'T T (LIST A1 A2 A3 A4))) 
(PUT 'GB_GBF 'NUMBER-OF-ARGS 4) 
(DE REDUCE$ (ARGL)
    (GB_INTERFACE$ 'GB_REDUCE '(GB_A2S-POL GB_A2S-PSYS)
     '(GB_A2S2-POL GB_A2S2-PSYS) 'NIL 'GB_XVARS-PPSYS 'GB_S2A-POL 'GB_S2S-POL
     'T NIL ARGL)) 
(PUT 'REDUCE$ 'CLEANUPFN 'GB_CLEANUP) 
(PUT 'REDUCE$ 'NUMBER-OF-ARGS 1) 
(PUT 'REDUCE 'PSOPFN 'REDUCE$) 
(DE GB_REDUCEF (A1 A2 A3 A4 A5)
    (GB_INTERFACE$ 'GB_REDUCE '(GB_A2S-POL GB_A2S-PSYS)
     '(GB_A2S2-POL GB_A2S2-PSYS) 'NIL 'GB_XVARS-PPSYS 'GB_S2A-POL 'GB_S2S-POL
     'T T (LIST A1 A2 A3 A4 A5))) 
(PUT 'GB_REDUCEF 'NUMBER-OF-ARGS 5) 
(DE LTB$ (ARGL)
    (GB_INTERFACE$ 'GB_LTB '(GB_A2S-PSYS) '(GB_A2S2-PSYS) 'NIL 'GB_XVARS-PSYS
     'GB_S2A-GB 'GB_S2S-GB 'T NIL ARGL)) 
(PUT 'LTB$ 'CLEANUPFN 'GB_CLEANUP) 
(PUT 'LTB$ 'NUMBER-OF-ARGS 1) 
(PUT 'LTB 'PSOPFN 'LTB$) 
(DE GB_LTBF (A1 A2 A3 A4)
    (GB_INTERFACE$ 'GB_LTB '(GB_A2S-PSYS) '(GB_A2S2-PSYS) 'NIL 'GB_XVARS-PSYS
     'GB_S2A-GB 'GB_S2S-GB 'T T (LIST A1 A2 A3 A4))) 
(PUT 'GB_LTBF 'NUMBER-OF-ARGS 4) 
(PUT 'GB_A2S-PSYS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_A2S-PSYS 'DEFINED-ON-LINE '149) 
(PUT 'GB_A2S-PSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_A2S-PSYS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_A2S-PSYS (L)
    (PROG (W RESL)
      (PROG (J)
        (SETQ J (GETRLIST (REVAL1 L T)))
       LAB
        (COND ((NULL J) (RETURN NIL)))
        ((LAMBDA (J)
           (PROGN
            (SETQ W (CAR (SIMP J)))
            (COND ((AND W (NOT (MEMBER W RESL))) (SETQ RESL (CONS W RESL))))))
         (CAR J))
        (SETQ J (CDR J))
        (GO LAB))
      (RETURN (SORT RESL 'ORDP)))) 
(PUT 'GB_A2S2-PSYS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_A2S2-PSYS 'DEFINED-ON-LINE '161) 
(PUT 'GB_A2S2-PSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_A2S2-PSYS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_A2S2-PSYS (FL)
    (PROG (X FORALL-RESULT FORALL-ENDPTR)
      (SETQ X FL)
      (COND ((NULL X) (RETURN NIL)))
      (SETQ FORALL-RESULT
              (SETQ FORALL-ENDPTR
                      (CONS ((LAMBDA (X) (VDP_F2VDP X)) (CAR X)) NIL)))
     LOOPLABEL
      (SETQ X (CDR X))
      (COND ((NULL X) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR (CONS ((LAMBDA (X) (VDP_F2VDP X)) (CAR X)) NIL))
      (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
      (GO LOOPLABEL))) 
(PUT 'GB_S2A-GB 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2A-GB 'DEFINED-ON-LINE '164) 
(PUT 'GB_S2A-GB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2A-GB 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_S2A-GB (U)
    (CONS 'LIST
          (PROG (X FORALL-RESULT FORALL-ENDPTR)
            (SETQ X U)
            (COND ((NULL X) (RETURN NIL)))
            (SETQ FORALL-RESULT
                    (SETQ FORALL-ENDPTR
                            (CONS ((LAMBDA (X) (VDP_2A X)) (CAR X)) NIL)))
           LOOPLABEL
            (SETQ X (CDR X))
            (COND ((NULL X) (RETURN FORALL-RESULT)))
            (RPLACD FORALL-ENDPTR (CONS ((LAMBDA (X) (VDP_2A X)) (CAR X)) NIL))
            (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
            (GO LOOPLABEL)))) 
(PUT 'GB_S2A-GBX 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2A-GBX 'DEFINED-ON-LINE '169) 
(PUT 'GB_S2A-GBX 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2A-GBX 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_S2A-GBX (L)
    (PROGN
     (COND
      (*GLTBASIS
       (SETQ GLTB (PROGN (SETQ ALGLIST* (CONS NIL NIL)) (GB_GB2GLTB L)))))
     (GB_S2A-GB L))) 
(DE GB_S2S-GB (L) (GB_GB-SFL L)) 
(PUT 'GB_S2S-GB 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2S-GB 'DEFINED-ON-LINE '179) 
(PUT 'GB_S2S-GB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2S-GB 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_S2S-GB 'INLINE '(LAMBDA (L) (GB_GB-SFL L))) 
(PUT 'GB_S2A-GSYS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2A-GSYS 'DEFINED-ON-LINE '182) 
(PUT 'GB_S2A-GSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2A-GSYS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_S2A-GSYS (L)
    (CONS 'LIST
          (PROG (X FORALL-RESULT FORALL-ENDPTR)
            (SETQ X L)
            (COND ((NULL X) (RETURN NIL)))
            (SETQ FORALL-RESULT
                    (SETQ FORALL-ENDPTR
                            (CONS
                             ((LAMBDA (X)
                                (LIST 'LIST
                                      (RL_MK*FOF
                                       (COND
                                        ((AND (CAR X) (CDR (CAR X)))
                                         (CONS 'AND (CAR X)))
                                        ((NULL (CAR X))
                                         (COND ((EQ 'AND 'AND) 'TRUE)
                                               (T 'FALSE)))
                                        (T (CAR (CAR X)))))
                                      (GB_S2A-GB (CADR X))))
                              (CAR X))
                             NIL)))
           LOOPLABEL
            (SETQ X (CDR X))
            (COND ((NULL X) (RETURN FORALL-RESULT)))
            (RPLACD FORALL-ENDPTR
                    (CONS
                     ((LAMBDA (X)
                        (LIST 'LIST
                              (RL_MK*FOF
                               (COND
                                ((AND (CAR X) (CDR (CAR X)))
                                 (CONS 'AND (CAR X)))
                                ((NULL (CAR X))
                                 (COND ((EQ 'AND 'AND) 'TRUE) (T 'FALSE)))
                                (T (CAR (CAR X)))))
                              (GB_S2A-GB (CADR X))))
                      (CAR X))
                     NIL))
            (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
            (GO LOOPLABEL)))) 
(PUT 'GB_S2S-GSYS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2S-GSYS 'DEFINED-ON-LINE '186) 
(PUT 'GB_S2S-GSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2S-GSYS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_S2S-GSYS (L)
    (PROG (X FORALL-RESULT FORALL-ENDPTR)
      (SETQ X L)
      (COND ((NULL X) (RETURN NIL)))
      (SETQ FORALL-RESULT
              (SETQ FORALL-ENDPTR
                      (CONS
                       ((LAMBDA (X)
                          (LIST
                           (COND
                            ((AND (CAR X) (CDR (CAR X))) (CONS 'AND (CAR X)))
                            ((NULL (CAR X))
                             (COND ((EQ 'AND 'AND) 'TRUE) (T 'FALSE)))
                            (T (CAR (CAR X))))
                           (GB_GB-SFL (CADR X))))
                        (CAR X))
                       NIL)))
     LOOPLABEL
      (SETQ X (CDR X))
      (COND ((NULL X) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              (CONS
               ((LAMBDA (X)
                  (LIST
                   (COND ((AND (CAR X) (CDR (CAR X))) (CONS 'AND (CAR X)))
                         ((NULL (CAR X))
                          (COND ((EQ 'AND 'AND) 'TRUE) (T 'FALSE)))
                         (T (CAR (CAR X))))
                   (GB_GB-SFL (CADR X))))
                (CAR X))
               NIL))
      (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
      (GO LOOPLABEL))) 
(DE GB_A2S-POL (P) (CAR (SIMP (REVAL1 P T)))) 
(PUT 'GB_A2S-POL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_A2S-POL 'DEFINED-ON-LINE '190) 
(PUT 'GB_A2S-POL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_A2S-POL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_A2S-POL 'INLINE '(LAMBDA (P) (CAR (SIMP (REVAL1 P T))))) 
(DE GB_A2S2-POL (P) (VDP_F2VDP P)) 
(PUT 'GB_A2S2-POL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_A2S2-POL 'DEFINED-ON-LINE '193) 
(PUT 'GB_A2S2-POL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_A2S2-POL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_A2S2-POL 'INLINE '(LAMBDA (P) (VDP_F2VDP P))) 
(DE GB_S2A-POL (P) (VDP_2A P)) 
(PUT 'GB_S2A-POL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2A-POL 'DEFINED-ON-LINE '196) 
(PUT 'GB_S2A-POL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2A-POL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_S2A-POL 'INLINE '(LAMBDA (P) (VDP_2A P))) 
(DE GB_S2S-POL (P) (VDP_2SQ P)) 
(PUT 'GB_S2S-POL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_S2S-POL 'DEFINED-ON-LINE '199) 
(PUT 'GB_S2S-POL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_S2S-POL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_S2S-POL 'INLINE '(LAMBDA (P) (VDP_2SQ P))) 
(DE GB_DUMMY1 (DUMMY) NIL) 
(PUT 'GB_DUMMY1 'NUMBER-OF-ARGS 1) 
(PUT 'GB_DUMMY1 'DEFINED-ON-LINE '202) 
(PUT 'GB_DUMMY1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_DUMMY1 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_DUMMY1 'INLINE '(LAMBDA (DUMMY) NIL)) 
(DE GB_XVARS-PSYS (L VL) (GB_VARS L VL)) 
(PUT 'GB_XVARS-PSYS 'NUMBER-OF-ARGS 2) 
(PUT 'GB_XVARS-PSYS 'DEFINED-ON-LINE '205) 
(PUT 'GB_XVARS-PSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_XVARS-PSYS 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_XVARS-PSYS 'INLINE '(LAMBDA (L VL) (GB_VARS L VL))) 
(DE GB_XVARS-PSYS2 (L CD VL) (GB_VARS L VL)) 
(PUT 'GB_XVARS-PSYS2 'NUMBER-OF-ARGS 3) 
(PUT 'GB_XVARS-PSYS2 'DEFINED-ON-LINE '208) 
(PUT 'GB_XVARS-PSYS2 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_XVARS-PSYS2 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_XVARS-PSYS2 'INLINE '(LAMBDA (L CD VL) (GB_VARS L VL))) 
(DE GB_XVARS-PSYS3 (L CD XVARL VL) (GB_VARS L VL)) 
(PUT 'GB_XVARS-PSYS3 'NUMBER-OF-ARGS 4) 
(PUT 'GB_XVARS-PSYS3 'DEFINED-ON-LINE '211) 
(PUT 'GB_XVARS-PSYS3 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_XVARS-PSYS3 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_XVARS-PSYS3 'INLINE '(LAMBDA (L CD XVARL VL) (GB_VARS L VL))) 
(DE GB_XVARS-PPSYS (P L VL) (GB_VARS (CONS P L) VL)) 
(PUT 'GB_XVARS-PPSYS 'NUMBER-OF-ARGS 3) 
(PUT 'GB_XVARS-PPSYS 'DEFINED-ON-LINE '214) 
(PUT 'GB_XVARS-PPSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_XVARS-PPSYS 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_XVARS-PPSYS 'INLINE '(LAMBDA (P L VL) (GB_VARS (CONS P L) VL))) 
(DE GB_CLEANUP (U V) U) 
(PUT 'GB_CLEANUP 'NUMBER-OF-ARGS 2) 
(PUT 'GB_CLEANUP 'DEFINED-ON-LINE '217) 
(PUT 'GB_CLEANUP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CLEANUP 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_CLEANUP 'INLINE '(LAMBDA (U V) U)) 
(PUT 'GB_INTERFACE$ 'NUMBER-OF-ARGS 10) 
(PUT 'GB_INTERFACE$ 'DEFINED-ON-LINE '220) 
(PUT 'GB_INTERFACE$ 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_INTERFACE$ 'PROCEDURE_TYPE
     '(ARROW
       (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL
              GENERAL GENERAL)
       GENERAL)) 
(DE GB_INTERFACE$ (FNAME A2SL1 A2SL2 DEFL XVFN S2A S2S S SMP ARGL)
    (PROG (W VL NARGL OENV M C X)
      (COND
       ((NOT SMP)
        (PROGN
         (SETQ NARGL (GB_AM-PARGL FNAME A2SL1 ARGL DEFL))
         (SETQ VL (APPLY XVFN (APPEND NARGL (LIST (TD_VARS)))))
         (SETQ OENV (VDP_INIT (CAR VL) (TD_SORTMODE) (TD_SORTEXTENSION)))
         (SETQ GVARSLAST
                 (PROGN (SETQ ALGLIST* (CONS NIL NIL)) (CONS 'LIST (CAR VL))))
         NIL))
       (T
        (PROGN
         (SETQ W (GB_SM-PARGL ARGL))
         (SETQ NARGL (CAR W))
         (SETQ M (CADR W))
         (SETQ C (CADDR W))
         (SETQ X (CADDDR W))
         (SETQ VL (APPLY XVFN (APPEND NARGL (LIST M))))
         (SETQ OENV (VDP_INIT (CAR VL) C X))
         NIL)))
      (SETQ W
              (ERRORSET
               (LIST 'GB_INTERFACE1$ (MKQUOTE FNAME) (MKQUOTE A2SL2)
                     (MKQUOTE S2A) (MKQUOTE S2S) (MKQUOTE S) (MKQUOTE SMP)
                     (MKQUOTE ARGL) (MKQUOTE NARGL) (MKQUOTE (CAR VL))
                     (MKQUOTE (CDR VL)))
               T *BACKTRACE))
      (VDP_CLEANUP OENV)
      (COND ((ERRORP W) (REDERR (LIST "Error during " FNAME))))
      (RETURN (CAR W)))) 
(PUT 'GB_SM-PARGL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_SM-PARGL 'DEFINED-ON-LINE '255) 
(PUT 'GB_SM-PARGL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SM-PARGL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_SM-PARGL (ARGL)
    (PROG (NARGL M C X)
      (SETQ NARGL (REVERSE ARGL))
      (SETQ X (CAR NARGL))
      (SETQ NARGL (CDR NARGL))
      (SETQ C (CAR NARGL))
      (SETQ NARGL (CDR NARGL))
      (SETQ M (CAR NARGL))
      (SETQ NARGL (CDR NARGL))
      (SETQ NARGL (REVERSIP NARGL))
      (RETURN (LIST NARGL M C X)))) 
(PUT 'GB_AM-PARGL 'NUMBER-OF-ARGS 4) 
(PUT 'GB_AM-PARGL 'DEFINED-ON-LINE '268) 
(PUT 'GB_AM-PARGL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_AM-PARGL 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_AM-PARGL (FNAME A2SL1 ARGL DEFL)
    (PROG (L1 L2 L3 W NARGL SCARGL SCDEFL)
      (SETQ L1 0)
      (SETQ L2 0)
      (SETQ L3 0)
      (SETQ L1 (LENGTH ARGL))
      (SETQ L2 (LENGTH A2SL1))
      (SETQ L3 (DIFFERENCE L2 (LENGTH DEFL)))
      (COND
       ((OR (LESSP L1 L3) (GREATERP L1 L2))
        (REDERR
         (LIST FNAME "called with" L1 "arguments instead of" L3 "-" L2))))
      (SETQ SCARGL ARGL)
      (SETQ SCDEFL DEFL)
      (SETQ NARGL
              (PROG (X FORALL-RESULT FORALL-ENDPTR)
                (SETQ X A2SL1)
                (COND ((NULL X) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS
                                 ((LAMBDA (X)
                                    (PROGN
                                     (COND
                                      (SCARGL
                                       (PROGN
                                        (SETQ W (CAR SCARGL))
                                        (SETQ SCARGL (CDR SCARGL))))
                                      (T
                                       (PROGN
                                        (SETQ W (CAR SCDEFL))
                                        (SETQ SCDEFL (CDR SCDEFL)))))
                                     (APPLY X (LIST W))))
                                  (CAR X))
                                 NIL)))
               LOOPLABEL
                (SETQ X (CDR X))
                (COND ((NULL X) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS
                         ((LAMBDA (X)
                            (PROGN
                             (COND
                              (SCARGL
                               (PROGN
                                (SETQ W (CAR SCARGL))
                                (SETQ SCARGL (CDR SCARGL))))
                              (T
                               (PROGN
                                (SETQ W (CAR SCDEFL))
                                (SETQ SCDEFL (CDR SCDEFL)))))
                             (APPLY X (LIST W))))
                          (CAR X))
                         NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (RETURN NARGL))) 
(PUT 'GB_INTERFACE1$ 'NUMBER-OF-ARGS 10) 
(PUT 'GB_INTERFACE1$ 'DEFINED-ON-LINE '291) 
(PUT 'GB_INTERFACE1$ 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_INTERFACE1$ 'PROCEDURE_TYPE
     '(ARROW
       (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL
              GENERAL GENERAL)
       GENERAL)) 
(DE GB_INTERFACE1$ (FNAME A2SL2 S2A S2S S SMP ARGL NARGL M P)
    (PROG (W PL)
      (SETQ PL (COND (S NARGL) (T ARGL)))
      (SETQ ARGL
              (PROG (X FORALL-RESULT FORALL-ENDPTR)
                (SETQ X A2SL2)
                (COND ((NULL X) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS
                                 ((LAMBDA (X)
                                    (PROGN
                                     (SETQ W (CAR PL))
                                     (SETQ PL (CDR PL))
                                     (APPLY X (LIST W))))
                                  (CAR X))
                                 NIL)))
               LOOPLABEL
                (SETQ X (CDR X))
                (COND ((NULL X) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS
                         ((LAMBDA (X)
                            (PROGN
                             (SETQ W (CAR PL))
                             (SETQ PL (CDR PL))
                             (APPLY X (LIST W))))
                          (CAR X))
                         NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (SETQ W (APPLY FNAME ARGL))
      (SETQ W (COND (SMP (APPLY S2S (LIST W))) (T (APPLY S2A (LIST W)))))
      (RETURN W))) 
(DE GB_TT (S1 S2) (EV_LCM (VDP_EVLMON S1) (VDP_EVLMON S2))) 
(PUT 'GB_TT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_TT 'DEFINED-ON-LINE '308) 
(PUT 'GB_TT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_TT 'INLINE '(LAMBDA (S1 S2) (EV_LCM (VDP_EVLMON S1) (VDP_EVLMON S2)))) 
(PUT 'GB_GB-SFL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_GB-SFL 'DEFINED-ON-LINE '312) 
(PUT 'GB_GB-SFL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GB-SFL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_GB-SFL (U)
    (PROG (P FORALL-RESULT FORALL-ENDPTR)
      (SETQ P U)
      (COND ((NULL P) (RETURN NIL)))
      (SETQ FORALL-RESULT
              (SETQ FORALL-ENDPTR
                      (CONS ((LAMBDA (P) (VDP_2F P)) (CAR P)) NIL)))
     LOOPLABEL
      (SETQ P (CDR P))
      (COND ((NULL P) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR (CONS ((LAMBDA (P) (VDP_2F P)) (CAR P)) NIL))
      (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
      (GO LOOPLABEL))) 
(PUT 'GB_DOMAINCHK 'NUMBER-OF-ARGS 0) 
(PUT 'GB_DOMAINCHK 'DEFINED-ON-LINE '317) 
(PUT 'GB_DOMAINCHK 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_DOMAINCHK 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE GB_DOMAINCHK NIL
    (COND
     ((NOT (MEMQ DMODE* '(NIL)))
      (REDERR
       (BLDMSG_INTERNAL "gb does not support domain: %w"
                        (LIST (GET DMODE* 'DNAME))))))) 
(PUT 'GB_VARS 'NUMBER-OF-ARGS 2) 
(PUT 'GB_VARS 'DEFINED-ON-LINE '324) 
(PUT 'GB_VARS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VARS 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_VARS (L VL)
    (PROG (W M P)
      (PROG (F)
        (SETQ F L)
       LAB
        (COND ((NULL F) (RETURN NIL)))
        ((LAMBDA (F) (SETQ W (UNION W (KERNELS F)))) (CAR F))
        (SETQ F (CDR F))
        (GO LAB))
      (COND
       (VL (PROGN (SETQ M (GB_INTERSECTION VL W)) (SETQ P (SETDIFF W VL))))
       (T (SETQ M W)))
      (RETURN (CONS (GB_VARSOPT L M) P)))) 
(PUT 'GB_INTERSECTION 'NUMBER-OF-ARGS 2) 
(PUT 'GB_INTERSECTION 'DEFINED-ON-LINE '340) 
(PUT 'GB_INTERSECTION 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_INTERSECTION 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_INTERSECTION (A B)
    (PROG (X FORALL-RESULT FORALL-ENDPTR)
      (SETQ X A)
     STARTOVER
      (COND ((NULL X) (RETURN NIL)))
      (SETQ FORALL-RESULT
              ((LAMBDA (X) (COND ((MEMBER X B) (LIST X)))) (CAR X)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
      (SETQ X (CDR X))
      (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
     LOOPLABEL
      (COND ((NULL X) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              ((LAMBDA (X) (COND ((MEMBER X B) (LIST X)))) (CAR X)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
      (SETQ X (CDR X))
      (GO LOOPLABEL))) 
(PUT 'GB_VARSOPT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_VARSOPT 'DEFINED-ON-LINE '348) 
(PUT 'GB_VARSOPT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VARSOPT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_VARSOPT (L VL)
    (COND
     ((AND *GROEBOPT (MEMQ (TD_SORTMODE) '(LEX GRADLEX REVGRADLEX)))
      (GB_VDPVORDOPT L VL))
     (T VL))) 
(PUT 'GB_GB2GLTB 'NUMBER-OF-ARGS 1) 
(PUT 'GB_GB2GLTB 'DEFINED-ON-LINE '357) 
(PUT 'GB_GB2GLTB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GB2GLTB 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_GB2GLTB (BASE)
    (CONS 'LIST
          (PROG (J FORALL-RESULT FORALL-ENDPTR)
            (SETQ J BASE)
            (COND ((NULL J) (RETURN NIL)))
            (SETQ FORALL-RESULT
                    (SETQ FORALL-ENDPTR
                            (CONS
                             ((LAMBDA (J)
                                (VDP_2A (VDP_FMON (BC_A2BC 1) (VDP_EVLMON J))))
                              (CAR J))
                             NIL)))
           LOOPLABEL
            (SETQ J (CDR J))
            (COND ((NULL J) (RETURN FORALL-RESULT)))
            (RPLACD FORALL-ENDPTR
                    (CONS
                     ((LAMBDA (J)
                        (VDP_2A (VDP_FMON (BC_A2BC 1) (VDP_EVLMON J))))
                      (CAR J))
                     NIL))
            (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
            (GO LOOPLABEL)))) 
(PUT 'GB_LTB 'NUMBER-OF-ARGS 1) 
(PUT 'GB_LTB 'DEFINED-ON-LINE '361) 
(PUT 'GB_LTB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_LTB 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_LTB (L)
    (PROG (P FORALL-RESULT FORALL-ENDPTR)
      (SETQ P L)
      (COND ((NULL P) (RETURN NIL)))
      (SETQ FORALL-RESULT
              (SETQ FORALL-ENDPTR
                      (CONS
                       ((LAMBDA (P) (VDP_FMON (BC_A2BC 1) (VDP_EVLMON P)))
                        (CAR P))
                       NIL)))
     LOOPLABEL
      (SETQ P (CDR P))
      (COND ((NULL P) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              (CONS
               ((LAMBDA (P) (VDP_FMON (BC_A2BC 1) (VDP_EVLMON P))) (CAR P))
               NIL))
      (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
      (GO LOOPLABEL))) 
(DE GB_GBGGSYS0 (P DUMMY DUMMY1) (GB_GBGSYS P)) 
(PUT 'GB_GBGGSYS0 'NUMBER-OF-ARGS 3) 
(PUT 'GB_GBGGSYS0 'DEFINED-ON-LINE '365) 
(PUT 'GB_GBGGSYS0 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GBGGSYS0 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_GBGGSYS0 'INLINE '(LAMBDA (P DUMMY DUMMY1) (GB_GBGSYS P))) 
(DE GB_GBGSYS0 (P DUMMY) (GB_GBGSYS P)) 
(PUT 'GB_GBGSYS0 'NUMBER-OF-ARGS 2) 
(PUT 'GB_GBGSYS0 'DEFINED-ON-LINE '368) 
(PUT 'GB_GBGSYS0 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GBGSYS0 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_GBGSYS0 'INLINE '(LAMBDA (P DUMMY) (GB_GBGSYS P))) 
(DE GB_GBGSYS (P) (LIST (LIST NIL (GB_GB P) NIL))) 
(PUT 'GB_GBGSYS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_GBGSYS 'DEFINED-ON-LINE '371) 
(PUT 'GB_GBGSYS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GBGSYS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'GB_GBGSYS 'INLINE '(LAMBDA (P) (LIST (LIST NIL (GB_GB P) NIL)))) 
(DE GB_GB0 (P DUMMY) (GB_GB P)) 
(PUT 'GB_GB0 'NUMBER-OF-ARGS 2) 
(PUT 'GB_GB0 'DEFINED-ON-LINE '374) 
(PUT 'GB_GB0 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GB0 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_GB0 'INLINE '(LAMBDA (P DUMMY) (GB_GB P))) 
(PUT 'GB_GB 'NUMBER-OF-ARGS 1) 
(PUT 'GB_GB 'DEFINED-ON-LINE '377) 
(PUT 'GB_GB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_GB 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_GB (P)
    (PROG (SPAC P1 SAVETIME *FACTOR *EXP INTVDPVARS* *GCD *EZGCD DIP_VARS*
           SECONDVALUE* THIRDVALUE* CGB_GSTAT* *CGBSUGAR VDP_PCOUNT*
           CGB_CONTCOUNT* CGB_HCOUNT* CGB_HZEROCOUNT* CGB_TR1COUNT*
           CGB_TR2COUNT* CGB_TR3COUNT* CGB_B4COUNT* CGB_STRANGECOUNT*
           CGB_PAIRCOUNT* CGB_HFACCOUNT* CGB_GCOUNT* CGB_GBCOUNT*
           CGB_UPDBCOUNT* CGB_UPDBCOUNTP* CGB_UPDBCALLS*)
      (SETQ VDP_PCOUNT* 0)
      (SETQ CGB_CONTCOUNT* 0)
      (SETQ CGB_HCOUNT* 0)
      (SETQ CGB_HZEROCOUNT* 0)
      (SETQ CGB_TR1COUNT* 0)
      (SETQ CGB_TR2COUNT* 0)
      (SETQ CGB_TR3COUNT* 0)
      (SETQ CGB_B4COUNT* 0)
      (SETQ CGB_STRANGECOUNT* 0)
      (SETQ CGB_PAIRCOUNT* 0)
      (SETQ CGB_HFACCOUNT* 0)
      (SETQ CGB_GCOUNT* 0)
      (SETQ CGB_GBCOUNT* 0)
      (SETQ CGB_UPDBCOUNT* 0)
      (SETQ CGB_UPDBCOUNTP* 0)
      (SETQ CGB_UPDBCALLS* 0)
      (SETQ *EXP (SETQ *GCD (SETQ *EZGCD T)))
      (SETQ *CGBSUGAR T)
      (COND (*CGBSTAT (SETQ SAVETIME (TIME))))
      (COND (*CGBCHECKG (SETQ CGB_GSTAT* NIL)))
      (SETQ CGB_CONTCOUNT* CGB_MINCONTRED*)
      (COND (*CGBSTAT (SETQ SPAC (GCTIME))))
      (SETQ P1
              (COND (*CGBUPDB (GB_TRAVERSO-STURM-EXPERIMENTAL P))
                    (T (GB_TRAVERSO P))))
      (COND
       (*CGBSTAT
        (PROGN
         (IOTO_TPRIN2T "Statistics for GB computation:")
         (IOTO_PRIN2T
          (LIST "Time: " (DIFFERENCE (TIME) SAVETIME) " ms plus GC time: "
                (DIFFERENCE (GCTIME) SPAC) " ms"))
         (IOTO_PRIN2T (LIST "H-polynomials total: " CGB_HCOUNT*))
         (IOTO_PRIN2T (LIST "H-polynomials zero: " CGB_HZEROCOUNT*))
         (COND
          (*CGBCOUNTHF
           (IOTO_PRIN2T (LIST "H-polynomials reducible: " CGB_HFACCOUNT*))))
         (COND
          (*CGBCHECKG
           (IOTO_PRIN2T
            (LIST "H-polynomials gaussible: " CGB_GCOUNT* " " CGB_GSTAT*))))
         (IOTO_PRIN2T (LIST "Crit Tr1 hits: " CGB_TR1COUNT*))
         (IOTO_PRIN2T (LIST "Crit B4 hits: " CGB_B4COUNT* " (Buchberger 1)"))
         (IOTO_PRIN2T (LIST "Crit Tr2 hits: " CGB_TR2COUNT*))
         (IOTO_PRIN2T (LIST "Crit Tr3 hits: " CGB_TR3COUNT*))
         (COND
          (*CGBUPDB
           (IOTO_PRIN2T
            (LIST "updbase: calls " CGB_UPDBCALLS* ", del " CGB_UPDBCOUNTP* "/"
                  CGB_UPDBCOUNT*))))
         (IOTO_PRIN2T (LIST "Strange reductions: " CGB_STRANGECOUNT*)))))
      (RETURN P1))) 
(PUT 'GB_TRAVERSO-STURM-EXPERIMENTAL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_TRAVERSO-STURM-EXPERIMENTAL 'DEFINED-ON-LINE '420) 
(PUT 'GB_TRAVERSO-STURM-EXPERIMENTAL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO-STURM-EXPERIMENTAL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_TRAVERSO-STURM-EXPERIMENTAL (G0)
    (PROG (GALL G D S H P)
      (SETQ G0
              (PROG (FJ FORALL-RESULT FORALL-ENDPTR)
                (SETQ FJ G0)
               STARTOVER
                (COND ((NULL FJ) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        ((LAMBDA (FJ)
                           (COND
                            ((NOT (VDP_ZERO? FJ))
                             (LIST
                              (VDP_SETSUGAR (VDP_ENUMERATE (VDP_SIMPCONT FJ))
                               (VDP_TDEG FJ))))))
                         (CAR FJ)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
                (SETQ FJ (CDR FJ))
                (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
               LOOPLABEL
                (COND ((NULL FJ) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        ((LAMBDA (FJ)
                           (COND
                            ((NOT (VDP_ZERO? FJ))
                             (LIST
                              (VDP_SETSUGAR (VDP_ENUMERATE (VDP_SIMPCONT FJ))
                               (VDP_TDEG FJ))))))
                         (CAR FJ)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
                (SETQ FJ (CDR FJ))
                (GO LOOPLABEL)))
      (PROG (H)
        (SETQ H G0)
       LAB
        (COND ((NULL H) (RETURN NIL)))
        ((LAMBDA (H)
           (PROGN
            (SETQ P (LIST NIL H H))
            (SETQ H (GB_ENUMERATE H))
            (SETQ D (GB_TRAVERSO-PAIRLIST H G D))
            (SETQ G (NCONC G (LIST H)))
            (SETQ GALL (NCONC GALL (LIST H)))
            NIL))
         (CAR H))
        (SETQ H (CDR H))
        (GO LAB))
      (PROG ()
       WHILELABEL
        (COND ((NOT D) (RETURN NIL)))
        (PROGN
         (COND
          (*CGBVERBOSE
           (PROGN
            (IOTO_PRIN2 (LIST "[" CGB_PAIRCOUNT* "] "))
            (SETQ CGB_PAIRCOUNT* (IDIFFERENCE CGB_PAIRCOUNT* 1)))))
         (SETQ P (CAR D))
         (SETQ D (CDR D))
         (SETQ S (GB_SPOLYNOMIAL P))
         (SETQ H (GB_SIMPCONTNORMALFORM (GB_NORMALFORM S GALL)))
         (SETQ CGB_HCOUNT* (IPLUS2 CGB_HCOUNT* 1))
         (COND
          ((VDP_ZERO? H)
           (PROGN (SETQ CGB_HZEROCOUNT* (IPLUS2 CGB_HZEROCOUNT* 1)) NIL))
          ((EV_ZERO? (VDP_EVLMON H))
           (PROGN (SETQ H (GB_ENUMERATE H)) (SETQ D NIL) (SETQ G (LIST H))))
          (T
           (PROGN
            (COND
             (*CGBCOUNTHF
              (COND
               ((CDDR (FCTRF (VDP_2F H)))
                (SETQ CGB_HFACCOUNT* (IPLUS2 CGB_HFACCOUNT* 1))))))
            (SETQ H (GB_ENUMERATE H))
            (SETQ D (GB_TRAVERSO-PAIRLIST H G D))
            (SETQ GALL (GB_UPDBASE GALL H))
            (SETQ G (NCONC G (LIST H)))))))
        (GO WHILELABEL))
      (RETURN (GB_TRAVERSO-FINAL G)))) 
(PUT 'GB_TRAVERSO 'NUMBER-OF-ARGS 1) 
(PUT 'GB_TRAVERSO 'DEFINED-ON-LINE '461) 
(PUT 'GB_TRAVERSO 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_TRAVERSO (G0)
    (PROG (G D S H P GSTAT)
      (SETQ G0
              (PROG (FJ FORALL-RESULT FORALL-ENDPTR)
                (SETQ FJ G0)
               STARTOVER
                (COND ((NULL FJ) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        ((LAMBDA (FJ)
                           (COND
                            ((NOT (VDP_ZERO? FJ))
                             (LIST
                              (VDP_SETSUGAR (VDP_ENUMERATE (VDP_SIMPCONT FJ))
                               (VDP_TDEG FJ))))))
                         (CAR FJ)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
                (SETQ FJ (CDR FJ))
                (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
               LOOPLABEL
                (COND ((NULL FJ) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        ((LAMBDA (FJ)
                           (COND
                            ((NOT (VDP_ZERO? FJ))
                             (LIST
                              (VDP_SETSUGAR (VDP_ENUMERATE (VDP_SIMPCONT FJ))
                               (VDP_TDEG FJ))))))
                         (CAR FJ)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
                (SETQ FJ (CDR FJ))
                (GO LOOPLABEL)))
      (PROG (H)
        (SETQ H G0)
       LAB
        (COND ((NULL H) (RETURN NIL)))
        ((LAMBDA (H)
           (PROGN
            (SETQ P (LIST NIL H H))
            (SETQ H (GB_ENUMERATE H))
            (SETQ D (GB_TRAVERSO-PAIRLIST H G D))
            (SETQ G (NCONC G (LIST H)))))
         (CAR H))
        (SETQ H (CDR H))
        (GO LAB))
      (COND (*CGBVERBOSE (SETQ CGB_GBCOUNT* (LENGTH G))))
      (PROG ()
       WHILELABEL
        (COND ((NOT D) (RETURN NIL)))
        (PROGN
         (COND
          (*CGBVERBOSE
           (PROGN
            (IOTO_PRIN2 (LIST "[" CGB_PAIRCOUNT* "] "))
            (SETQ CGB_PAIRCOUNT* (IDIFFERENCE CGB_PAIRCOUNT* 1)))))
         (SETQ P (CAR D))
         (SETQ D (CDR D))
         (SETQ S (GB_SPOLYNOMIAL P))
         (SETQ H (GB_SIMPCONTNORMALFORM (GB_NORMALFORM S G)))
         (COND (*CGBSTAT (SETQ CGB_HCOUNT* (IPLUS2 CGB_HCOUNT* 1))))
         (COND
          ((VDP_ZERO? H)
           (COND (*CGBSTAT (SETQ CGB_HZEROCOUNT* (IPLUS2 CGB_HZEROCOUNT* 1)))))
          ((VDP_UNIT? H)
           (PROGN (SETQ H (GB_ENUMERATE H)) (SETQ D NIL) (SETQ G (LIST H))))
          (T
           (PROGN
            (COND
             (*CGBCOUNTHF
              (COND
               ((CDDR (FCTRF (VDP_2F H)))
                (SETQ CGB_HFACCOUNT* (IPLUS2 CGB_HFACCOUNT* 1))))))
            (COND
             (*CGBCHECKG
              (PROGN
               (SETQ GSTAT (GB_CHKGAUSS (VDP_POLY H)))
               (COND
                ((MEMBER 1 GSTAT)
                 (PROGN
                  (SETQ CGB_GCOUNT* (IPLUS2 CGB_GCOUNT* 1))
                  (SETQ CGB_GSTAT*
                          (CONS (GB_CHKGAUSS-STAT2VL GSTAT) CGB_GSTAT*))))))))
            (SETQ H (GB_ENUMERATE H))
            (SETQ D (GB_TRAVERSO-PAIRLIST H G D))
            (SETQ G (NCONC G (LIST H)))
            (COND
             (*CGBVERBOSE (SETQ CGB_GBCOUNT* (IPLUS2 CGB_GBCOUNT* 1))))))))
        (GO WHILELABEL))
      (RETURN (GB_TRAVERSO-FINAL G)))) 
(PUT 'GB_UPDBASE 'NUMBER-OF-ARGS 2) 
(PUT 'GB_UPDBASE 'DEFINED-ON-LINE '513) 
(PUT 'GB_UPDBASE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_UPDBASE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_UPDBASE (G H)
    (PROG (HEV OC)
      (COND (*CGBSTAT (SETQ OC CGB_UPDBCOUNTP*)))
      (SETQ HEV (VDP_EVLMON H))
      (SETQ G
              (PROG (P FORALL-RESULT FORALL-ENDPTR)
                (SETQ P G)
               STARTOVER
                (COND ((NULL P) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        ((LAMBDA (P)
                           (COND
                            ((NOT (EV_DIVIDES? HEV (VDP_EVLMON P))) (LIST P))
                            (T
                             (PROGN
                              (COND (*CGBVERBOSE (IOTO_PRIN2 "#")))
                              (COND
                               (*CGBSTAT
                                (SETQ CGB_UPDBCOUNTP*
                                        (IPLUS2 CGB_UPDBCOUNTP* 1))))
                              NIL))))
                         (CAR P)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
                (SETQ P (CDR P))
                (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
               LOOPLABEL
                (COND ((NULL P) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        ((LAMBDA (P)
                           (COND
                            ((NOT (EV_DIVIDES? HEV (VDP_EVLMON P))) (LIST P))
                            (T
                             (PROGN
                              (COND (*CGBVERBOSE (IOTO_PRIN2 "#")))
                              (COND
                               (*CGBSTAT
                                (SETQ CGB_UPDBCOUNTP*
                                        (IPLUS2 CGB_UPDBCOUNTP* 1))))
                              NIL))))
                         (CAR P)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
                (SETQ P (CDR P))
                (GO LOOPLABEL)))
      (COND
       (*CGBSTAT
        (PROGN
         (COND
          ((NOT (IEQUAL OC CGB_UPDBCOUNTP*))
           (SETQ CGB_UPDBCOUNT* (IPLUS2 CGB_UPDBCOUNT* 1))))
         (SETQ CGB_UPDBCALLS* (PLUS CGB_UPDBCALLS* 1)))))
      (RETURN (NCONC G (LIST H))))) 
(PUT 'GB_CHKGAUSS 'NUMBER-OF-ARGS 1) 
(PUT 'GB_CHKGAUSS 'DEFINED-ON-LINE '536) 
(PUT 'GB_CHKGAUSS 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CHKGAUSS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_CHKGAUSS (P)
    (PROG (STAT)
      (SETQ STAT
              (PROG (X FORALL-RESULT FORALL-ENDPTR)
                (SETQ X DIP_VARS*)
                (COND ((NULL X) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS ((LAMBDA (X) 0) (CAR X)) NIL)))
               LOOPLABEL
                (SETQ X (CDR X))
                (COND ((NULL X) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR (CONS ((LAMBDA (X) 0) (CAR X)) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (PROG ()
       WHILELABEL
        (COND ((NOT P) (RETURN NIL)))
        (PROGN
         (SETQ STAT (GB_CHKGAUSS1 (DIP_EVLMON P) STAT))
         (SETQ P (DIP_MRED P)))
        (GO WHILELABEL))
      (RETURN STAT))) 
(PUT 'GB_CHKGAUSS1 'NUMBER-OF-ARGS 2) 
(PUT 'GB_CHKGAUSS1 'DEFINED-ON-LINE '547) 
(PUT 'GB_CHKGAUSS1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CHKGAUSS1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_CHKGAUSS1 (EV STAT)
    (PROG (NSTAT E S TD)
      (SETQ TD (EV_TDEG EV))
      (COND ((EQUAL TD 0) (RETURN STAT)))
      (SETQ TD (COND ((IEQUAL TD 1) 1) (T (MINUS 1))))
      (PROG ()
       WHILELABEL
        (COND ((NOT EV) (RETURN NIL)))
        (PROGN
         (SETQ E (CAR EV))
         (SETQ EV (CDR EV))
         (SETQ S (CAR STAT))
         (SETQ STAT (CDR STAT))
         (COND ((IEQUAL E 0) (SETQ NSTAT (CONS S NSTAT)))
               ((OR (IGREATERP E 1) (IEQUAL S (MINUS 1)))
                (SETQ NSTAT (CONS (MINUS 1) NSTAT)))
               ((AND (IEQUAL E 1) (IEQUAL S 0)) (SETQ NSTAT (CONS TD NSTAT)))
               ((AND (IEQUAL S 0) (IEQUAL E 0)) (SETQ NSTAT (CONS 0 NSTAT)))
               (T (REDERR "ich sehe es anders"))))
        (GO WHILELABEL))
      (RETURN (REVERSIP NSTAT)))) 
(PUT 'GB_CHKGAUSS-STAT2VL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_CHKGAUSS-STAT2VL 'DEFINED-ON-LINE '572) 
(PUT 'GB_CHKGAUSS-STAT2VL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CHKGAUSS-STAT2VL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_CHKGAUSS-STAT2VL (GSTAT)
    (PROG (SCDV R)
      (SETQ SCDV DIP_VARS*)
      (PROG ()
       WHILELABEL
        (COND ((NOT GSTAT) (RETURN NIL)))
        (PROGN
         (COND ((EQCAR GSTAT 1) (SETQ R (CONS (CAR SCDV) R))))
         (SETQ GSTAT (CDR GSTAT))
         (SETQ SCDV (CDR SCDV)))
        (GO WHILELABEL))
      (RETURN (REVERSIP R)))) 
(PUT 'GB_ENUMERATE 'NUMBER-OF-ARGS 1) 
(PUT 'GB_ENUMERATE 'DEFINED-ON-LINE '584) 
(PUT 'GB_ENUMERATE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_ENUMERATE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_ENUMERATE (F)
    (COND ((VDP_ZERO? F) F)
          (T
           (PROGN
            (VDP_CONDENSE F)
            (COND
             ((IEQUAL (VDP_NUMBER F) 0)
              (SETQ F
                      (VDP_SETNUMBER F
                       (SETQ VDP_PCOUNT* (IPLUS2 VDP_PCOUNT* 1))))))
            F)))) 
(PUT 'GB_TRAVERSO-PAIRLIST 'NUMBER-OF-ARGS 3) 
(PUT 'GB_TRAVERSO-PAIRLIST 'DEFINED-ON-LINE '596) 
(PUT 'GB_TRAVERSO-PAIRLIST 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO-PAIRLIST 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_TRAVERSO-PAIRLIST (GK G D)
    (PROG (EV R N)
      (SETQ D (GB_TRAVERSO-PAIRS-DISCARD1 GK D))
      (SETQ EV (VDP_EVLMON GK))
      (PROG (P)
        (SETQ P G)
       LAB
        (COND ((NULL P) (RETURN NIL)))
        ((LAMBDA (P)
           (COND
            ((NOT (GB_BUCHCRIT4T EV (VDP_EVLMON P)))
             (PROGN
              (COND (*CGBSTAT (SETQ CGB_B4COUNT* (IPLUS2 CGB_B4COUNT* 1))))
              (SETQ R (CONS (EV_LCM EV (VDP_EVLMON P)) R))))
            (T (SETQ N (CONS (GB_MAKEPAIR P GK) N)))))
         (CAR P))
        (SETQ P (CDR P))
        (GO LAB))
      (SETQ N (GB_TR2CRIT N R))
      (SETQ N (GB_CPLISTSORT N *CGBSLOPPY))
      (SETQ N (GB_TR3CRIT N))
      (COND
       ((AND *CGBVERBOSE N)
        (PROGN
         (SETQ CGB_PAIRCOUNT* (IPLUS2 CGB_PAIRCOUNT* (LENGTH N)))
         (IOTO_CTERPRI)
         (IOTO_PRIN2 (LIST "(" CGB_GBCOUNT* ") ")))))
      (RETURN (GB_CPLISTMERGE D (REVERSIP N))))) 
(PUT 'GB_TR2CRIT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_TR2CRIT 'DEFINED-ON-LINE '620) 
(PUT 'GB_TR2CRIT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TR2CRIT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_TR2CRIT (N R)
    (PROG (P FORALL-RESULT FORALL-ENDPTR)
      (SETQ P N)
     STARTOVER
      (COND ((NULL P) (RETURN NIL)))
      (SETQ FORALL-RESULT
              ((LAMBDA (P)
                 (COND
                  ((EV_MEMBER (CAR P) R)
                   (PROGN
                    (COND
                     (*CGBSTAT (SETQ CGB_TR2COUNT* (IPLUS2 CGB_TR2COUNT* 1))))
                    NIL))
                  (T (LIST P))))
               (CAR P)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
      (SETQ P (CDR P))
      (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
     LOOPLABEL
      (COND ((NULL P) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              ((LAMBDA (P)
                 (COND
                  ((EV_MEMBER (CAR P) R)
                   (PROGN
                    (COND
                     (*CGBSTAT (SETQ CGB_TR2COUNT* (IPLUS2 CGB_TR2COUNT* 1))))
                    NIL))
                  (T (LIST P))))
               (CAR P)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
      (SETQ P (CDR P))
      (GO LOOPLABEL))) 
(PUT 'GB_TR3CRIT 'NUMBER-OF-ARGS 1) 
(PUT 'GB_TR3CRIT 'DEFINED-ON-LINE '630) 
(PUT 'GB_TR3CRIT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TR3CRIT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_TR3CRIT (N)
    (PROG (NEWN SCANNEWN Q)
      (PROG (P)
        (SETQ P N)
       LAB
        (COND ((NULL P) (RETURN NIL)))
        ((LAMBDA (P)
           (PROGN
            (SETQ SCANNEWN NEWN)
            (SETQ Q NIL)
            (PROG ()
             WHILELABEL
              (COND ((NOT SCANNEWN) (RETURN NIL)))
              (COND
               ((EV_DIVIDES? (CAAR SCANNEWN) (CAR P))
                (PROGN
                 (SETQ Q T)
                 (SETQ SCANNEWN NIL)
                 (COND
                  (*CGBSTAT (SETQ CGB_TR3COUNT* (IPLUS2 CGB_TR3COUNT* 1))))))
               (T (SETQ SCANNEWN (CDR SCANNEWN))))
              (GO WHILELABEL))
            (COND ((NOT Q) (SETQ NEWN (GB_CPLISTSORTIN P NEWN NIL))))))
         (CAR P))
        (SETQ P (CDR P))
        (GO LAB))
      (RETURN NEWN))) 
(PUT 'GB_TRAVERSO-PAIRS-DISCARD1 'NUMBER-OF-ARGS 2) 
(PUT 'GB_TRAVERSO-PAIRS-DISCARD1 'DEFINED-ON-LINE '649) 
(PUT 'GB_TRAVERSO-PAIRS-DISCARD1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO-PAIRS-DISCARD1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_TRAVERSO-PAIRS-DISCARD1 (GK D)
    (PROG (PIJ FORALL-RESULT FORALL-ENDPTR)
      (SETQ PIJ D)
     STARTOVER
      (COND ((NULL PIJ) (RETURN NIL)))
      (SETQ FORALL-RESULT
              ((LAMBDA (PIJ)
                 (COND
                  ((GB_TRAVERSO-TRIANGLEP (CADR PIJ) (CADDR PIJ) GK (CAR PIJ))
                   (PROGN
                    (COND
                     (*CGBSTAT (SETQ CGB_TR1COUNT* (IPLUS2 CGB_TR1COUNT* 1))))
                    (COND
                     (*CGBVERBOSE
                      (SETQ CGB_PAIRCOUNT* (IDIFFERENCE CGB_PAIRCOUNT* 1))))
                    NIL))
                  (T (LIST PIJ))))
               (CAR PIJ)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
      (SETQ PIJ (CDR PIJ))
      (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
     LOOPLABEL
      (COND ((NULL PIJ) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              ((LAMBDA (PIJ)
                 (COND
                  ((GB_TRAVERSO-TRIANGLEP (CADR PIJ) (CADDR PIJ) GK (CAR PIJ))
                   (PROGN
                    (COND
                     (*CGBSTAT (SETQ CGB_TR1COUNT* (IPLUS2 CGB_TR1COUNT* 1))))
                    (COND
                     (*CGBVERBOSE
                      (SETQ CGB_PAIRCOUNT* (IDIFFERENCE CGB_PAIRCOUNT* 1))))
                    NIL))
                  (T (LIST PIJ))))
               (CAR PIJ)))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
      (SETQ PIJ (CDR PIJ))
      (GO LOOPLABEL))) 
(PUT 'GB_TRAVERSO-TRIANGLEP 'NUMBER-OF-ARGS 4) 
(PUT 'GB_TRAVERSO-TRIANGLEP 'DEFINED-ON-LINE '661) 
(PUT 'GB_TRAVERSO-TRIANGLEP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO-TRIANGLEP 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_TRAVERSO-TRIANGLEP (GI GJ GK TIJ)
    (AND (EV_SDIVP (EV_LCM (VDP_EVLMON GI) (VDP_EVLMON GK)) TIJ)
         (EV_SDIVP (EV_LCM (VDP_EVLMON GJ) (VDP_EVLMON GK)) TIJ))) 
(PUT 'GB_TRAVERSO-FINAL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_TRAVERSO-FINAL 'DEFINED-ON-LINE '664) 
(PUT 'GB_TRAVERSO-FINAL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_TRAVERSO-FINAL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_TRAVERSO-FINAL (G)
    (PROG (RG FORALL-RESULT FORALL-ENDPTR)
      (SETQ RG (VDP_LSORT G))
     STARTOVER
      (COND ((NULL RG) (RETURN NIL)))
      (SETQ FORALL-RESULT
              (COND
               ((NOT (GB_SEARCHINLIST (VDP_EVLMON (CAR RG)) (CDR RG)))
                (LIST
                 (VDP_REMPLIST
                  (GB_SIMPCONTNORMALFORM
                   (GB_NORMALFORM (CAR RG) (CDR RG))))))))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
      (SETQ RG (CDR RG))
      (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
     LOOPLABEL
      (COND ((NULL RG) (RETURN FORALL-RESULT)))
      (RPLACD FORALL-ENDPTR
              (COND
               ((NOT (GB_SEARCHINLIST (VDP_EVLMON (CAR RG)) (CDR RG)))
                (LIST
                 (VDP_REMPLIST
                  (GB_SIMPCONTNORMALFORM
                   (GB_NORMALFORM (CAR RG) (CDR RG))))))))
      (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
      (SETQ RG (CDR RG))
      (GO LOOPLABEL))) 
(DE GB_BUCHCRIT4T (E1 E2) (NOT (EV_DISJOINTP E1 E2))) 
(PUT 'GB_BUCHCRIT4T 'NUMBER-OF-ARGS 2) 
(PUT 'GB_BUCHCRIT4T 'DEFINED-ON-LINE '670) 
(PUT 'GB_BUCHCRIT4T 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_BUCHCRIT4T 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_BUCHCRIT4T 'INLINE '(LAMBDA (E1 E2) (NOT (EV_DISJOINTP E1 E2)))) 
(PUT 'GB_CPLISTSORT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_CPLISTSORT 'DEFINED-ON-LINE '675) 
(PUT 'GB_CPLISTSORT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPLISTSORT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_CPLISTSORT (G SLOPPY)
    (PROG (GG)
      (PROG (P)
        (SETQ P G)
       LAB
        (COND ((NULL P) (RETURN NIL)))
        ((LAMBDA (P) (SETQ GG (GB_CPLISTSORTIN P GG SLOPPY))) (CAR P))
        (SETQ P (CDR P))
        (GO LAB))
      (RETURN GG))) 
(PUT 'GB_CPLISTSORTIN 'NUMBER-OF-ARGS 3) 
(PUT 'GB_CPLISTSORTIN 'DEFINED-ON-LINE '682) 
(PUT 'GB_CPLISTSORTIN 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPLISTSORTIN 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_CPLISTSORTIN (P PL SLOPPY)
    (COND ((NULL PL) (LIST P)) (T (PROGN (GB_CPLISTSORTIN1 P PL SLOPPY) PL)))) 
(PUT 'GB_CPLISTSORTIN1 'NUMBER-OF-ARGS 3) 
(PUT 'GB_CPLISTSORTIN1 'DEFINED-ON-LINE '693) 
(PUT 'GB_CPLISTSORTIN1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPLISTSORTIN1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_CPLISTSORTIN1 (P PL SLOPPY)
    (COND
     ((NOT (GB_CPCOMPLESS? (CAR PL) P SLOPPY))
      (PROGN (RPLACD PL (CONS (CAR PL) (CDR PL))) (RPLACA PL P)))
     ((NULL (CDR PL)) (RPLACD PL (LIST P)))
     (T (GB_CPLISTSORTIN1 P (CDR PL) SLOPPY)))) 
(PUT 'GB_CPCOMPLESS? 'NUMBER-OF-ARGS 3) 
(PUT 'GB_CPCOMPLESS? 'DEFINED-ON-LINE '703) 
(PUT 'GB_CPCOMPLESS? 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPCOMPLESS? 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_CPCOMPLESS? (P1 P2 SLOPPY)
    (COND (SLOPPY (EV_COMPLESS? (CAR P1) (CAR P2)))
          (T
           (GB_CPCOMPLESS?S P1 P2 (IDIFFERENCE (CADDDR P1) (CADDDR P2))
            (EV_COMP (CAR P1) (CAR P2)))))) 
(PUT 'GB_CPCOMPLESS?S 'NUMBER-OF-ARGS 4) 
(PUT 'GB_CPCOMPLESS?S 'DEFINED-ON-LINE '710) 
(PUT 'GB_CPCOMPLESS?S 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPCOMPLESS?S 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_CPCOMPLESS?S (P1 P2 D Q)
    (COND ((NEQ D 0) (ILESSP D 0)) ((NEQ Q 0) (LESSP Q 0))
          (T (ILESSP (VDP_NUMBER (CADDR P1)) (VDP_NUMBER (CADDR P2)))))) 
(PUT 'GB_CPLISTMERGE 'NUMBER-OF-ARGS 2) 
(PUT 'GB_CPLISTMERGE 'DEFINED-ON-LINE '718) 
(PUT 'GB_CPLISTMERGE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CPLISTMERGE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_CPLISTMERGE (PL1 PL2)
    (PROG (CPL1 CPL2)
      (COND ((NULL PL1) (RETURN PL2)))
      (COND ((NULL PL2) (RETURN PL1)))
      (SETQ CPL1 (CAR PL1))
      (SETQ CPL2 (CAR PL2))
      (RETURN
       (COND
        ((GB_CPCOMPLESS? CPL1 CPL2 NIL)
         (CONS CPL1 (GB_CPLISTMERGE (CDR PL1) PL2)))
        (T (CONS CPL2 (GB_CPLISTMERGE PL1 (CDR PL2)))))))) 
(PUT 'GB_MAKEPAIR 'NUMBER-OF-ARGS 2) 
(PUT 'GB_MAKEPAIR 'DEFINED-ON-LINE '735) 
(PUT 'GB_MAKEPAIR 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_MAKEPAIR 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_MAKEPAIR (F H)
    (PROG (TTT SF SH)
      (SETQ TTT (EV_LCM (VDP_EVLMON F) (VDP_EVLMON H)))
      (SETQ SF (IPLUS2 (VDP_SUGAR F) (EV_TDEG (EV_DIF TTT (VDP_EVLMON F)))))
      (SETQ SH (IPLUS2 (VDP_SUGAR H) (EV_TDEG (EV_DIF TTT (VDP_EVLMON H)))))
      (RETURN (LIST TTT F H (|EV_MAX#| SF SH))))) 
(PUT 'GB_SPOLYNOMIAL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_SPOLYNOMIAL 'DEFINED-ON-LINE '744) 
(PUT 'GB_SPOLYNOMIAL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SPOLYNOMIAL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_SPOLYNOMIAL (PR)
    (PROG (P1 P2 S)
      (SETQ P1 (CADR PR))
      (SETQ P2 (CADDR PR))
      (SETQ S (GB_SPOLYNOMIAL1 P1 P2))
      (COND ((OR (VDP_ZERO? S) (VDP_UNIT? S)) (RETURN S)))
      (RETURN (GB_STRANGE-REDUCTION S P1 P2)))) 
(PUT 'GB_SPOLYNOMIAL1 'NUMBER-OF-ARGS 2) 
(PUT 'GB_SPOLYNOMIAL1 'DEFINED-ON-LINE '756) 
(PUT 'GB_SPOLYNOMIAL1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SPOLYNOMIAL1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_SPOLYNOMIAL1 (P1 P2)
    (PROG (EP1 EP2 EP RP1 RP2 DB1 DB2 X)
      (SETQ EP1 (VDP_EVLMON P1))
      (SETQ EP2 (VDP_EVLMON P2))
      (SETQ EP (EV_LCM EP1 EP2))
      (SETQ RP1 (VDP_MRED P1))
      (SETQ RP2 (VDP_MRED P2))
      (COND ((AND (VDP_ZERO? RP1) (VDP_ZERO? RP2)) (RETURN RP1)))
      (COND
       ((VDP_ZERO? RP1)
        (RETURN (VDP_PROD RP2 (VDP_FMON (BC_A2BC 1) (EV_DIF EP EP2))))))
      (COND
       ((VDP_ZERO? RP2)
        (RETURN (VDP_PROD RP1 (VDP_FMON (BC_A2BC 1) (EV_DIF EP EP1))))))
      (SETQ DB1 (VDP_LBC P1))
      (SETQ DB2 (VDP_LBC P2))
      (SETQ X (BC_GCD DB1 DB2))
      (COND
       ((NOT (BC_ONE? X))
        (PROGN (SETQ DB1 (BC_QUOT DB1 X)) (SETQ DB2 (BC_QUOT DB2 X)))))
      (RETURN
       (VDP_ILCOMB RP2 DB1 (EV_DIF EP EP2) RP1 (BC_NEG DB2) (EV_DIF EP EP1))))) 
(PUT 'GB_STRANGE-REDUCTION 'NUMBER-OF-ARGS 3) 
(PUT 'GB_STRANGE-REDUCTION 'DEFINED-ON-LINE '779) 
(PUT 'GB_STRANGE-REDUCTION 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_STRANGE-REDUCTION 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_STRANGE-REDUCTION (S P1 P2)
    (PROG (TP1 TP2 TS C SAVES)
      (SETQ SAVES S)
      (SETQ TP1 (VDP_EVLMON P1))
      (SETQ TP2 (VDP_EVLMON P2))
      (SETQ C T)
      (PROG ()
       WHILELABEL
        (COND ((NOT (AND C (NOT (VDP_ZERO? S)))) (RETURN NIL)))
        (PROGN
         (SETQ TS (VDP_EVLMON S))
         (COND
          ((GB_BUCH-EV_DIVIDES? TP2 TS)
           (SETQ S (GB_REDUCEONESTEPINT S (VDP_ZERO) (VDP_LBC S) TS P2)))
          ((GB_BUCH-EV_DIVIDES? TP1 TS)
           (SETQ S (GB_REDUCEONESTEPINT S (VDP_ZERO) (VDP_LBC S) TS P1)))
          (T (SETQ C NIL))))
        (GO WHILELABEL))
      (COND
       ((AND *CGBSTAT (NOT (EQ S SAVES)))
        (SETQ CGB_STRANGECOUNT* (IPLUS2 CGB_STRANGECOUNT* 1))))
      (RETURN S))) 
(DE GB_BUCH-EV_DIVIDES? (VEV1 VEV2) (EV_MTEST? VEV2 VEV1)) 
(PUT 'GB_BUCH-EV_DIVIDES? 'NUMBER-OF-ARGS 2) 
(PUT 'GB_BUCH-EV_DIVIDES? 'DEFINED-ON-LINE '800) 
(PUT 'GB_BUCH-EV_DIVIDES? 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_BUCH-EV_DIVIDES? 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'GB_BUCH-EV_DIVIDES? 'INLINE '(LAMBDA (VEV1 VEV2) (EV_MTEST? VEV2 VEV1))) 
(PUT 'GB_NORMALFORM 'NUMBER-OF-ARGS 2) 
(PUT 'GB_NORMALFORM 'DEFINED-ON-LINE '804) 
(PUT 'GB_NORMALFORM 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_NORMALFORM 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_NORMALFORM (F G)
    (PROG (F1 C VEV DIVISOR TAI FOLD N)
      (SETQ N 0)
      (SETQ FOLD F)
      (SETQ F1 (VDP_SETSUGAR (VDP_ZERO) (VDP_SUGAR F)))
      (PROG ()
       WHILELABEL
        (COND ((NOT (NOT (VDP_ZERO? F))) (RETURN NIL)))
        (PROGN
         (SETQ VEV (VDP_EVLMON F))
         (SETQ C (VDP_LBC F))
         (SETQ DIVISOR (GB_SEARCHINLIST VEV G))
         (COND
          (DIVISOR
           (PROGN
            (SETQ TAI T)
            (COND
             ((VDP_MONP DIVISOR)
              (SETQ F (VDP_CANCELMEV F (VDP_EVLMON DIVISOR))))
             (T
              (PROGN
               (SETQ F (GB_REDUCEONESTEPINT F F1 C VEV DIVISOR))
               (SETQ F1 SECONDVALUE*)
               (COND
                (*CGBCONTRED
                 (PROGN
                  (SETQ F (GB_ADTSSIMPCONT F F1 N))
                  (SETQ F1 SECONDVALUE*)
                  (SETQ N THIRDVALUE*)))))))))
          (*CGBFULLRED (PROGN (SETQ F (GB_SHIFT F F1)) (SETQ F1 SECONDVALUE*)))
          (T (PROGN (SETQ F1 (VDP_SUM F1 F)) (SETQ F (VDP_ZERO))))))
        (GO WHILELABEL))
      (RETURN (COND (TAI F1) (T FOLD))))) 
(PUT 'GB_SEARCHINLIST 'NUMBER-OF-ARGS 2) 
(PUT 'GB_SEARCHINLIST 'DEFINED-ON-LINE '840) 
(PUT 'GB_SEARCHINLIST 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SEARCHINLIST 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_SEARCHINLIST (VEV G)
    (COND ((NULL G) NIL) ((EV_MTEST? VEV (VDP_EVLMON (CAR G))) (CAR G))
          (T (GB_SEARCHINLIST VEV (CDR G))))) 
(PUT 'GB_ADTSSIMPCONT 'NUMBER-OF-ARGS 3) 
(PUT 'GB_ADTSSIMPCONT 'DEFINED-ON-LINE '850) 
(PUT 'GB_ADTSSIMPCONT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_ADTSSIMPCONT 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_ADTSSIMPCONT (F F1 N)
    (PROG (F0)
      (COND
       ((VDP_ZERO? F)
        (PROGN (SETQ SECONDVALUE* F1) (SETQ THIRDVALUE* 0) (RETURN F))))
      (SETQ N (PLUS N 1))
      (COND
       ((IGREATERP N CGB_CONTCOUNT*)
        (PROGN
         (SETQ F0 F)
         (SETQ F (GB_SIMPCONT2 F F1))
         (SETQ F1 SECONDVALUE*)
         (GB_CONTENTCONTROL (NEQ F F0))
         (SETQ N 0))))
      (SETQ SECONDVALUE* F1)
      (SETQ THIRDVALUE* N)
      (RETURN F))) 
(PUT 'GB_SIMPCONT2 'NUMBER-OF-ARGS 2) 
(PUT 'GB_SIMPCONT2 'DEFINED-ON-LINE '870) 
(PUT 'GB_SIMPCONT2 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SIMPCONT2 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_SIMPCONT2 (F F1)
    (PROG (C S1 S2)
      (SETQ C (VDP_CONTENT F))
      (COND ((BC_ONE? (BC_ABS C)) (PROGN (SETQ SECONDVALUE* F1) (RETURN F))))
      (SETQ S1 (VDP_SUGAR F))
      (SETQ S2 (VDP_SUGAR F1))
      (COND
       ((NOT (VDP_ZERO? F1))
        (PROGN
         (SETQ C (VDP_CONTENT1 F1 C))
         (COND
          ((BC_ONE? (BC_ABS C)) (PROGN (SETQ SECONDVALUE* F1) (RETURN F))))
         (SETQ F1 (VDP_BCQUOT F1 C)))))
      (SETQ F (VDP_BCQUOT F C))
      (VDP_SETSUGAR F S1)
      (VDP_SETSUGAR F1 S2)
      (SETQ SECONDVALUE* F1)
      (RETURN F))) 
(PUT 'GB_CONTENTCONTROL 'NUMBER-OF-ARGS 1) 
(PUT 'GB_CONTENTCONTROL 'DEFINED-ON-LINE '896) 
(PUT 'GB_CONTENTCONTROL 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_CONTENTCONTROL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_CONTENTCONTROL (U)
    (PROGN
     (SETQ CGB_CONTCOUNT*
             (COND (U (|EV_MAX#| 0 (IDIFFERENCE CGB_CONTCOUNT* 1)))
                   (T (|GB_MIN#| CGB_MINCONTRED* (IPLUS2 CGB_CONTCOUNT* 1)))))
     (COND (*CGBVERBOSE (IOTO_PRIN2 (LIST "<" CGB_CONTCOUNT* "> ")))))) 
(DE |GB_MIN#| (A B) (COND ((ILESSP A B) A) (T B))) 
(PUT '|GB_MIN#| 'NUMBER-OF-ARGS 2) 
(PUT '|GB_MIN#| 'DEFINED-ON-LINE '908) 
(PUT '|GB_MIN#| 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT '|GB_MIN#| 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC '|GB_MIN#| 'INLINE '(LAMBDA (A B) (COND ((ILESSP A B) A) (T B)))) 
(PUT 'GB_SHIFT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_SHIFT 'DEFINED-ON-LINE '911) 
(PUT 'GB_SHIFT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SHIFT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_SHIFT (F F1)
    (PROG (S S1)
      (SETQ S (VDP_SUGAR F))
      (SETQ S1 (VDP_SUGAR F1))
      (SETQ F1 (VDP_NCONCMON F1 (VDP_LBC F) (VDP_EVLMON F)))
      (SETQ F (VDP_MRED F))
      (VDP_SETSUGAR F S)
      (VDP_SETSUGAR F1 (|EV_MAX#| S1 S))
      (SETQ SECONDVALUE* F1)
      (RETURN F))) 
(PUT 'GB_REDUCEONESTEPINT 'NUMBER-OF-ARGS 5) 
(PUT 'GB_REDUCEONESTEPINT 'DEFINED-ON-LINE '923) 
(PUT 'GB_REDUCEONESTEPINT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_REDUCEONESTEPINT 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_REDUCEONESTEPINT (F F1 C VEV G1)
    (PROG (VEVCOF A B CG X RG1)
      (SETQ RG1 (VDP_MRED G1))
      (COND
       ((VDP_ZERO? RG1)
        (PROGN (SETQ F (VDP_MRED F)) (SETQ SECONDVALUE* F1) (RETURN F))))
      (SETQ VEVCOF (EV_DIF VEV (VDP_EVLMON G1)))
      (SETQ CG (VDP_LBC G1))
      (SETQ X (BC_GCD C CG))
      (SETQ A (BC_QUOT CG X))
      (SETQ B (BC_QUOT C X))
      (COND ((NOT (VDP_ZERO? F1)) (SETQ F1 (VDP_BCPROD F1 A))))
      (SETQ F (VDP_ILCOMBR (VDP_MRED F) A RG1 (BC_NEG B) VEVCOF))
      (SETQ SECONDVALUE* F1)
      (RETURN F))) 
(PUT 'GB_SIMPCONTNORMALFORM 'NUMBER-OF-ARGS 1) 
(PUT 'GB_SIMPCONTNORMALFORM 'DEFINED-ON-LINE '947) 
(PUT 'GB_SIMPCONTNORMALFORM 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_SIMPCONTNORMALFORM 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_SIMPCONTNORMALFORM (H)
    (COND ((VDP_ZERO? H) H) (T (VDP_SETSUGAR (VDP_SIMPCONT H) (VDP_SUGAR H))))) 
(PUT 'GB_VDPVORDOPT 'NUMBER-OF-ARGS 2) 
(PUT 'GB_VDPVORDOPT 'DEFINED-ON-LINE '954) 
(PUT 'GB_VDPVORDOPT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VDPVORDOPT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_VDPVORDOPT (W VARS)
    (PROG (C)
      (SETQ VARS (SORT VARS 'ORDOP))
      (SETQ C
              (PROG (X FORALL-RESULT FORALL-ENDPTR)
                (SETQ X VARS)
                (COND ((NULL X) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS
                                 ((LAMBDA (X) (CONS X (CONS 0 0))) (CAR X))
                                 NIL)))
               LOOPLABEL
                (SETQ X (CDR X))
                (COND ((NULL X) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS ((LAMBDA (X) (CONS X (CONS 0 0))) (CAR X)) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (PROG (POLY)
        (SETQ POLY W)
       LAB
        (COND ((NULL POLY) (RETURN NIL)))
        ((LAMBDA (POLY) (GB_VDPVORDOPT1 POLY VARS C)) (CAR POLY))
        (SETQ POLY (CDR POLY))
        (GO LAB))
      (SETQ C (SORT C (FUNCTION GB_VDPVORDOPT2)))
      (SETQ INTVDPVARS*
              (PROG (V FORALL-RESULT FORALL-ENDPTR)
                (SETQ V C)
                (COND ((NULL V) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS ((LAMBDA (V) (CAR V)) (CAR V)) NIL)))
               LOOPLABEL
                (SETQ V (CDR V))
                (COND ((NULL V) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS ((LAMBDA (V) (CAR V)) (CAR V)) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (SETQ VARS (GB_VDPVORDOPT31 INTVDPVARS*))
      (RETURN VARS))) 
(PUT 'GB_VDPVORDOPT31 'NUMBER-OF-ARGS 1) 
(PUT 'GB_VDPVORDOPT31 'DEFINED-ON-LINE '969) 
(PUT 'GB_VDPVORDOPT31 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VDPVORDOPT31 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GB_VDPVORDOPT31 (U)
    (PROG (V Y)
      (COND ((NULL U) (RETURN NIL)))
      (SETQ V
              (PROG (X FORALL-RESULT FORALL-ENDPTR)
                (SETQ X U)
               STARTOVER
                (COND ((NULL X) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        ((LAMBDA (X)
                           (PROGN
                            (SETQ Y (ASSOC X DEPL*))
                            (COND
                             ((OR (NULL Y) (NULL (XNP (CDR Y) U))) (LIST X)))))
                         (CAR X)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
                (SETQ X (CDR X))
                (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
               LOOPLABEL
                (COND ((NULL X) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        ((LAMBDA (X)
                           (PROGN
                            (SETQ Y (ASSOC X DEPL*))
                            (COND
                             ((OR (NULL Y) (NULL (XNP (CDR Y) U))) (LIST X)))))
                         (CAR X)))
                (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
                (SETQ X (CDR X))
                (GO LOOPLABEL)))
      (RETURN (NCONC (GB_VDPVORDOPT31 (SETDIFF U V)) V)))) 
(PUT 'GB_VDPVORDOPT1 'NUMBER-OF-ARGS 3) 
(PUT 'GB_VDPVORDOPT1 'DEFINED-ON-LINE '981) 
(PUT 'GB_VDPVORDOPT1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VDPVORDOPT1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_VDPVORDOPT1 (P VL C)
    (COND ((NULL P) 0) ((OR (OR (ATOM P) (ATOM (CAR P))) (NULL VL)) 1)
          ((NEQ (CAAAR P) (CAR VL)) (GB_VDPVORDOPT1 P (CDR VL) C))
          (T
           (PROG (VAR POW SLOT N)
             (SETQ N 0)
             (SETQ N (GB_VDPVORDOPT1 (CDAR P) (CDR VL) C))
             (SETQ VAR (CAAAR P))
             (SETQ POW (CDAAR P))
             (SETQ SLOT (ASSOC VAR C))
             (COND
              ((IGREATERP POW (CADR SLOT))
               (PROGN (RPLACA (CDR SLOT) POW) (RPLACD (CDR SLOT) N)))
              (T (RPLACD (CDR SLOT) (IPLUS2 N (CDDR SLOT)))))
             (RETURN (IPLUS2 N (GB_VDPVORDOPT1 (CDR P) VL C))))))) 
(PUT 'GB_VDPVORDOPT2 'NUMBER-OF-ARGS 2) 
(PUT 'GB_VDPVORDOPT2 'DEFINED-ON-LINE '1001) 
(PUT 'GB_VDPVORDOPT2 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_VDPVORDOPT2 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_VDPVORDOPT2 (SL1 SL2)
    (PROGN
     (SETQ SL1 (CDR SL1))
     (SETQ SL2 (CDR SL2))
     (OR (ILESSP (CAR SL1) (CAR SL2))
         (AND (EQUAL (CAR SL1) (CAR SL2)) (ILESSP (CDR SL1) (CDR SL2)))))) 
(ENDMODULE) 
(MODULE (LIST 'VDP)) 
(DE VDP_LBC (U) (CADDR U)) 
(PUT 'VDP_LBC 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_LBC 'DEFINED-ON-LINE '1024) 
(PUT 'VDP_LBC 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_LBC 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_LBC 'INLINE '(LAMBDA (U) (CADDR U))) 
(DE VDP_EVLMON (U) (CADR U)) 
(PUT 'VDP_EVLMON 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_EVLMON 'DEFINED-ON-LINE '1027) 
(PUT 'VDP_EVLMON 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_EVLMON 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_EVLMON 'INLINE '(LAMBDA (U) (CADR U))) 
(DE VDP_POLY (U) (CAR (CDDDR U))) 
(PUT 'VDP_POLY 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_POLY 'DEFINED-ON-LINE '1030) 
(PUT 'VDP_POLY 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_POLY 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_POLY 'INLINE '(LAMBDA (U) (CAR (CDDDR U)))) 
(DE VDP_ZERO? (U) (NULL (CAR (CDDDR U)))) 
(PUT 'VDP_ZERO? 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_ZERO? 'DEFINED-ON-LINE '1033) 
(PUT 'VDP_ZERO? 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_ZERO? 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_ZERO? 'INLINE '(LAMBDA (U) (NULL (CAR (CDDDR U))))) 
(DE VDP_PLIST (U) (CADR (CDDDR U))) 
(PUT 'VDP_PLIST 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_PLIST 'DEFINED-ON-LINE '1036) 
(PUT 'VDP_PLIST 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_PLIST 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_PLIST 'INLINE '(LAMBDA (U) (CADR (CDDDR U)))) 
(PUT 'VDP_REMPLIST 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_REMPLIST 'DEFINED-ON-LINE '1039) 
(PUT 'VDP_REMPLIST 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_REMPLIST 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_REMPLIST (U) (PROGN (SETCAR (PNTH U 5) NIL) U)) 
(DE VDP_NUMBER (F) (OR (VDP_GETPROP F 'NUMBER) 0)) 
(PUT 'VDP_NUMBER 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_NUMBER 'DEFINED-ON-LINE '1047) 
(PUT 'VDP_NUMBER 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_NUMBER 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_NUMBER 'INLINE '(LAMBDA (F) (OR (VDP_GETPROP F 'NUMBER) 0))) 
(PUT 'VDP_SUGAR 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_SUGAR 'DEFINED-ON-LINE '1050) 
(PUT 'VDP_SUGAR 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_SUGAR 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_SUGAR (F)
    (COND ((OR (NULL (CAR (CDDDR F))) (NOT *CGBSUGAR)) 0)
          (T (OR (VDP_GETPROP F 'SUGAR) 0)))) 
(DE VDP_UNIT? (P) (AND (NOT (NULL (CAR (CDDDR P)))) (EV_ZERO? (CADR P)))) 
(PUT 'VDP_UNIT? 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_UNIT? 'DEFINED-ON-LINE '1053) 
(PUT 'VDP_UNIT? 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_UNIT? 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_UNIT? 'INLINE
      '(LAMBDA (P) (AND (NOT (NULL (CAR (CDDDR P)))) (EV_ZERO? (CADR P))))) 
(DE VDP_MAKE (VBC VEV FORM) (LIST 'VDP VEV VBC FORM NIL)) 
(PUT 'VDP_MAKE 'NUMBER-OF-ARGS 3) 
(PUT 'VDP_MAKE 'DEFINED-ON-LINE '1056) 
(PUT 'VDP_MAKE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_MAKE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'VDP_MAKE 'INLINE '(LAMBDA (VBC VEV FORM) (LIST 'VDP VEV VBC FORM NIL))) 
(DE VDP_MONP (U) (DIP_MONP (CAR (CDDDR U)))) 
(PUT 'VDP_MONP 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_MONP 'DEFINED-ON-LINE '1059) 
(PUT 'VDP_MONP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_MONP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_MONP 'INLINE '(LAMBDA (U) (DIP_MONP (CAR (CDDDR U))))) 
(DE VDP_TDEG (U) (DIP_TDEG (CAR (CDDDR U)))) 
(PUT 'VDP_TDEG 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_TDEG 'DEFINED-ON-LINE '1062) 
(PUT 'VDP_TDEG 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_TDEG 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_TDEG 'INLINE '(LAMBDA (U) (DIP_TDEG (CAR (CDDDR U))))) 
(PUT 'VDP_FDIP 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_FDIP 'DEFINED-ON-LINE '1065) 
(PUT 'VDP_FDIP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_FDIP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_FDIP (U)
    (COND ((NULL U) (VDP_ZERO))
          (T (LIST 'VDP (DIP_EVLMON U) (DIP_LBC U) U NIL)))) 
(PUT 'VDP_APPENDMON 'NUMBER-OF-ARGS 3) 
(PUT 'VDP_APPENDMON 'DEFINED-ON-LINE '1071) 
(PUT 'VDP_APPENDMON 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_APPENDMON 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE VDP_APPENDMON (VDP COEF VEV)
    (COND ((NULL (CAR (CDDDR VDP))) (VDP_FMON COEF VEV)) ((BC_ZERO? COEF) VDP)
          (T
           (LIST 'VDP (CADR VDP) (CADDR VDP)
                 (DIP_APPENDMON (CAR (CDDDR VDP)) COEF VEV) NIL)))) 
(PUT 'VDP_NCONCMON 'NUMBER-OF-ARGS 3) 
(PUT 'VDP_NCONCMON 'DEFINED-ON-LINE '1080) 
(PUT 'VDP_NCONCMON 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_NCONCMON 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE VDP_NCONCMON (VDP COEF VEV)
    (COND ((NULL (CAR (CDDDR VDP))) (VDP_FMON COEF VEV)) ((BC_ZERO? COEF) VDP)
          (T
           (LIST 'VDP (CADR VDP) (CADDR VDP)
                 (DIP_NCONCMON (CAR (CDDDR VDP)) COEF VEV) NIL)))) 
(PUT 'VDP_BCQUOT 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_BCQUOT 'DEFINED-ON-LINE '1089) 
(PUT 'VDP_BCQUOT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_BCQUOT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_BCQUOT (P C)
    (PROG (R)
      (SETQ R (VDP_FDIP (DIP_BCQUOT (CAR (CDDDR P)) C)))
      (VDP_SETSUGAR R (VDP_SUGAR P))
      (RETURN R))) 
(DE VDP_CONTENT (P) (DIP_CONTENTI (CAR (CDDDR P)))) 
(PUT 'VDP_CONTENT 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_CONTENT 'DEFINED-ON-LINE '1096) 
(PUT 'VDP_CONTENT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_CONTENT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_CONTENT 'INLINE '(LAMBDA (P) (DIP_CONTENTI (CAR (CDDDR P))))) 
(DE VDP_CONTENT1 (D C) (DIP_CONTENTI1 (CAR (CDDDR D)) C)) 
(PUT 'VDP_CONTENT1 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_CONTENT1 'DEFINED-ON-LINE '1099) 
(PUT 'VDP_CONTENT1 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_CONTENT1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'VDP_CONTENT1 'INLINE '(LAMBDA (D C) (DIP_CONTENTI1 (CAR (CDDDR D)) C))) 
(DE VDP_LENGTH (F) (DIP_LENGTH (CAR (CDDDR F)))) 
(PUT 'VDP_LENGTH 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_LENGTH 'DEFINED-ON-LINE '1102) 
(PUT 'VDP_LENGTH 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_LENGTH 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_LENGTH 'INLINE '(LAMBDA (F) (DIP_LENGTH (CAR (CDDDR F))))) 
(PUT 'VDP_BCPROD 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_BCPROD 'DEFINED-ON-LINE '1105) 
(PUT 'VDP_BCPROD 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_BCPROD 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_BCPROD (P B)
    (PROG (R)
      (SETQ R (VDP_FDIP (DIP_BCPROD (CAR (CDDDR P)) B)))
      (VDP_SETSUGAR R (VDP_SUGAR P))
      (RETURN R))) 
(PUT 'VDP_CANCELMEV 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_CANCELMEV 'DEFINED-ON-LINE '1112) 
(PUT 'VDP_CANCELMEV 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_CANCELMEV 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_CANCELMEV (P VEV)
    (PROG (R)
      (SETQ R (VDP_FDIP (DIP_CANCELMEV (CAR (CDDDR P)) VEV)))
      (VDP_SETSUGAR R (VDP_SUGAR P))
      (RETURN R))) 
(PUT 'VDP_SUM 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_SUM 'DEFINED-ON-LINE '1119) 
(PUT 'VDP_SUM 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_SUM 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_SUM (D1 D2)
    (PROG (R)
      (SETQ R (VDP_FDIP (DIP_SUM (CAR (CDDDR D1)) (CAR (CDDDR D2)))))
      (VDP_SETSUGAR R (|EV_MAX#| (VDP_SUGAR D1) (VDP_SUGAR D2)))
      (RETURN R))) 
(PUT 'VDP_PROD 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_PROD 'DEFINED-ON-LINE '1126) 
(PUT 'VDP_PROD 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_PROD 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_PROD (D1 D2)
    (PROG (R)
      (SETQ R (VDP_FDIP (DIP_PROD (CAR (CDDDR D1)) (CAR (CDDDR D2)))))
      (VDP_SETSUGAR R (IPLUS2 (VDP_SUGAR D1) (VDP_SUGAR D2)))
      (RETURN R))) 
(DE VDP_ZERO NIL (LIST 'VDP 'INVALID 'INVALID NIL NIL)) 
(PUT 'VDP_ZERO 'NUMBER-OF-ARGS 0) 
(PUT 'VDP_ZERO 'DEFINED-ON-LINE '1133) 
(PUT 'VDP_ZERO 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_ZERO 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(PUTC 'VDP_ZERO 'INLINE '(LAMBDA () (LIST 'VDP 'INVALID 'INVALID NIL NIL))) 
(PUT 'VDP_MRED 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_MRED 'DEFINED-ON-LINE '1136) 
(PUT 'VDP_MRED 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_MRED 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_MRED (U)
    (PROG (R)
      (SETQ R (DIP_MRED (CAR (CDDDR U))))
      (COND ((NULL R) (RETURN (LIST 'VDP 'INVALID 'INVALID NIL NIL))))
      (SETQ R (LIST 'VDP (DIP_EVLMON R) (DIP_LBC R) R NIL))
      (VDP_SETSUGAR R (VDP_SUGAR U))
      (RETURN R))) 
(DE VDP_CONDENSE (F) (DIP_CONDENSE (CAR (CDDDR F)))) 
(PUT 'VDP_CONDENSE 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_CONDENSE 'DEFINED-ON-LINE '1146) 
(PUT 'VDP_CONDENSE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_CONDENSE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_CONDENSE 'INLINE '(LAMBDA (F) (DIP_CONDENSE (CAR (CDDDR F))))) 
(PUT 'VDP_SETSUGAR 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_SETSUGAR 'DEFINED-ON-LINE '1149) 
(PUT 'VDP_SETSUGAR 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_SETSUGAR 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_SETSUGAR (P S) (COND ((NOT *CGBSUGAR) P) (T (VDP_PUTPROP P 'SUGAR S)))) 
(DE VDP_SETNUMBER (P N) (VDP_PUTPROP P 'NUMBER N)) 
(PUT 'VDP_SETNUMBER 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_SETNUMBER 'DEFINED-ON-LINE '1155) 
(PUT 'VDP_SETNUMBER 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_SETNUMBER 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'VDP_SETNUMBER 'INLINE '(LAMBDA (P N) (VDP_PUTPROP P 'NUMBER N))) 
(PUT 'VDP_PUTPROP 'NUMBER-OF-ARGS 3) 
(PUT 'VDP_PUTPROP 'DEFINED-ON-LINE '1158) 
(PUT 'VDP_PUTPROP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_PUTPROP 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE VDP_PUTPROP (POLY PROP VAL)
    (PROG (C P)
      (SETQ C (CDR (CDDDR POLY)))
      (SETQ P (ATSOC PROP (CAR C)))
      (COND (P (RPLACD P VAL)) (T (RPLACA C (CONS (CONS PROP VAL) (CAR C)))))
      (RETURN POLY))) 
(PUT 'VDP_GETPROP 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_GETPROP 'DEFINED-ON-LINE '1169) 
(PUT 'VDP_GETPROP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_GETPROP 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_GETPROP (POLY PROP)
    ((LAMBDA (P) (COND (P (CDR P)) (T NIL))) (ATSOC PROP (CADR (CDDDR POLY))))) 
(PUT 'VDP_FMON 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_FMON 'DEFINED-ON-LINE '1172) 
(PUT 'VDP_FMON 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_FMON 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE VDP_FMON (COEF VEV)
    (PROG (R)
      (SETQ R (LIST 'VDP VEV COEF (DIP_FMON COEF VEV) NIL))
      (VDP_SETSUGAR R (EV_TDEG VEV))
      (RETURN R))) 
(DE VDP_2A (U) (DIP_2A (CAR (CDDDR U)))) 
(PUT 'VDP_2A 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_2A 'DEFINED-ON-LINE '1182) 
(PUT 'VDP_2A 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_2A 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_2A 'INLINE '(LAMBDA (U) (DIP_2A (CAR (CDDDR U))))) 
(DE VDP_2F (U) (DIP_2F (CAR (CDDDR U)))) 
(PUT 'VDP_2F 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_2F 'DEFINED-ON-LINE '1185) 
(PUT 'VDP_2F 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_2F 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_2F 'INLINE '(LAMBDA (U) (DIP_2F (CAR (CDDDR U))))) 
(DE VDP_2SQ (U) (DIP_2SQ (CAR (CDDDR U)))) 
(PUT 'VDP_2SQ 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_2SQ 'DEFINED-ON-LINE '1188) 
(PUT 'VDP_2SQ 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_2SQ 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'VDP_2SQ 'INLINE '(LAMBDA (U) (DIP_2SQ (CAR (CDDDR U))))) 
(DE VDP_INIT (VARS SM SX) (DIP_INIT VARS SM SX)) 
(PUT 'VDP_INIT 'NUMBER-OF-ARGS 3) 
(PUT 'VDP_INIT 'DEFINED-ON-LINE '1191) 
(PUT 'VDP_INIT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_INIT 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(PUTC 'VDP_INIT 'INLINE '(LAMBDA (VARS SM SX) (DIP_INIT VARS SM SX))) 
(PUT 'VDP_CLEANUP 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_CLEANUP 'DEFINED-ON-LINE '1195) 
(PUT 'VDP_CLEANUP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_CLEANUP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_CLEANUP (L) (DIP_CLEANUP L)) 
(PUT 'VDP_F2VDP 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_F2VDP 'DEFINED-ON-LINE '1198) 
(PUT 'VDP_F2VDP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_F2VDP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_F2VDP (U)
    (PROG (DIP)
      (SETQ DIP (DIP_F2DIP U))
      (COND ((NULL DIP) (RETURN (LIST 'VDP 'INVALID 'INVALID NIL NIL))))
      (RETURN (LIST 'VDP (DIP_EVLMON DIP) (DIP_LBC DIP) DIP NIL)))) 
(PUT 'VDP_ENUMERATE 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_ENUMERATE 'DEFINED-ON-LINE '1206) 
(PUT 'VDP_ENUMERATE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_ENUMERATE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_ENUMERATE (F)
    (COND ((OR (NULL (CAR (CDDDR F))) (VDP_GETPROP F 'NUMBER)) F)
          (T
           (VDP_PUTPROP F 'NUMBER (SETQ VDP_PCOUNT* (IPLUS2 VDP_PCOUNT* 1)))))) 
(PUT 'VDP_SIMPCONT 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_SIMPCONT 'DEFINED-ON-LINE '1214) 
(PUT 'VDP_SIMPCONT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_SIMPCONT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_SIMPCONT (P)
    (PROG (Q)
      (SETQ Q (CAR (CDDDR P)))
      (COND ((NULL Q) (RETURN P)))
      (RETURN (VDP_FDIP (DIP_SIMPCONT Q))))) 
(PUT 'VDP_LSORT 'NUMBER-OF-ARGS 1) 
(PUT 'VDP_LSORT 'DEFINED-ON-LINE '1222) 
(PUT 'VDP_LSORT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_LSORT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE VDP_LSORT (PL) (SORT PL (FUNCTION VDP_EVLCOMP))) 
(DE VDP_EVLCOMP (P1 P2) (DIP_EVLCOMP (CAR (CDDDR P1)) (CAR (CDDDR P2)))) 
(PUT 'VDP_EVLCOMP 'NUMBER-OF-ARGS 2) 
(PUT 'VDP_EVLCOMP 'DEFINED-ON-LINE '1228) 
(PUT 'VDP_EVLCOMP 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_EVLCOMP 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(PUTC 'VDP_EVLCOMP 'INLINE
      '(LAMBDA (P1 P2) (DIP_EVLCOMP (CAR (CDDDR P1)) (CAR (CDDDR P2))))) 
(PUT 'VDP_ILCOMB 'NUMBER-OF-ARGS 6) 
(PUT 'VDP_ILCOMB 'DEFINED-ON-LINE '1231) 
(PUT 'VDP_ILCOMB 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_ILCOMB 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE VDP_ILCOMB (V1 C1 T1 V2 C2 T2)
    (PROG (R)
      (SETQ R
              (VDP_FDIP
               (DIP_ILCOMB (CAR (CDDDR V1)) C1 T1 (CAR (CDDDR V2)) C2 T2)))
      (VDP_SETSUGAR R
       (|EV_MAX#| (IPLUS2 (VDP_SUGAR V1) (EV_TDEG T1))
        (IPLUS2 (VDP_SUGAR V2) (EV_TDEG T2))))
      (RETURN R))) 
(PUT 'VDP_ILCOMBR 'NUMBER-OF-ARGS 5) 
(PUT 'VDP_ILCOMBR 'DEFINED-ON-LINE '1239) 
(PUT 'VDP_ILCOMBR 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'VDP_ILCOMBR 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE VDP_ILCOMBR (V1 C1 V2 C2 T2)
    (PROG (R)
      (SETQ R
              (VDP_FDIP
               (DIP_ILCOMBR (CAR (CDDDR V1)) C1 (CAR (CDDDR V2)) C2 T2)))
      (VDP_SETSUGAR R
       (|EV_MAX#| (VDP_SUGAR V1) (IPLUS2 (VDP_SUGAR V2) (EV_TDEG T2))))
      (RETURN R))) 
(PUT 'GB_REDUCE 'NUMBER-OF-ARGS 2) 
(PUT 'GB_REDUCE 'DEFINED-ON-LINE '1249) 
(PUT 'GB_REDUCE 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_REDUCE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE GB_REDUCE (F G)
    (PROG (F1 C VEV DIVISOR TAI FOLD)
      (SETQ FOLD F)
      (SETQ F1
              (VDP_SETSUGAR (LIST 'VDP 'INVALID 'INVALID NIL NIL)
               (VDP_SUGAR F)))
      (PROG ()
       WHILELABEL
        (COND ((NOT (NOT (NULL (CAR (CDDDR F))))) (RETURN NIL)))
        (PROGN
         (SETQ VEV (CADR F))
         (SETQ C (CADDR F))
         (SETQ DIVISOR (GB_SEARCHINLIST VEV G))
         (COND
          (DIVISOR
           (PROGN
            (SETQ TAI T)
            (COND
             ((DIP_MONP (CAR (CDDDR DIVISOR)))
              (SETQ F (VDP_CANCELMEV F (CADR DIVISOR))))
             (T (SETQ F (GB_REDUCEONESTEPRAT F C VEV DIVISOR))))
            NIL))
          (T (PROGN (SETQ F (GB_SHIFT F F1)) (SETQ F1 SECONDVALUE*)))))
        (GO WHILELABEL))
      (RETURN (COND (TAI F1) (T FOLD))))) 
(PUT 'GB_REDUCEONESTEPRAT 'NUMBER-OF-ARGS 4) 
(PUT 'GB_REDUCEONESTEPRAT 'DEFINED-ON-LINE '1274) 
(PUT 'GB_REDUCEONESTEPRAT 'DEFINED-IN-FILE 'CGB/GB.RED) 
(PUT 'GB_REDUCEONESTEPRAT 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GB_REDUCEONESTEPRAT (F C VEV G1)
    (PROG (B RG1 VEVCOF)
      (SETQ RG1 (VDP_MRED G1))
      (COND ((NULL (CAR (CDDDR RG1))) (RETURN (VDP_MRED F))))
      (SETQ B (BC_QUOT C (CADDR G1)))
      (SETQ VEVCOF (EV_DIF VEV (CADR G1)))
      (RETURN (VDP_ILCOMBR (VDP_MRED F) (BC_A2BC 1) RG1 (BC_NEG B) VEVCOF)))) 
(ENDMODULE) 