(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'GNUPLDRV)) 
(FLUID '(PLOTSTYLE* *TRPLOT *PLOTKEEP)) 
(GLOBAL '(*PLOTUSEPIPE *PLOTREFINE PLOTHEADER* PLOTCLEANUP* PLOTOPTIONS*)) 
(SWITCH (LIST 'PLOTUSEPIPE)) 
(SWITCH (LIST 'TRPLOT)) 
(SWITCH (LIST 'PLOTKEEP)) 
(GLOBAL '(*PLOTPAUSE PLOTCOMMAND* PLOTCMDS* PLOTDTA* PLOTHEADER* PLOTCLEANUP*)) 
(FLUID '(PLOT-FILES* PLOTPIPE*)) 
(PUT 'GP-INIT 'NUMBER-OF-ARGS 0) 
(PUT 'GP-INIT 'DEFINED-ON-LINE '69) 
(PUT 'GP-INIT 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-INIT 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE GP-INIT NIL
    (PROGN
     (COND ((NULL PLOTCOMMAND*) (INITIALIZE_GNUPLOT)))
     (COND
      ((NULL PLOTCOMMAND*)
       (REDERR " no support for GNUPLOT in this installation")))
     (SETQ PLOT-FILES* PLOTDTA*)
     (SETQ PLOTOPTIONS* NIL)
     (PLOTOPENDISPLAY)
     NIL)) 
(PUT 'GNUPLOT 'INIT 'GP-INIT) 
(PUT 'PLOT-FILENAME 'NUMBER-OF-ARGS 0) 
(PUT 'PLOT-FILENAME 'DEFINED-ON-LINE '81) 
(PUT 'PLOT-FILENAME 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOT-FILENAME 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE PLOT-FILENAME NIL
    ((LAMBDA (U) (PROGN (SETQ PLOT-FILES* (CDR PLOT-FILES*)) U))
     (COND ((NULL PLOT-FILES*) (REDERR "ran out of scratch files"))
           (T (CAR PLOT-FILES*))))) 
(PUT 'GP-RESET 'NUMBER-OF-ARGS 0) 
(PUT 'GP-RESET 'DEFINED-ON-LINE '86) 
(PUT 'GP-RESET 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-RESET 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE GP-RESET NIL
    (COND
     ((AND *PLOTUSEPIPE PLOTPIPE*)
      (PROGN
       (PLOTPRIN2 "exit")
       (PLOTTERPRI)
       (CLOSE PLOTPIPE*)
       (SETQ PLOTPIPE* NIL)
       NIL)))) 
(PUT 'GNUPLOT 'RESET 'GP-RESET) 
(PUT 'PLOTOPENDISPLAY 'NUMBER-OF-ARGS 0) 
(PUT 'PLOTOPENDISPLAY 'DEFINED-ON-LINE '93) 
(PUT 'PLOTOPENDISPLAY 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTOPENDISPLAY 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE PLOTOPENDISPLAY NIL
    (PROG ()
      (COND ((NULL PLOTCOMMAND*) (INITIALIZE_GNUPLOT)))
      (COND
       ((NULL PLOTCOMMAND*)
        (REDERR " no support for GNUPLOT in this installation")))
      (COND
       ((NULL PLOTPIPE*)
        (COND ((NOT *PLOTUSEPIPE) (SETQ PLOTPIPE* (OPEN PLOTCMDS* 'OUTPUT)))
              (T (PROGN (SETQ PLOTPIPE* (PIPE-OPEN PLOTCOMMAND* 'OUTPUT)))))))
      (COND ((NULL PLOTHEADER*) NIL)
            ((ATOM PLOTHEADER*) (PROGN (PLOTPRIN2 PLOTHEADER*) (PLOTTERPRI)))
            ((EQCAR PLOTHEADER* 'LIST)
             (PROG (X)
               (SETQ X (CDR PLOTHEADER*))
              LAB
               (COND ((NULL X) (RETURN NIL)))
               ((LAMBDA (X) (PROGN (PLOTPRIN2 X) (PLOTTERPRI))) (CAR X))
               (SETQ X (CDR X))
               (GO LAB)))
            (T (TYPERR PLOTHEADER* "gnuplot header"))))) 
(PUT 'GP-SHOW 'NUMBER-OF-ARGS 0) 
(PUT 'GP-SHOW 'DEFINED-ON-LINE '108) 
(PUT 'GP-SHOW 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-SHOW 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE GP-SHOW NIL
    (COND ((AND *PLOTUSEPIPE PLOTPIPE*) (PROGN (CHANNELFLUSH PLOTPIPE*) NIL))
          (T
           (PROGN
            (COND (*PLOTPAUSE (PLOTPRIN2LT (LIST "pause " *PLOTPAUSE))))
            (CLOSE PLOTPIPE*)
            (SETQ PLOTPIPE* NIL)
            (COND ((NULL PLOTCOMMAND*) (INITIALIZE_GNUPLOT)))
            (COND
             ((NULL PLOTCOMMAND*)
              (REDERR " no support for GNUPLOT in this installation")))
            (COND
             (PLOTCOMMAND*
              (PROGN
               (PLOT-EXEC PLOTCOMMAND*)
               (COND
                ((NOT *PLOTKEEP)
                 (PROG (U)
                   (SETQ U PLOTCLEANUP*)
                  LAB
                   (COND ((NULL U) (RETURN NIL)))
                   ((LAMBDA (U) (SYSTEM U)) (CAR U))
                   (SETQ U (CDR U))
                   (GO LAB))))
               NIL)))
            NIL)))) 
(PUT 'GNUPLOT 'SHOW 'GP-SHOW) 
(PUT 'PLOT-EXEC 'NUMBER-OF-ARGS 1) 
(PUT 'PLOT-EXEC 'DEFINED-ON-LINE '127) 
(PUT 'PLOT-EXEC 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOT-EXEC 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOT-EXEC (U) (SYSTEM U)) 
(PUT 'PLOTPRIN2 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPRIN2 'DEFINED-ON-LINE '129) 
(PUT 'PLOTPRIN2 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRIN2 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPRIN2 (U)
    ((LAMBDA (V *LOWER) (PROGN (PRIN2 U) (WRS V) (COND (*TRPLOT (PRIN2 U)))))
     (WRS PLOTPIPE*) T)) 
(PUT 'PLOTTERPRI 'NUMBER-OF-ARGS 0) 
(PUT 'PLOTTERPRI 'DEFINED-ON-LINE '133) 
(PUT 'PLOTTERPRI 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTTERPRI 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE PLOTTERPRI NIL
    ((LAMBDA (V) (PROGN (TERPRI) (WRS V) (COND (*TRPLOT (TERPRI)))))
     (WRS PLOTPIPE*))) 
(PUT 'PLOTPRIN2LT 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPRIN2LT 'DEFINED-ON-LINE '137) 
(PUT 'PLOTPRIN2LT 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRIN2LT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPRIN2LT (L)
    (PROGN
     (PROG (X)
       (SETQ X L)
      LAB
       (COND ((NULL X) (RETURN NIL)))
       ((LAMBDA (X) (PLOTPRIN2 X)) (CAR X))
       (SETQ X (CDR X))
       (GO LAB))
     (PLOTTERPRI))) 
(FLUID '(PLOTPRINITMS*)) 
(PUT 'PLOTPRINEXPR 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPRINEXPR 'DEFINED-ON-LINE '142) 
(PUT 'PLOTPRINEXPR 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRINEXPR 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPRINEXPR (U)
    (PROG (PLOTPRINITMS* *LOWER V)
      (SETQ *LOWER T)
      (SETQ V (WRS PLOTPIPE*))
      (SETQ PLOTPRINITMS* 0)
      (COND
       ((EQCAR U 'FILE)
        (PROGN (PRIN2 '|"|) (PRIN2 (CADR U)) (PRIN2 '|"|) (PRIN2 " ")))
       (T (ERRORSET (LIST 'PLOTPRINEXPR1 (MKQUOTE U) NIL) NIL NIL)))
      (WRS V))) 
(PUT 'PLOTPRINEXPR1 'NUMBER-OF-ARGS 2) 
(PUT 'PLOTPRINEXPR1 'DEFINED-ON-LINE '154) 
(PUT 'PLOTPRINEXPR1 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRINEXPR1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE PLOTPRINEXPR1 (U OLDOP)
    (PROG (OP)
      (COND
       ((GREATERP PLOTPRINITMS* 5)
        (PROGN (PRIN2 "\\") (TERPRI) (SETQ PLOTPRINITMS* 0))))
      (COND
       ((ATOM U)
        (PROGN
         (PRIN2 (COND ((EQUAL U 'E) 2.718281) ((EQUAL U 'PI) 3.14159) (T U)))
         (SETQ PLOTPRINITMS* (PLUS PLOTPRINITMS* 1))))
       ((EQCAR U '|:RD:|)
        (PLOTPRINEXPR1 (COND ((ATOM (CDR U)) (CDR U)) (T (BF2FLR U))) NIL))
       ((MEMQ (SETQ OP (CAR U)) '(PLUS TIMES DIFFERENCE QUOTIENT EXPT))
        (PLOTPRINEXPR2 (CDR U) (GET (CAR U) 'PRTCH)
         (AND OLDOP
              (NOT
               (MEMQ OP (MEMQ OLDOP '(DIFFERENCE PLUS TIMES QUOTIENT EXPT)))))
         OP))
       ((EQUAL OP 'MINUS)
        (PROGN (PRIN2 "(-") (PLOTPRINEXPR1 (CADR U) T) (PRIN2 ")")))
       ((GET (CAR U) '|:RD:|)
        (PROGN (PRIN2 (CAR U)) (PLOTPRINEXPR2 (CDR U) '|,| T NIL)))
       (T (TYPERR U " expression for printing"))))) 
(PUT 'PLOTPRINEXPR2 'NUMBER-OF-ARGS 4) 
(PUT 'PLOTPRINEXPR2 'DEFINED-ON-LINE '184) 
(PUT 'PLOTPRINEXPR2 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRINEXPR2 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE PLOTPRINEXPR2 (U SEP BR OP)
    (PROGN
     (COND (BR (PRIN2 " (")))
     (PROG ()
      WHILELABEL
       (COND ((NOT U) (RETURN NIL)))
       (PROGN
        (PLOTPRINEXPR1 (CAR U) OP)
        (SETQ U (CDR U))
        (COND (U (PRIN2 SEP))))
       (GO WHILELABEL))
     (COND (BR (PRIN2 ") "))))) 
(PUT 'GNUPLOTEVAL 'NUMBER-OF-ARGS 1) 
(PUT 'GNUPLOTEVAL 'DEFINED-ON-LINE '193) 
(PUT 'GNUPLOTEVAL 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GNUPLOTEVAL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GNUPLOTEVAL (U)
    (PROG (M EVALLHSEQP*)
      (SETQ EVALLHSEQP* T)
      (SETQ M (PLOTROUNDED NIL))
      (PLOTOPENDISPLAY)
      (PROG (V)
        (SETQ V U)
       LAB
        (COND ((NULL V) (RETURN NIL)))
        ((LAMBDA (V) (PROGN (PLOTPRINEXPR (REVAL1 V T)) (PLOTPRIN2 " ")))
         (CAR V))
        (SETQ V (CDR V))
        (GO LAB))
      (PLOTTERPRI)
      (PLOTROUNDED M))) 
(PUT 'GNUPLOT 'PSOPFN 'GNUPLOTEVAL) 
(FLAG
 '(CONTOUR NOCONTOUR LOGSCALE NOLOGSCALE SURFACE NOSURFACE HIDDEN3D PM3D XLABEL
   YLABEL ZLABEL TITLE SIZE TERMINAL VIEW OUTPUT)
 'GP-OPTION) 
(PUT 'GNUPLOT 'OPTION 'GP-OPTION) 
(PUT 'PLOTPOINTS 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPOINTS 'DEFINED-ON-LINE '221) 
(PUT 'PLOTPOINTS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPOINTS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPOINTS (U)
    (PROG (F FN OF DIM W)
      (SETQ FN (PLOT-FILENAME))
      (SETQ F (OPEN FN 'OUTPUT))
      (SETQ OF (WRS F))
      (SETQ W (LIST 'PLOTPOINTS0 (MKQUOTE (CONS NIL U))))
      (SETQ DIM (ERRORSET W T NIL))
      (WRS OF)
      (CLOSE F)
      (COND ((PLOTERRORP DIM) (REDERR "failure during plotting point set")))
      (RETURN
       (COND ((EQUAL (CAR DIM) 2) (LIST 'FILE FN 'X))
             (T (LIST 'FILE FN 'X 'Y)))))) 
(PUT 'PLOTPOINTS0 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPOINTS0 'DEFINED-ON-LINE '235) 
(PUT 'PLOTPOINTS0 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPOINTS0 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPOINTS0 (U)
    (PROG (Z BOOL N)
      (SETQ N 0)
      (PROG (X)
        (SETQ X (CDR U))
       LAB
        (COND ((NULL X) (RETURN NIL)))
        ((LAMBDA (X)
           (COND ((AND (NOT BOOL) (EQCAR X 'LIST)) (SETQ N (PLOTPOINTS0 X)))
                 (T
                  (PROGN
                   (SETQ BOOL T)
                   (SETQ N (IPLUS2 N 1))
                   (SETQ Z (RDWRAP (REVAL1 X T)))
                   (COND
                    ((NOT (NUMBERP Z)) (PROGN (WRS NIL) (TYPERR X "number"))))
                   (PRIN2 Z)
                   (PRIN2 " ")
                   NIL))))
         (CAR X))
        (SETQ X (CDR X))
        (GO LAB))
      (TERPRI)
      (RETURN N))) 
(PUT 'PLOTPOINTS1 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPOINTS1 'DEFINED-ON-LINE '250) 
(PUT 'PLOTPOINTS1 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPOINTS1 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPOINTS1 (U)
    (PROG (F FN OF Y)
      (SETQ FN (PLOT-FILENAME))
      (SETQ F (OPEN FN 'OUTPUT))
      (SETQ OF (WRS F))
      (PROG (X)
        (SETQ X U)
       LAB
        (COND ((NULL X) (RETURN NIL)))
        ((LAMBDA (X)
           (PROGN
            (PROG (Y)
              (SETQ Y X)
             LAB
              (COND ((NULL Y) (RETURN NIL)))
              ((LAMBDA (Y) (GP-PLOTPRINPOINT Y)) (CAR Y))
              (SETQ Y (CDR Y))
              (GO LAB))
            (TERPRI)
            NIL))
         (CAR X))
        (SETQ X (CDR X))
        (GO LAB))
      (WRS OF)
      (CLOSE F)
      (RETURN FN))) 
(PUT 'GP-PLOTGRIDS 'NUMBER-OF-ARGS 1) 
(PUT 'GP-PLOTGRIDS 'DEFINED-ON-LINE '264) 
(PUT 'GP-PLOTGRIDS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-PLOTGRIDS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GP-PLOTGRIDS (G)
    (PROG (F FN OF Y)
      (SETQ FN (PLOT-FILENAME))
      (SETQ F (OPEN FN 'OUTPUT))
      (SETQ OF (WRS F))
      (PROG (U)
        (SETQ U G)
       LAB
        (COND ((NULL U) (RETURN NIL)))
        ((LAMBDA (U)
           (PROGN
            (PROG (X)
              (SETQ X U)
             LAB
              (COND ((NULL X) (RETURN NIL)))
              ((LAMBDA (X)
                 (PROGN
                  (PROG (Y)
                    (SETQ Y X)
                   LAB
                    (COND ((NULL Y) (RETURN NIL)))
                    ((LAMBDA (Y) (GP-PLOTPRINPOINT Y)) (CAR Y))
                    (SETQ Y (CDR Y))
                    (GO LAB))
                  (TERPRI)
                  NIL))
               (CAR X))
              (SETQ X (CDR X))
              (GO LAB))
            NIL))
         (CAR U))
        (SETQ U (CDR U))
        (GO LAB))
      (WRS OF)
      (CLOSE F)
      (RETURN FN))) 
(PUT 'GP-PLOTQUADS 'NUMBER-OF-ARGS 1) 
(PUT 'GP-PLOTQUADS 'DEFINED-ON-LINE '282) 
(PUT 'GP-PLOTQUADS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-PLOTQUADS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GP-PLOTQUADS (U)
    (PROG (F FN OF)
      (SETQ FN (PLOT-FILENAME))
      (SETQ F (OPEN FN 'OUTPUT))
      (SETQ OF (WRS F))
      (PROG (Q)
        (SETQ Q U)
       LAB
        (COND ((NULL Q) (RETURN NIL)))
        ((LAMBDA (Q)
           (PROGN
            (GP-PLOTPRINPOINT (CAR Q))
            (GP-PLOTPRINPOINT (CADR Q))
            (TERPRI)
            (GP-PLOTPRINPOINT (CADDDR Q))
            (GP-PLOTPRINPOINT (CADDR Q))
            (TERPRI)
            (TERPRI)
            NIL))
         (CAR Q))
        (SETQ Q (CDR Q))
        (GO LAB))
      (WRS OF)
      (CLOSE F)
      (RETURN FN))) 
(PUT 'GP-PLOTPRINPOINT 'NUMBER-OF-ARGS 1) 
(PUT 'GP-PLOTPRINPOINT 'DEFINED-ON-LINE '303) 
(PUT 'GP-PLOTPRINPOINT 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-PLOTPRINPOINT 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GP-PLOTPRINPOINT (Y)
    (PROGN
     (COND ((OR (NULL Y) (MEMBER NIL Y)) T)
           (T
            (PROG (Z)
              (SETQ Z Y)
             LAB
              (COND ((NULL Z) (RETURN NIL)))
              ((LAMBDA (Z) (PROGN (PLOTPRIN2NUMBER Z) (PRIN2 " "))) (CAR Z))
              (SETQ Z (CDR Z))
              (GO LAB))))
     (TERPRI))) 
(PUT 'PLOTPRIN2NUMBER 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTPRIN2NUMBER 'DEFINED-ON-LINE '309) 
(PUT 'PLOTPRIN2NUMBER 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTPRIN2NUMBER 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTPRIN2NUMBER (U)
    (PRIN2 (COND ((AND (FLOATP U) (LESSP (ABS U) PLOTMIN*)) "0.0") (T U)))) 
(FLAG '(XLABEL YLABEL ZLABEL OUTPUT TITLE) 'PLOTSTRING) 
(PUT 'GP-PLOTOPTIONS 'NUMBER-OF-ARGS 0) 
(PUT 'GP-PLOTOPTIONS 'DEFINED-ON-LINE '315) 
(PUT 'GP-PLOTOPTIONS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-PLOTOPTIONS 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE GP-PLOTOPTIONS NIL
    (PROGN
     (COND
      ((NOT (MEMQ 'POLAR PLOTOPTIONS*))
       (SETQ PLOTOPTIONS* (CONS 'NOPOLAR PLOTOPTIONS*))))
     (COND
      ((NOT (MEMQ 'CONTOUR PLOTOPTIONS*))
       (SETQ PLOTOPTIONS* (CONS 'NOCONTOUR PLOTOPTIONS*))))
     (COND
      ((NOT (ASSOC 'TITLE PLOTOPTIONS*))
       (SETQ PLOTOPTIONS* (CONS '(TITLE . "REDUCE Plot") PLOTOPTIONS*))))
     (PROG (X)
       (SETQ X PLOTOPTIONS*)
      LAB
       (COND ((NULL X) (RETURN NIL)))
       ((LAMBDA (X)
          (PROG (A B)
            (SETQ A X)
            (COND ((NOT (IDP A)) (SETQ A (CAR A))))
            (COND ((SETQ B (GET A 'OLDNAM)) (SETQ A B)))
            (SETQ B (EXPLODE2 A))
            (COND
             ((AND (EQCAR B 'N) (EQCAR (CDR B) 'O))
              (PROGN (SETQ A (COMPRESS (CDDR B))) (SETQ B "unset ")))
             (T (SETQ B "set ")))
            (PLOTPRIN2 B)
            (COND ((IDP X) (PLOTPRIN2 A))
                  (T
                   (PROGN
                    (PLOTPRIN2 A)
                    (PLOTPRIN2 " ")
                    (COND ((FLAGP (CAR X) 'PLOTSTRING) (PLOTPRIN2 '|"|)))
                    (PLOTPRIN2 (CDR X))
                    (COND ((FLAGP (CAR X) 'PLOTSTRING) (PLOTPRIN2 '|"|))))))
            (PLOTTERPRI)))
        (CAR X))
       (SETQ X (CDR X))
       (GO LAB))
     NIL)) 
(PUT 'PLOTSTYLE1 'NUMBER-OF-ARGS 0) 
(PUT 'PLOTSTYLE1 'DEFINED-ON-LINE '346) 
(PUT 'PLOTSTYLE1 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTSTYLE1 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE PLOTSTYLE1 NIL
    (COND
     (PLOTSTYLE*
      (PROGN
       (PLOTPRIN2 " \\")
       (PLOTTERPRI)
       (PLOTPRIN2 " with ")
       (PLOTPRIN2 PLOTSTYLE*)
       (PLOTPRIN2 " ")
       NIL)))) 
(PUT 'PLOTSTYLE 'NUMBER-OF-ARGS 1) 
(PUT 'PLOTSTYLE 'DEFINED-ON-LINE '355) 
(PUT 'PLOTSTYLE 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'PLOTSTYLE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PLOTSTYLE (OPTION)
    (COND
     ((MEMQ OPTION
            '(LINES POINTS LINESPOINTS IMPULSES DOTS ERRORBARS BOXES
              BOXERRORBARS BOXXYERRORBARS CANDLESTICKS FINANCEBARS FSTEPS
              HISTEPS STEPS VECTOR XERRORBARS XYERRORBARS YERRORBARS))
      (SETQ PLOTSTYLE* OPTION))
     (T (TYPERR OPTION "plot style option")))) 
(PUT 'STYLE 'GP-DO 'PLOTSTYLE) 
(PUT 'GP-2EXP 'NUMBER-OF-ARGS 4) 
(PUT 'GP-2EXP 'DEFINED-ON-LINE '368) 
(PUT 'GP-2EXP 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-2EXP 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GP-2EXP (X Y PTS FP)
    (PROG (CM CM1)
      (SETQ PLOTOPTIONS* (CONS 'NOPARAMETRIC PLOTOPTIONS*))
      (PLOTPRIN2LT (LIST "set size 1,1"))
      (PLOTPRIN2LT (LIST "set xlabel " '|"| X '|"|))
      (PLOTPRIN2LT (LIST "set ylabel " '|"| Y '|"|))
      (GP-PLOTOPTIONS)
      (PLOTPRIN2LT (LIST "unset key"))
      (COND ((OR PTS FP) (PLOTPRIN2 "plot ")))
      (PROG (F)
        (SETQ F (REVERSIP PTS))
       LAB
        (COND ((NULL F) (RETURN NIL)))
        ((LAMBDA (F)
           (PROGN
            (COND (CM (PROGN (PLOTPRIN2 ",\\") (PLOTTERPRI))))
            (PLOTPRIN2 "'")
            (PLOTPRIN2 (PLOTPOINTS1 F))
            (PLOTPRIN2 "'")
            (PLOTSTYLE1)
            (SETQ CM T)
            NIL))
         (CAR F))
        (SETQ F (CDR F))
        (GO LAB))
      (COND
       (FP
        (PROGN
         (COND (CM (PROGN (PLOTPRIN2 ",\\") (PLOTTERPRI))))
         (COND
          ((ATOM FP)
           (PROGN
            (PLOTPRIN2 "'")
            (PLOTPRIN2 FP)
            (PLOTPRIN2 "'")
            (COND (CM (PLOTPRIN2 " with points")) (T (PLOTSTYLE1)))
            NIL))
          (T
           (PROG (FF)
             (SETQ FF FP)
            LAB
             (COND ((NULL FF) (RETURN NIL)))
             ((LAMBDA (FF)
                (PROGN
                 (COND (CM1 (PROGN (PLOTPRIN2 ",\\") (PLOTTERPRI))))
                 (PLOTPRIN2 "'")
                 (PLOTPRIN2 FF)
                 (PLOTPRIN2 "'")
                 (COND (CM (PLOTPRIN2 " with points")) (T (PLOTSTYLE1)))
                 (SETQ CM1 T)
                 NIL))
              (CAR FF))
             (SETQ FF (CDR FF))
             (GO LAB))))
         NIL)))
      (PLOTTERPRI))) 
(PUT 'GNUPLOT 'PLOT-2EXP 'GP-2EXP) 
(PUT 'BADPOINTP 'NUMBER-OF-ARGS 1) 
(PUT 'BADPOINTP 'DEFINED-ON-LINE '405) 
(PUT 'BADPOINTP 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'BADPOINTP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE BADPOINTP (U) (OR (NULL U) (MEMQ NIL U))) 
(PUT 'GP-3EXP 'NUMBER-OF-ARGS 4) 
(PUT 'GP-3EXP 'DEFINED-ON-LINE '408) 
(PUT 'GP-3EXP 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-3EXP 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GP-3EXP (X Y Z PTS)
    (PROG (CM H)
      (COND ((EQUAL Z 'POINTS) (SETQ Z 'Z))
            (T
             (SETQ PTS
                     (PROG (F FORALL-RESULT FORALL-ENDPTR)
                       (SETQ F PTS)
                       (COND ((NULL F) (RETURN NIL)))
                       (SETQ FORALL-RESULT
                               (SETQ FORALL-ENDPTR
                                       (CONS
                                        ((LAMBDA (F) (GP-PLOTGRIDS F)) (CAR F))
                                        NIL)))
                      LOOPLABEL
                       (SETQ F (CDR F))
                       (COND ((NULL F) (RETURN FORALL-RESULT)))
                       (RPLACD FORALL-ENDPTR
                               (CONS ((LAMBDA (F) (GP-PLOTGRIDS F)) (CAR F))
                                     NIL))
                       (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                       (GO LOOPLABEL)))))
      (PLOTPRIN2LT (LIST "unset hidden3d"))
      (PLOTPRIN2LT (LIST "unset pm3d"))
      (COND
       ((NOT H)
        (SETQ PLOTOPTIONS*
                (CONS 'PARAMETRIC (DELETE 'NOPARAMETRIC PLOTOPTIONS*))))
       (T
        (SETQ PLOTOPTIONS*
                (CONS 'NOPARAMETRIC (DELETE 'PARAMETRIC PLOTOPTIONS*)))))
      (PLOTPRIN2LT (LIST "set view 60,30,1,1"))
      (PLOTPRIN2LT (LIST "set size 1,1"))
      (COND (H (PLOTPRIN2LT (LIST "set format xy " '|"| '|"|))))
      (PLOTPRIN2LT (LIST "set xlabel " '|"| X '|"|))
      (PLOTPRIN2LT (LIST "set ylabel " '|"| Y '|"|))
      (PLOTPRIN2LT (LIST "set zlabel " '|"| Z '|"|))
      (GP-PLOTOPTIONS)
      (PLOTPRIN2LT (LIST "unset key"))
      (PLOTPRIN2 "splot ")
      (PROG (F)
        (SETQ F PTS)
       LAB
        (COND ((NULL F) (RETURN NIL)))
        ((LAMBDA (F)
           (PROGN
            (COND (CM (PROGN (PLOTPRIN2 ",\\") (PLOTTERPRI))))
            (PLOTPRIN2 "'")
            (PLOTPRIN2 F)
            (PLOTPRIN2 "'")
            (PLOTPRIN2 " with lines ")
            (SETQ CM T)
            NIL))
         (CAR F))
        (SETQ F (CDR F))
        (GO LAB))
      (PLOTTERPRI)
      (COND (H (PLOTPRIN2LT (LIST "set format xy")))))) 
(PUT 'GNUPLOT 'PLOT-3EXP-REG 'GP-3EXP) 
(PUT 'GP-REG2QUADS 'NUMBER-OF-ARGS 1) 
(PUT 'GP-REG2QUADS 'DEFINED-ON-LINE '447) 
(PUT 'GP-REG2QUADS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-REG2QUADS 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GP-REG2QUADS (F)
    (PROG (L L1 L2 P1 P2 P3 P4)
      (PROG ()
       WHILELABEL
        (COND ((NOT (AND F (CDR F))) (RETURN NIL)))
        (PROGN
         (SETQ L1 (CAR F))
         (SETQ L2 (CADR F))
         (SETQ F (CDR F))
         (PROG ()
          WHILELABEL
           (COND ((NOT (AND L1 (CDR L1))) (RETURN NIL)))
           (PROGN
            (SETQ P1 (CAR L1))
            (SETQ L1 (CDR L1))
            (SETQ P2 (CAR L1))
            (SETQ P4 (CAR L2))
            (SETQ L2 (CDR L2))
            (SETQ P3 (CAR L2))
            (COND
             ((AND (NOT (BADPOINTP P1)) (NOT (BADPOINTP P2))
                   (NOT (BADPOINTP P3)) (NOT (BADPOINTP P4)))
              (SETQ L (CONS (LIST P1 P2 P3 P4) L)))))
           (GO WHILELABEL)))
        (GO WHILELABEL))
      (RETURN L))) 
(PUT 'GP-3QUADS 'NUMBER-OF-ARGS 4) 
(PUT 'GP-3QUADS 'DEFINED-ON-LINE '462) 
(PUT 'GP-3QUADS 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-3QUADS 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE GP-3QUADS (X Y Z F)
    (PROG (H)
      (SETQ H (MEMBER 'HIDDEN3D PLOTOPTIONS*))
      (SETQ F (GP-PLOTQUADS F))
      (PLOTPRIN2LT (LIST "unset hidden3d"))
      (PLOTPRIN2LT (LIST "unset pm3d"))
      (SETQ PLOTOPTIONS*
              (CONS 'PARAMETRIC (DELETE 'NOPARAMETRIC PLOTOPTIONS*)))
      (PLOTPRIN2LT (LIST "set view 60,30,1,1"))
      (PLOTPRIN2LT (LIST "set size 1,1"))
      (COND (H (PLOTPRIN2LT (LIST "set format xy " '|"| '|"|))))
      (PLOTPRIN2LT (LIST "set xlabel " '|"| X '|"|))
      (PLOTPRIN2LT (LIST "set ylabel " '|"| Y '|"|))
      (PLOTPRIN2LT (LIST "set zlabel " '|"| Z '|"|))
      (GP-PLOTOPTIONS)
      (PLOTPRIN2LT (LIST "unset key"))
      (PLOTPRIN2 "splot ")
      (PLOTPRIN2 "'")
      (PLOTPRIN2 F)
      (PLOTPRIN2 "'")
      (PLOTPRIN2 " with lines ")
      (PLOTTERPRI)
      (PLOTPRIN2LT (LIST "unset hidden3d"))
      (PLOTPRIN2LT (LIST "unset pm3d"))
      (COND (H (PLOTPRIN2LT (LIST "set format xy")))))) 
(PUT 'GNUPLOT 'PLOT-3QUADS 'GP-3QUADS) 
(PUT 'GP-2IMP 'NUMBER-OF-ARGS 8) 
(PUT 'GP-2IMP 'DEFINED-ON-LINE '493) 
(PUT 'GP-2IMP 'DEFINED-IN-FILE 'PLOT/GNUPLDRV.RED) 
(PUT 'GP-2IMP 'PROCEDURE_TYPE
     '(ARROW
       (TIMES GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL GENERAL)
       GENERAL)) 
(DE GP-2IMP (X Y L G XMIN XMAX YMIN YMAX)
    (PROG (F Q)
      (SETQ Q
              (LIST (LIST XMIN YMIN) NIL (LIST XMIN YMAX) NIL (LIST XMAX YMIN)
                    NIL (LIST XMAX YMAX)))
      (SETQ PLOTOPTIONS* (CONS 'NOPARAMETRIC PLOTOPTIONS*))
      (SETQ F (PLOTPOINTS1 (CONS Q L)))
      (PLOTPRIN2LT (LIST "set size 1,1"))
      (PLOTPRIN2LT (LIST "set xlabel " '|"| X '|"|))
      (PLOTPRIN2LT (LIST "set ylabel " '|"| Y '|"|))
      (GP-PLOTOPTIONS)
      (PLOTPRIN2LT (LIST "unset key"))
      (PLOTPRIN2 "plot ")
      (PLOTPRIN2 "'")
      (PLOTPRIN2 F)
      (PLOTPRIN2 "'")
      (PLOTPRIN2 " with lines")
      (COND
       (G
        (PROGN
         (PLOTPRIN2 ", '")
         (PLOTPRIN2 (PLOTPOINTS1 G))
         (PLOTPRIN2 "' with lines")
         NIL)))
      (PLOTTERPRI))) 
(PUT 'GNUPLOT 'PLOT-2IMP 'GP-2IMP) 
(ENDMODULE) 