(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'MATHPR)) 
(CREATE-PACKAGE '(MATHPR MPRINT SQPRINT RATPRIN DFPRIN FORTPRI) NIL) 
(FLAG '(MATHPR) 'CORE_PACKAGE) 
(ENDMODULE) 