(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'PASFBNF)) 
(REVISION 'PASFBNF "$Id: pasfbnf.red 5986 2021-08-28 13:35:27Z thomas-sturm $") 
(COPYRIGHT 'PASF
           "(c) 2002-2009 A. Dolzmann, A. Seidl, T. Sturm, 2010-2020 T. Sturm") 
(PUT 'PASF_SACAT 'NUMBER-OF-ARGS 3) 
(PUT 'PASF_SACAT 'DEFINED-ON-LINE '34) 
(PUT 'PASF_SACAT 'DEFINED-IN-FILE 'REDLOG/PASF/PASFBNF.RED) 
(PUT 'PASF_SACAT 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE PASF_SACAT (A1 A2 GOR) NIL) 
(PUT 'PASF_DNF 'NUMBER-OF-ARGS 1) 
(PUT 'PASF_DNF 'DEFINED-ON-LINE '40) 
(PUT 'PASF_DNF 'DEFINED-IN-FILE 'REDLOG/PASF/PASFBNF.RED) 
(PUT 'PASF_DNF 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PASF_DNF (PHI)
    (COND ((PASF_PUREGCONP PHI 'AND) PHI) (T (PASF_PBNF (PASF_PNF PHI) 'DNF)))) 
(PUT 'PASF_CNF 'NUMBER-OF-ARGS 1) 
(PUT 'PASF_CNF 'DEFINED-ON-LINE '45) 
(PUT 'PASF_CNF 'DEFINED-IN-FILE 'REDLOG/PASF/PASFBNF.RED) 
(PUT 'PASF_CNF 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PASF_CNF (PHI)
    (COND ((PASF_PUREGCONP PHI 'OR) PHI) (T (PASF_PBNF (PASF_PNF PHI) 'CNF)))) 
(PUT 'PASF_PUREGCONP 'NUMBER-OF-ARGS 2) 
(PUT 'PASF_PUREGCONP 'DEFINED-ON-LINE '50) 
(PUT 'PASF_PUREGCONP 'DEFINED-IN-FILE 'REDLOG/PASF/PASFBNF.RED) 
(PUT 'PASF_PUREGCONP 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE PASF_PUREGCONP (F GAND)
    (PROG (C FL A)
      (COND ((OR (EQ F 'TRUE) (EQ F 'FALSE)) (RETURN T)))
      (COND
       ((MEMQ
         (COND ((OR (EQ F 'TRUE) (EQ F 'FALSE)) F) ((PAIRP (CAR F)) (CAAR F))
               (T (CAR F)))
         '(EQUAL NEQ LEQ GEQ LESSP GREATERP CONG NCONG))
        (RETURN T)))
      (COND
       ((AND (PAIRP F) (EQ (COND ((ATOM F) F) (T (CAR F))) GAND))
        (PROGN
         (SETQ FL (CDR F))
         (SETQ C T)
         (PROG ()
          WHILELABEL
           (COND ((NOT (AND C FL)) (RETURN NIL)))
           (PROGN
            (SETQ A (PROG1 (CAR FL) (SETQ FL (CDR FL))))
            (COND
             ((NOT
               (MEMQ
                (COND ((OR (EQ A 'TRUE) (EQ A 'FALSE)) A)
                      ((PAIRP (CAR A)) (CAAR A)) (T (CAR A)))
                '(EQUAL NEQ LEQ GEQ LESSP GREATERP CONG NCONG)))
              (SETQ C NIL))))
           (GO WHILELABEL))
         (RETURN C))))
      (RETURN NIL))) 
(PUT 'PASF_PBNF 'NUMBER-OF-ARGS 2) 
(PUT 'PASF_PBNF 'DEFINED-ON-LINE '67) 
(PUT 'PASF_PBNF 'DEFINED-IN-FILE 'REDLOG/PASF/PASFBNF.RED) 
(PUT 'PASF_PBNF 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE PASF_PBNF (PHI FLAG)
    (PROG ()
      (COND
       (((LAMBDA (X) (OR (EQ X 'BEX) (EQ X 'BALL)))
         (COND ((ATOM PHI) PHI) (T (CAR PHI))))
        (RETURN
         (LIST (COND ((ATOM PHI) PHI) (T (CAR PHI))) (CADR PHI)
               (PASF_PBNF (CADDR PHI) FLAG) (CADDDR PHI)))))
      (COND
       (((LAMBDA (X) (OR (EQ X 'EX) (EQ X 'ALL)))
         (COND ((ATOM PHI) PHI) (T (CAR PHI))))
        (RETURN
         (LIST (COND ((ATOM PHI) PHI) (T (CAR PHI))) (CADR PHI)
               (PASF_PBNF (CADDR PHI) FLAG)))))
      (RETURN (COND ((EQ FLAG 'DNF) (CL_DNF PHI)) (T (CL_CNF PHI)))))) 
(ENDMODULE) 