(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'QUOTFX)) 
(PUT 'QUOTFX 'NUMBER-OF-ARGS 2) 
(PUT 'QUOTFX 'DEFINED-ON-LINE '55) 
(PUT 'QUOTFX 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'QUOTFX 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE QUOTFX (U V)
    (COND ((OR (NULL *EXP) (NULL *MCD)) ((LAMBDA (*EXP) (QUOTF1 U V)) T))
          (T (QUOTFX1 U V)))) 
(PUT 'QUOTFX1 'NUMBER-OF-ARGS 2) 
(PUT 'QUOTFX1 'DEFINED-ON-LINE '58) 
(PUT 'QUOTFX1 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'QUOTFX1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE QUOTFX1 (P Q)
    (COND ((NULL P) (QUOTFXERR P Q)) ((EQUAL P Q) 1) ((EQUAL Q 1) P)
          ((OR (ATOM Q) (ATOM (CAR Q))) (QUOTFDX P Q))
          ((OR (ATOM P) (ATOM (CAR P))) (QUOTFXERR P Q))
          ((EQ (CAAAR P) (CAAAR Q))
           (PROG (F DP DQ U V W X Y Z N)
             (SETQ N 0)
             (SETQ W (CAAAR Q))
             (SETQ DQ (CDAAR Q))
            A
             (COND ((LESSP (SETQ DP (CDAAR P)) DQ) (RETURN (QUOTFXERR P Q))))
             (SETQ U (LT* P))
             (SETQ V (LT* Q))
             (SETQ W (CAAAR Q))
             (SETQ X (QUOTFX1 (CDR U) (CDR V)))
             (SETQ N (IDIFFERENCE DP DQ))
             (COND ((EQUAL N 0) (RETURN (RNCONC Z X))))
             (SETQ Y (CONS W N))
             (COND ((NULL F) (SETQ P (CUTF P W (ISUB1 (IDIFFERENCE DP N))))))
             (SETQ F T)
             (SETQ Q (CUTF Q W (ISUB1 (IDIFFERENCE DQ N))))
             (SETQ P
                     (ADDF P
                           ((LAMBDA (G566 G567)
                              (COND (*PHYSOP-LOADED (PHYSOP-MULTF G566 G567))
                                    (T (POLY-MULTF G566 G567))))
                            (COND ((EQUAL N 0) Q)
                                  (T
                                   ((LAMBDA (G544)
                                      (COND
                                       (*PHYSOP-LOADED (PHYSOP-MULTF G544 Q))
                                       (T (POLY-MULTF G544 Q))))
                                    (LIST (CONS Y 1)))))
                            (NEGF X))))
             (COND
              ((AND P (OR (OR (ATOM P) (ATOM (CAR P))) (NOT (EQ (CAAAR P) W))))
               (RETURN (QUOTFXERR P Q))))
             (SETQ Z (ACONC* Z (CONS Y X)))
             (COND ((NULL P) (RETURN Z)))
             (GO A)))
          ((ORDOP (CAAAR P) (CAAAR Q)) (QUOTKX P Q)) (T (QUOTFXERR P Q)))) 
(PUT 'QUOTKX 'NUMBER-OF-ARGS 2) 
(PUT 'QUOTKX 'DEFINED-ON-LINE '91) 
(PUT 'QUOTKX 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'QUOTKX 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE QUOTKX (P Q)
    ((LAMBDA (W)
       (COND
        (W
         (COND ((NULL (CDR P)) (LIST (CONS (CAAR P) W)))
               (T
                ((LAMBDA (Y) (COND (Y (CONS (CONS (CAAR P) W) Y)) (T NIL)))
                 (QUOTFX1 (CDR P) Q)))))
        (T NIL)))
     (QUOTFX1 (CDAR P) Q))) 
(PUT 'QUOTFDX 'NUMBER-OF-ARGS 2) 
(PUT 'QUOTFDX 'DEFINED-ON-LINE '98) 
(PUT 'QUOTFDX 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'QUOTFDX 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE QUOTFDX (P Q)
    (COND ((EQUAL P Q) 1) ((FLAGP DMODE* 'FIELD) (DIVD P Q))
          ((OR (ATOM P) (ATOM (CAR P))) (QUOTDD P Q)) (T (QUOTKX P Q)))) 
(PUT 'QUOTFXERR 'NUMBER-OF-ARGS 2) 
(PUT 'QUOTFXERR 'DEFINED-ON-LINE '104) 
(PUT 'QUOTFXERR 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'QUOTFXERR 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE QUOTFXERR (U V) (REDERR "exact division failed")) 
(PUT 'CUTF 'NUMBER-OF-ARGS 3) 
(PUT 'CUTF 'DEFINED-ON-LINE '107) 
(PUT 'CUTF 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'CUTF 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE CUTF (U X N) (COND ((ILESSP N 1) U) (T (CUTF1 U X N)))) 
(PUT 'CUTF1 'NUMBER-OF-ARGS 3) 
(PUT 'CUTF1 'DEFINED-ON-LINE '111) 
(PUT 'CUTF1 'DEFINED-IN-FILE 'POLY/QUOTF.RED) 
(PUT 'CUTF1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE CUTF1 (U X N)
    (COND
     ((OR (OR (ATOM U) (ATOM (CAR U))) (NEQ (CAAAR U) X) (ILESSP (CDAAR U) N))
      NIL)
     (T (CONS (CAR U) (CUTF1 (CDR U) X N))))) 
(ENDMODULE) 