(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'REMAKE)) 
(FLUID
 '(*BREAK *FASLP *FORCECOMPILE *INT *LOADALL *WRITINGFASLFILE LISPSYSTEM*)) 
(GLOBAL '(LOADED-MODULES* FASL-DIR* FASL-EXT*)) 
(PUT 'OLDERFASLP 'NUMBER-OF-ARGS 2) 
(PUT 'OLDERFASLP 'DEFINED-ON-LINE '43) 
(PUT 'OLDERFASLP 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'OLDERFASLP 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE OLDERFASLP (U V)
    (OR (NOT (FILEP U))
        (AND (FILEP V) (LESSP (FILE-WRITE-DATE U) (FILE-WRITE-DATE V))))) 
(PUT 'PACKAGE-REMAKE 'NUMBER-OF-ARGS 1) 
(PUT 'PACKAGE-REMAKE 'DEFINED-ON-LINE '51) 
(PUT 'PACKAGE-REMAKE 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'PACKAGE-REMAKE 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE PACKAGE-REMAKE (X)
    ((LAMBDA (Y) (COND (Y (PACKAGE-REMAKE2 X Y)) (T (PACKAGE-REMAKE2 X X))))
     (GET X 'FOLDER))) 
(FLUID '(NEW_INLINE_DEFINITIONS)) 
(SETQ NEW_INLINE_DEFINITIONS NIL) 
(PUT 'INLINE_DEFS_FILE 'NUMBER-OF-ARGS 0) 
(PUT 'INLINE_DEFS_FILE 'DEFINED-ON-LINE '63) 
(PUT 'INLINE_DEFS_FILE 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'INLINE_DEFS_FILE 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE INLINE_DEFS_FILE NIL (CONCAT2 FASL-DIR* "inline-defs.dat")) 
(PUT 'LOAD_SAVED_INLINES 'NUMBER-OF-ARGS 0) 
(PUT 'LOAD_SAVED_INLINES 'DEFINED-ON-LINE '66) 
(PUT 'LOAD_SAVED_INLINES 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'LOAD_SAVED_INLINES 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE LOAD_SAVED_INLINES NIL
    (PROG (FF U V)
      (SETQ FF (INLINE_DEFS_FILE))
      (COND ((NOT (FILEP FF)) (RETURN NIL)))
      (SETQ FF (OPEN FF 'INPUT))
      (COND ((NULL FF) (RETURN NIL)))
      (SETQ U (RDS FF))
      (SETQ V (READ))
      (COND ((ATOM V) (SETQ V NIL)))
      (RDS U)
      (CLOSE FF)
      (PROG (A)
        (SETQ A V)
       LAB
        (COND ((NULL A) (RETURN NIL)))
        ((LAMBDA (A) (PUT (CAR A) 'INLINE (CDR A))) (CAR A))
        (SETQ A (CDR A))
        (GO LAB))
      (RETURN NIL))) 
(PUT 'SAVE_INLINES 'NUMBER-OF-ARGS 0) 
(PUT 'SAVE_INLINES 'DEFINED-ON-LINE '100) 
(PUT 'SAVE_INLINES 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'SAVE_INLINES 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE SAVE_INLINES NIL
    (PROG (FNAME FF U V W CHANGED)
      (COND
       ((NULL NEW_INLINE_DEFINITIONS)
        (PROGN (LPRIM "No new inline definitions here") (RETURN NIL))))
      (SETQ FNAME (INLINE_DEFS_FILE))
      (COND
       ((FILEP FNAME)
        (PROGN
         (SETQ FF (OPEN FNAME 'INPUT))
         (COND ((NULL FF) (RETURN NIL)))
         (SETQ U (RDS FF))
         (SETQ V (READ))
         (COND ((ATOM V) (SETQ V NIL)))
         (RDS U)
         (CLOSE FF)))
       (T (SETQ V NIL)))
      (SETQ CHANGED NIL)
      (PROG (A)
        (SETQ A NEW_INLINE_DEFINITIONS)
       LAB
        (COND ((NULL A) (RETURN NIL)))
        ((LAMBDA (A)
           (PROGN
            (SETQ W (ASSOC (CAR A) V))
            (COND
             ((NOT W)
              (PROGN
               (COND ((NEQ (POSN) 0) (TERPRI)))
               (PRINC "+++ new inline definition for ")
               (PRIN1 (CAR A)))))
            (COND
             ((AND W (NOT (EQUAL W A)))
              (PROGN
               (COND ((NEQ (POSN) 0) (TERPRI)))
               (PRINC "+++ inline definition for ")
               (PRIN1 (CAR A))
               (PROGN
                (PRIN2
                 " differs from previous version - please recompile everything")
                (TERPRI)
                " differs from previous version - please recompile everything")
               (SETQ V (DELASC (CAR A) V))
               (SETQ W NIL))))
            (COND ((NOT W) (PROGN (SETQ V (CONS A V)) (SETQ CHANGED T))))))
         (CAR A))
        (SETQ A (CDR A))
        (GO LAB))
      (COND
       (CHANGED
        (PROGN
         (LPRIM "Need to rewrite inline-defs.dat file")
         (SETQ FF (OPEN FNAME 'OUTPUT))
         (COND ((NULL FF) (RETURN NIL)))
         (SETQ U (WRS FF))
         (PRIN2 "(")
         (TERPRI)
         (PROG (X)
           (SETQ X V)
          LAB
           (COND ((NULL X) (RETURN NIL)))
           ((LAMBDA (X) (PROGN (PRINT X) (TERPRI))) (CAR X))
           (SETQ X (CDR X))
           (GO LAB))
         (PRIN2 ")")
         (TERPRI)
         (WRS U)
         (CLOSE FF))))
      (RETURN NIL))) 
(PUT 'PACKAGE-REMAKE2 'NUMBER-OF-ARGS 2) 
(PUT 'PACKAGE-REMAKE2 'DEFINED-ON-LINE '157) 
(PUT 'PACKAGE-REMAKE2 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'PACKAGE-REMAKE2 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE PACKAGE-REMAKE2 (U V)
    (PROG (Y *INT)
      (LOAD_SAVED_INLINES)
      (SETQ NEW_INLINE_DEFINITIONS NIL)
      (UPDATE-FASL2 U V)
      (EVLOAD (LIST U))
      (SETQ LOADED-MODULES* (UNION LOADED-MODULES* (LIST U)))
      (SETQ Y (GET U 'PACKAGE))
      (COND (Y (SETQ Y (CDR Y))))
      (PROG (J)
        (SETQ J Y)
       LAB
        (COND ((NULL J) (RETURN NIL)))
        ((LAMBDA (J) (UPDATE-FASL2 J V)) (CAR J))
        (SETQ J (CDR J))
        (GO LAB))
      (SAVE_INLINES))) 
(PUT 'UPDATE-FASL2 'NUMBER-OF-ARGS 2) 
(PUT 'UPDATE-FASL2 'DEFINED-ON-LINE '172) 
(PUT 'UPDATE-FASL2 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'UPDATE-FASL2 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE UPDATE-FASL2 (U V)
    (PROG (Y Z)
      (SETQ Y (CONCAT FASL-DIR* (MKFIL U) FASL-EXT*))
      (SETQ Z (MODULE2-TO-FILE U V))
      (COND
       ((OR (OLDERFASLP Y Z) *FORCECOMPILE)
        (PROGN
         (TERPRI)
         (TERPRI)
         (COND
          ((ERRORP
            (ERRORSET* (LIST 'UPD-FASL1 (MKQUOTE U) (MKQUOTE Z) (MKQUOTE V))
                       T))
           (PROGN
            (COND (*WRITINGFASLFILE (LISPEVAL '(FASLEND))))
            (LPRIE (LIST "Error during mkfasl of" (CONS U V))))))))))) 
(PUT 'UPD-FASL1 'NUMBER-OF-ARGS 3) 
(PUT 'UPD-FASL1 'DEFINED-ON-LINE '189) 
(PUT 'UPD-FASL1 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'UPD-FASL1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE UPD-FASL1 (U V W)
    (PROG (*BREAK)
      (SETQ *FASLP T)
      (COND
       ((AND *LOADALL W (NEQ W U))
        (PROGN
         (EVLOAD (LIST W))
         (SETQ LOADED-MODULES* (UNION LOADED-MODULES* (LIST W))))))
      (SETQ U (MKFIL U))
      (LPRIM (LIST "Compiling" U "..."))
      (TERPRI)
      (LISPEVAL (LIST 'FASLOUT (CONCAT2 FASL-DIR* U)))
      (INFILE V)
      (LISPEVAL '(FASLEND)))) 
(PUT 'MODULE2-TO-FILE 'NUMBER-OF-ARGS 2) 
(PUT 'MODULE2-TO-FILE 'DEFINED-ON-LINE '205) 
(PUT 'MODULE2-TO-FILE 'DEFINED-IN-FILE 'REMAKE.RED) 
(PUT 'MODULE2-TO-FILE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE MODULE2-TO-FILE (U V)
    (PROGN
     (SETQ U (CONCAT2 (MKFIL U) ".red"))
     (COND (V (CONCAT "$reduce/packages/" (MKFIL V) "/" U)) (T U)))) 
(ENDMODULE) 