(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'RMSUBS)) 
(FLUID '(ALGLIST*)) 
(GLOBAL '(*SQVAR*)) 
(SETQ *SQVAR* (LIST 'T)) 
(PUT 'RMSUBS 'NUMBER-OF-ARGS 0) 
(PUT 'RMSUBS 'DEFINED-ON-LINE '41) 
(PUT 'RMSUBS 'DEFINED-IN-FILE 'ALG/RMSUBS.RED) 
(PUT 'RMSUBS 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE RMSUBS NIL
    (PROG ()
      (RPLACA *SQVAR* NIL)
      (SETQ *SQVAR* (LIST T))
      (SETQ ALGLIST* (CONS NIL NIL)))) 
(ENDMODULE) 