(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'SLFNS)) 
(FLUID '(*ARGNOCHK)) 
(GLOBAL '(SLFNS*)) 
(SETQ SLFNS*
        '((ABS 1) (ADD1 1) (APPEND 2) (APPLY 2) (ASSOC 2) (ATOM 1) (CAR 1)
          (CDR 1) (CAAR 1) (CADR 1) (CDAR 1) (CDDR 1) (CAAAR 1) (CAADR 1)
          (CADAR 1) (CADDR 1) (CDAAR 1) (CDADR 1) (CDDAR 1) (CDDDR 1)
          (CAAAAR 1) (CAAADR 1) (CAADAR 1) (CAADDR 1) (CADAAR 1) (CADADR 1)
          (CADDAR 1) (CADDDR 1) (CDAAAR 1) (CDAADR 1) (CDADAR 1) (CDADDR 1)
          (CDDAAR 1) (CDDADR 1) (CDDDAR 1) (CDDDDR 1) (CLOSE 1) (CODEP 1)
          (COMPRESS 1) (CONS 2) (CONSTANTP 1) (DE 3) (DEFLIST 2) (DELETE 2)
          (DIFFERENCE 2) (DIGIT 1) (DIVIDE 2) (DM 3) (EJECT 0) (EQ 2) (EQN 2)
          (EQUAL 2) (ERROR 2) (ERRORSET 3) (EVAL 1) (EVLIS 1) (EXPAND 2)
          (EXPLODE 1) (EXPT 2) (FIX 1) (FIXP 1) (FLAG 2) (FLAGP 2) (FLOAT 1)
          (FLOATP 1) (FLUID 1) (FLUIDP 1) (FUNCTION 1) (GENSYM 0) (GET 2)
          (GETD 1) (GETV 2) (GLOBAL 1) (GLOBALP 1) (GO 1) (GREATERP 2) (IDP 1)
          (INTERN 1) (LENGTH 1) (LESSP 2) (LINELENGTH 1) (LITER 1) (LPOSN 0)
          (MAP 2) (MAPC 2) (MAPCAN 2) (MAPCAR 2) (MAPCON 2) (MAPLIST 2)
          (MAX2 2) (MEMBER 2) (MEMQ 2) (MINUS 1) (MINUSP 1) (MIN2 2) (MKVECT 1)
          (NCONC 2) (NOT 1) (NULL 1) (NUMBERP 1) (ONEP 1) (OPEN 2)
          (PAGELENGTH 1) (PAIR 2) (PAIRP 1) (PLUS2 2) (POSN 0) (PRINT 1)
          (PRIN1 1) (PRIN2 1) (PROG2 2) (PUT 3) (PUTD 3) (PUTV 3) '1
          (QUOTIENT 2) (RDS 1) (READ 0) (READCH 0) (REMAINDER 2) (REMD 1)
          (REMFLAG 2) (REMOB 1) (REMPROP 2) (RETURN 1) (REVERSE 1) (RPLACA 2)
          (RPLACD 2) (SASSOC 3) (SET 2) (SETQ 2) (STRINGP 1) (SUBLIS 2)
          (SUBST 3) (SUB1 1) (TERPRI 0) (TIMES2 2) (UNFLUID 1) (UPBV 1)
          (VECTORP 1) (WRS 1) (ZEROP 1))) 
(COND (*ARGNOCHK (DEFLIST SLFNS* 'NUMBER-OF-ARGS))) 
(ENDMODULE) 