(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'SYMDATA1)) 
(SET*ELEMS*GROUP 'Z2 '(ID SZ2)) 
(SET*GENERATORS 'Z2 '(SZ2)) 
(SET*RELATIONS 'Z2 '(((SZ2 SZ2) (ID)))) 
(SET*GROUPTABLE 'Z2 '((GROUPTABLE ID SZ2) (ID ID SZ2) (SZ2 SZ2 ID))) 
(SET*INVERSE 'Z2 '((ID SZ2) (ID SZ2))) 
(SET*ELEMASGEN 'Z2 '(((SZ2) (SZ2)))) 
(SET*GROUP 'Z2 '((ID) (SZ2))) 
(SET*REPRESENTATION 'Z2 '((ID (((1 . 1)))) (SZ2 (((1 . 1))))) 'COMPLEX) 
(SET*REPRESENTATION 'Z2 '((ID (((1 . 1)))) (SZ2 (((-1 . 1))))) 'COMPLEX) 
(SET*REPRESENTATION 'Z2 '(REALTYPE (ID (((1 . 1)))) (SZ2 (((1 . 1))))) 'REAL) 
(SET*REPRESENTATION 'Z2 '(REALTYPE (ID (((1 . 1)))) (SZ2 (((-1 . 1))))) 'REAL) 
(SET*AVAILABLE 'Z2) 
(SET*ELEMS*GROUP 'K4 '(ID S1K4 S2K4 RK4)) 
(SET*GENERATORS 'K4 '(S1K4 S2K4)) 
(SET*RELATIONS 'K4
               '(((S1K4 S1K4) (ID)) ((S2K4 S2K4) (ID))
                 ((S1K4 S2K4) (S2K4 S1K4)))) 
(SET*GROUPTABLE 'K4
                '((GROUPTABLE ID S1K4 S2K4 RK4) (ID ID S1K4 S2K4 RK4)
                  (S1K4 S1K4 ID RK4 S2K4) (S2K4 S2K4 RK4 ID S1K4)
                  (RK4 RK4 S2K4 S1K4 ID))) 
(SET*INVERSE 'K4 '((ID S1K4 S2K4 RK4) (ID S1K4 S2K4 RK4))) 
(SET*ELEMASGEN 'K4 '(((S1K4) (S1K4)) ((S2K4) (S2K4)) ((RK4) (S1K4 S2K4)))) 
(SET*GROUP 'K4 '((ID) (S1K4) (S2K4) (RK4))) 
(SET*REPRESENTATION 'K4
                    '((ID (((1 . 1)))) (S1K4 (((1 . 1)))) (S2K4 (((1 . 1))))
                      (RK4 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'K4
                    '((ID (((1 . 1)))) (S1K4 (((-1 . 1)))) (S2K4 (((1 . 1))))
                      (RK4 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'K4
                    '((ID (((1 . 1)))) (S1K4 (((1 . 1)))) (S2K4 (((-1 . 1))))
                      (RK4 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'K4
                    '((ID (((1 . 1)))) (S1K4 (((-1 . 1)))) (S2K4 (((-1 . 1))))
                      (RK4 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'K4
                    '(REALTYPE (ID (((1 . 1)))) (S1K4 (((1 . 1))))
                      (S2K4 (((1 . 1)))) (RK4 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'K4
                    '(REALTYPE (ID (((1 . 1)))) (S1K4 (((-1 . 1))))
                      (S2K4 (((1 . 1)))) (RK4 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'K4
                    '(REALTYPE (ID (((1 . 1)))) (S1K4 (((1 . 1))))
                      (S2K4 (((-1 . 1)))) (RK4 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'K4
                    '(REALTYPE (ID (((1 . 1)))) (S1K4 (((-1 . 1))))
                      (S2K4 (((-1 . 1)))) (RK4 (((1 . 1)))))
                    'REAL) 
(SET*AVAILABLE 'K4) 
(SET*ELEMS*GROUP 'D3 '(ID RD3 ROT2D3 SD3 SRD3 SR2D3)) 
(SET*GENERATORS 'D3 '(RD3 SD3)) 
(SET*RELATIONS 'D3
               '(((SD3 SD3) (ID)) ((RD3 RD3 RD3) (ID))
                 ((SD3 RD3 SD3) (RD3 RD3)))) 
(SET*GROUPTABLE 'D3
                '((GROUPTABLE ID RD3 ROT2D3 SD3 SRD3 SR2D3)
                  (ID ID RD3 ROT2D3 SD3 SRD3 SR2D3)
                  (RD3 RD3 ROT2D3 ID SR2D3 SD3 SRD3)
                  (ROT2D3 ROT2D3 ID RD3 SRD3 SR2D3 SD3)
                  (SD3 SD3 SRD3 SR2D3 ID RD3 ROT2D3)
                  (SRD3 SRD3 SR2D3 SD3 ROT2D3 ID RD3)
                  (SR2D3 SR2D3 SD3 SRD3 RD3 ROT2D3 ID))) 
(SET*INVERSE 'D3
             '((ID RD3 ROT2D3 SD3 SRD3 SR2D3) (ID ROT2D3 RD3 SD3 SRD3 SR2D3))) 
(SET*ELEMASGEN 'D3
               '(((RD3) (RD3)) ((ROT2D3) (RD3 RD3)) ((SD3) (SD3))
                 ((SRD3) (SD3 RD3)) ((SR2D3) (SD3 RD3 RD3)))) 
(SET*GROUP 'D3 '((ID) (RD3 ROT2D3) (SR2D3 SD3 SRD3))) 
(SET*REPRESENTATION 'D3
                    '((ID (((1 . 1)))) (RD3 (((1 . 1)))) (ROT2D3 (((1 . 1))))
                      (SD3 (((1 . 1)))) (SRD3 (((1 . 1)))) (SR2D3 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D3
                    '((ID (((1 . 1)))) (RD3 (((1 . 1)))) (ROT2D3 (((1 . 1))))
                      (SD3 (((-1 . 1)))) (SRD3 (((-1 . 1))))
                      (SR2D3 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D3
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (ROT2D3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SD3 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR2D3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D3
                    '(REALTYPE (ID (((1 . 1)))) (RD3 (((1 . 1))))
                      (ROT2D3 (((1 . 1)))) (SD3 (((1 . 1)))) (SRD3 (((1 . 1))))
                      (SR2D3 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D3
                    '(REALTYPE (ID (((1 . 1)))) (RD3 (((1 . 1))))
                      (ROT2D3 (((1 . 1)))) (SD3 (((-1 . 1))))
                      (SRD3 (((-1 . 1)))) (SR2D3 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D3
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (ROT2D3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SD3 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR2D3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2)))))
                    'REAL) 
(SET*AVAILABLE 'D3) 
(SET*ELEMS*GROUP 'D4 '(ID RD4 ROT2D4 ROT3D4 SD4 SRD4 SR2D4 SR3D4)) 
(SET*GENERATORS 'D4 '(RD4 SD4)) 
(SET*RELATIONS 'D4
               '(((SD4 SD4) (ID)) ((RD4 RD4 RD4 RD4) (ID))
                 ((SD4 RD4 SD4) (RD4 RD4 RD4)))) 
(SET*GROUPTABLE 'D4
                '((GROUPTABLE ID RD4 ROT2D4 ROT3D4 SD4 SRD4 SR2D4 SR3D4)
                  (ID ID RD4 ROT2D4 ROT3D4 SD4 SRD4 SR2D4 SR3D4)
                  (RD4 RD4 ROT2D4 ROT3D4 ID SR3D4 SD4 SRD4 SR2D4)
                  (ROT2D4 ROT2D4 ROT3D4 ID RD4 SR2D4 SR3D4 SD4 SRD4)
                  (ROT3D4 ROT3D4 ID RD4 ROT2D4 SRD4 SR2D4 SR3D4 SD4)
                  (SD4 SD4 SRD4 SR2D4 SR3D4 ID RD4 ROT2D4 ROT3D4)
                  (SRD4 SRD4 SR2D4 SR3D4 SD4 ROT3D4 ID RD4 ROT2D4)
                  (SR2D4 SR2D4 SR3D4 SD4 SRD4 ROT2D4 ROT3D4 ID RD4)
                  (SR3D4 SR3D4 SD4 SRD4 SR2D4 RD4 ROT2D4 ROT3D4 ID))) 
(SET*INVERSE 'D4
             '((ID RD4 ROT2D4 ROT3D4 SD4 SRD4 SR2D4 SR3D4)
               (ID ROT3D4 ROT2D4 RD4 SD4 SRD4 SR2D4 SR3D4))) 
(SET*ELEMASGEN 'D4
               '(((RD4) (RD4)) ((ROT2D4) (RD4 RD4)) ((ROT3D4) (RD4 RD4 RD4))
                 ((SD4) (SD4)) ((SRD4) (SD4 RD4)) ((SR2D4) (SD4 RD4 RD4))
                 ((SR3D4) (SD4 RD4 RD4 RD4)))) 
(SET*GROUP 'D4 '((ID) (RD4 ROT3D4) (ROT2D4) (SD4 SR2D4) (SR3D4 SRD4))) 
(SET*REPRESENTATION 'D4
                    '((ID (((1 . 1)))) (RD4 (((1 . 1)))) (ROT2D4 (((1 . 1))))
                      (ROT3D4 (((1 . 1)))) (SD4 (((1 . 1)))) (SRD4 (((1 . 1))))
                      (SR2D4 (((1 . 1)))) (SR3D4 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D4
                    '((ID (((1 . 1)))) (RD4 (((1 . 1)))) (ROT2D4 (((1 . 1))))
                      (ROT3D4 (((1 . 1)))) (SD4 (((-1 . 1))))
                      (SRD4 (((-1 . 1)))) (SR2D4 (((-1 . 1))))
                      (SR3D4 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D4
                    '((ID (((1 . 1)))) (RD4 (((-1 . 1)))) (ROT2D4 (((1 . 1))))
                      (ROT3D4 (((-1 . 1)))) (SD4 (((1 . 1))))
                      (SRD4 (((-1 . 1)))) (SR2D4 (((1 . 1))))
                      (SR3D4 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D4
                    '((ID (((1 . 1)))) (RD4 (((-1 . 1)))) (ROT2D4 (((1 . 1))))
                      (ROT3D4 (((-1 . 1)))) (SD4 (((-1 . 1))))
                      (SRD4 (((1 . 1)))) (SR2D4 (((-1 . 1))))
                      (SR3D4 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D4
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD4 (((NIL . 1) (1 . 1)) ((-1 . 1) (NIL . 1))))
                      (ROT2D4 (((-1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (ROT3D4 (((NIL . 1) (-1 . 1)) ((1 . 1) (NIL . 1))))
                      (SD4 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD4 (((NIL . 1) (1 . 1)) ((1 . 1) (NIL . 1))))
                      (SR2D4 (((-1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (SR3D4 (((NIL . 1) (-1 . 1)) ((-1 . 1) (NIL . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D4
                    '(REALTYPE (ID (((1 . 1)))) (RD4 (((1 . 1))))
                      (ROT2D4 (((1 . 1)))) (ROT3D4 (((1 . 1))))
                      (SD4 (((1 . 1)))) (SRD4 (((1 . 1)))) (SR2D4 (((1 . 1))))
                      (SR3D4 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D4
                    '(REALTYPE (ID (((1 . 1)))) (RD4 (((1 . 1))))
                      (ROT2D4 (((1 . 1)))) (ROT3D4 (((1 . 1))))
                      (SD4 (((-1 . 1)))) (SRD4 (((-1 . 1))))
                      (SR2D4 (((-1 . 1)))) (SR3D4 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D4
                    '(REALTYPE (ID (((1 . 1)))) (RD4 (((-1 . 1))))
                      (ROT2D4 (((1 . 1)))) (ROT3D4 (((-1 . 1))))
                      (SD4 (((1 . 1)))) (SRD4 (((-1 . 1)))) (SR2D4 (((1 . 1))))
                      (SR3D4 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D4
                    '(REALTYPE (ID (((1 . 1)))) (RD4 (((-1 . 1))))
                      (ROT2D4 (((1 . 1)))) (ROT3D4 (((-1 . 1))))
                      (SD4 (((-1 . 1)))) (SRD4 (((1 . 1))))
                      (SR2D4 (((-1 . 1)))) (SR3D4 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D4
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD4 (((NIL . 1) (1 . 1)) ((-1 . 1) (NIL . 1))))
                      (ROT2D4 (((-1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (ROT3D4 (((NIL . 1) (-1 . 1)) ((1 . 1) (NIL . 1))))
                      (SD4 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD4 (((NIL . 1) (1 . 1)) ((1 . 1) (NIL . 1))))
                      (SR2D4 (((-1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (SR3D4 (((NIL . 1) (-1 . 1)) ((-1 . 1) (NIL . 1)))))
                    'REAL) 
(SET*AVAILABLE 'D4) 
(SET*ELEMS*GROUP 'D5 '(ID RD5 R2D5 R3D5 R4D5 SD5 SRD5 SR2D5 SR3D5 SR4D5)) 
(SET*GENERATORS 'D5 '(RD5 SD5)) 
(SET*RELATIONS 'D5
               '(((SD5 SD5) (ID)) ((RD5 RD5 RD5 RD5 RD5) (ID))
                 ((SD5 RD5 SD5) (RD5 RD5 RD5 RD5)))) 
(SET*GROUPTABLE 'D5
                '((GROUPTABLE ID RD5 R2D5 R3D5 R4D5 SD5 SRD5 SR2D5 SR3D5 SR4D5)
                  (ID ID RD5 R2D5 R3D5 R4D5 SD5 SRD5 SR2D5 SR3D5 SR4D5)
                  (RD5 RD5 R2D5 R3D5 R4D5 ID SR4D5 SD5 SRD5 SR2D5 SR3D5)
                  (R2D5 R2D5 R3D5 R4D5 ID RD5 SR3D5 SR4D5 SD5 SRD5 SR2D5)
                  (R3D5 R3D5 R4D5 ID RD5 R2D5 SR2D5 SR3D5 SR4D5 SD5 SRD5)
                  (R4D5 R4D5 ID RD5 R2D5 R3D5 SRD5 SR2D5 SR3D5 SR4D5 SD5)
                  (SD5 SD5 SRD5 SR2D5 SR3D5 SR4D5 ID RD5 R2D5 R3D5 R4D5)
                  (SRD5 SRD5 SR2D5 SR3D5 SR4D5 SD5 R4D5 ID RD5 R2D5 R3D5)
                  (SR2D5 SR2D5 SR3D5 SR4D5 SD5 SRD5 R3D5 R4D5 ID RD5 R2D5)
                  (SR3D5 SR3D5 SR4D5 SD5 SRD5 SR2D5 R2D5 R3D5 R4D5 ID RD5)
                  (SR4D5 SR4D5 SD5 SRD5 SR2D5 SR3D5 RD5 R2D5 R3D5 R4D5 ID))) 
(SET*INVERSE 'D5
             '((ID RD5 R2D5 R3D5 R4D5 SD5 SRD5 SR2D5 SR3D5 SR4D5)
               (ID R4D5 R3D5 R2D5 RD5 SD5 SRD5 SR2D5 SR3D5 SR4D5))) 
(SET*ELEMASGEN 'D5
               '(((RD5) (RD5)) ((R2D5) (RD5 RD5)) ((R3D5) (RD5 RD5 RD5))
                 ((R4D5) (RD5 RD5 RD5 RD5)) ((SD5) (SD5)) ((SRD5) (SD5 RD5))
                 ((SR2D5) (SD5 RD5 RD5)) ((SR3D5) (SD5 RD5 RD5 RD5))
                 ((SR4D5) (SD5 RD5 RD5 RD5 RD5)))) 
(SET*GROUP 'D5 '((ID) (RD5 R4D5) (R2D5 R3D5) (SRD5 SR2D5 SD5 SR4D5 SR3D5))) 
(SET*REPRESENTATION 'D5
                    '((ID (((1 . 1)))) (RD5 (((1 . 1)))) (R2D5 (((1 . 1))))
                      (R3D5 (((1 . 1)))) (R4D5 (((1 . 1)))) (SD5 (((1 . 1))))
                      (SRD5 (((1 . 1)))) (SR2D5 (((1 . 1))))
                      (SR3D5 (((1 . 1)))) (SR4D5 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D5
                    '((ID (((1 . 1)))) (RD5 (((1 . 1)))) (R2D5 (((1 . 1))))
                      (R3D5 (((1 . 1)))) (R4D5 (((1 . 1)))) (SD5 (((-1 . 1))))
                      (SRD5 (((-1 . 1)))) (SR2D5 (((-1 . 1))))
                      (SR3D5 (((-1 . 1)))) (SR4D5 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D5
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD5
                       (((((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1))))
                      (R2D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1))))
                      (SD5 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD5
                       (((((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1)
                         (((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1))
                          . 1))))
                      (SR2D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1))
                          . 1))))
                      (SR3D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -1))
                          . 1))))
                      (SR4D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . -1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D5
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD5
                       (((((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1))))
                      (R2D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1))))
                      (SD5 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD5
                       (((((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1)
                         (((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1))
                          . 1))))
                      (SR2D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1))
                          . 1))))
                      (SR3D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -1))
                          . 1))))
                      (SR4D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . -1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D5
                    '(REALTYPE (ID (((1 . 1)))) (RD5 (((1 . 1))))
                      (R2D5 (((1 . 1)))) (R3D5 (((1 . 1)))) (R4D5 (((1 . 1))))
                      (SD5 (((1 . 1)))) (SRD5 (((1 . 1)))) (SR2D5 (((1 . 1))))
                      (SR3D5 (((1 . 1)))) (SR4D5 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D5
                    '(REALTYPE (ID (((1 . 1)))) (RD5 (((1 . 1))))
                      (R2D5 (((1 . 1)))) (R3D5 (((1 . 1)))) (R4D5 (((1 . 1))))
                      (SD5 (((-1 . 1)))) (SRD5 (((-1 . 1))))
                      (SR2D5 (((-1 . 1)))) (SR3D5 (((-1 . 1))))
                      (SR4D5 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D5
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD5
                       (((((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1))))
                      (R2D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1))))
                      (SD5 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD5
                       (((((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1)
                         (((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1))
                          . 1))))
                      (SR2D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1))
                          . 1))))
                      (SR3D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -1))
                          . 1))))
                      (SR4D5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . -1))
                          . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D5
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD5
                       (((((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1))))
                      (R2D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1))))
                      (SD5 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD5
                       (((((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1)
                         (((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1))
                          . 1))))
                      (SR2D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1))
                          . 1))))
                      (SR3D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -1))
                          . 1))))
                      (SR4D5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . -1))
                          . 1)))))
                    'REAL) 
(SET*AVAILABLE 'D5) 
(SET*ELEMS*GROUP 'D6
                 '(ID RD6 R2D6 R3D6 R4D6 R5D6 SD6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6)) 
(SET*GENERATORS 'D6 '(RD6 SD6)) 
(SET*RELATIONS 'D6
               '(((SD6 SD6) (ID)) ((RD6 RD6 RD6 RD6 RD6 RD6) (ID))
                 ((SD6 RD6 SD6) (RD6 RD6 RD6 RD6 RD6)))) 
(SET*GROUPTABLE 'D6
                '((GROUPTABLE ID RD6 R2D6 R3D6 R4D6 R5D6 SD6 SRD6 SR2D6 SR3D6
                   SR4D6 SR5D6)
                  (ID ID RD6 R2D6 R3D6 R4D6 R5D6 SD6 SRD6 SR2D6 SR3D6 SR4D6
                   SR5D6)
                  (RD6 RD6 R2D6 R3D6 R4D6 R5D6 ID SR5D6 SD6 SRD6 SR2D6 SR3D6
                   SR4D6)
                  (R2D6 R2D6 R3D6 R4D6 R5D6 ID RD6 SR4D6 SR5D6 SD6 SRD6 SR2D6
                   SR3D6)
                  (R3D6 R3D6 R4D6 R5D6 ID RD6 R2D6 SR3D6 SR4D6 SR5D6 SD6 SRD6
                   SR2D6)
                  (R4D6 R4D6 R5D6 ID RD6 R2D6 R3D6 SR2D6 SR3D6 SR4D6 SR5D6 SD6
                   SRD6)
                  (R5D6 R5D6 ID RD6 R2D6 R3D6 R4D6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6
                   SD6)
                  (SD6 SD6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6 ID RD6 R2D6 R3D6 R4D6
                   R5D6)
                  (SRD6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6 SD6 R5D6 ID RD6 R2D6 R3D6
                   R4D6)
                  (SR2D6 SR2D6 SR3D6 SR4D6 SR5D6 SD6 SRD6 R4D6 R5D6 ID RD6 R2D6
                   R3D6)
                  (SR3D6 SR3D6 SR4D6 SR5D6 SD6 SRD6 SR2D6 R3D6 R4D6 R5D6 ID RD6
                   R2D6)
                  (SR4D6 SR4D6 SR5D6 SD6 SRD6 SR2D6 SR3D6 R2D6 R3D6 R4D6 R5D6
                   ID RD6)
                  (SR5D6 SR5D6 SD6 SRD6 SR2D6 SR3D6 SR4D6 RD6 R2D6 R3D6 R4D6
                   R5D6 ID))) 
(SET*INVERSE 'D6
             '((ID RD6 R2D6 R3D6 R4D6 R5D6 SD6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6)
               (ID R5D6 R4D6 R3D6 R2D6 RD6 SD6 SRD6 SR2D6 SR3D6 SR4D6 SR5D6))) 
(SET*ELEMASGEN 'D6
               '(((RD6) (RD6)) ((R2D6) (RD6 RD6)) ((R3D6) (RD6 RD6 RD6))
                 ((R4D6) (RD6 RD6 RD6 RD6)) ((R5D6) (RD6 RD6 RD6 RD6 RD6))
                 ((SD6) (SD6)) ((SRD6) (SD6 RD6)) ((SR2D6) (SD6 RD6 RD6))
                 ((SR3D6) (SD6 RD6 RD6 RD6)) ((SR4D6) (SD6 RD6 RD6 RD6 RD6))
                 ((SR5D6) (SD6 RD6 RD6 RD6 RD6 RD6)))) 
(SET*GROUP 'D6
           '((ID) (RD6 R5D6) (R2D6 R4D6) (R3D6) (SR2D6 SD6 SR4D6)
             (SRD6 SR5D6 SR3D6))) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1)))) (RD6 (((1 . 1)))) (R2D6 (((1 . 1))))
                      (R3D6 (((1 . 1)))) (R4D6 (((1 . 1)))) (R5D6 (((1 . 1))))
                      (SD6 (((1 . 1)))) (SRD6 (((1 . 1)))) (SR2D6 (((1 . 1))))
                      (SR3D6 (((1 . 1)))) (SR4D6 (((1 . 1))))
                      (SR5D6 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1)))) (RD6 (((1 . 1)))) (R2D6 (((1 . 1))))
                      (R3D6 (((1 . 1)))) (R4D6 (((1 . 1)))) (R5D6 (((1 . 1))))
                      (SD6 (((-1 . 1)))) (SRD6 (((-1 . 1))))
                      (SR2D6 (((-1 . 1)))) (SR3D6 (((-1 . 1))))
                      (SR4D6 (((-1 . 1)))) (SR5D6 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1)))) (RD6 (((-1 . 1)))) (R2D6 (((1 . 1))))
                      (R3D6 (((-1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((-1 . 1)))) (SD6 (((1 . 1)))) (SRD6 (((-1 . 1))))
                      (SR2D6 (((1 . 1)))) (SR3D6 (((-1 . 1))))
                      (SR4D6 (((1 . 1)))) (SR5D6 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1)))) (RD6 (((-1 . 1)))) (R2D6 (((1 . 1))))
                      (R3D6 (((-1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((-1 . 1)))) (SD6 (((-1 . 1)))) (SRD6 (((1 . 1))))
                      (SR2D6 (((-1 . 1)))) (SR3D6 (((1 . 1))))
                      (SR4D6 (((-1 . 1)))) (SR5D6 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (R2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R3D6 (((-1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (R4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (R5D6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SD6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SR2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR3D6 (((-1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (SR4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (SR5D6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '((ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (R3D6 (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (R4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R5D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SD6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (SR3D6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SR4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR5D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1)))) (RD6 (((1 . 1))))
                      (R2D6 (((1 . 1)))) (R3D6 (((1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((1 . 1)))) (SD6 (((1 . 1)))) (SRD6 (((1 . 1))))
                      (SR2D6 (((1 . 1)))) (SR3D6 (((1 . 1))))
                      (SR4D6 (((1 . 1)))) (SR5D6 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1)))) (RD6 (((1 . 1))))
                      (R2D6 (((1 . 1)))) (R3D6 (((1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((1 . 1)))) (SD6 (((-1 . 1)))) (SRD6 (((-1 . 1))))
                      (SR2D6 (((-1 . 1)))) (SR3D6 (((-1 . 1))))
                      (SR4D6 (((-1 . 1)))) (SR5D6 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1)))) (RD6 (((-1 . 1))))
                      (R2D6 (((1 . 1)))) (R3D6 (((-1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((-1 . 1)))) (SD6 (((1 . 1)))) (SRD6 (((-1 . 1))))
                      (SR2D6 (((1 . 1)))) (SR3D6 (((-1 . 1))))
                      (SR4D6 (((1 . 1)))) (SR5D6 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1)))) (RD6 (((-1 . 1))))
                      (R2D6 (((1 . 1)))) (R3D6 (((-1 . 1)))) (R4D6 (((1 . 1))))
                      (R5D6 (((-1 . 1)))) (SD6 (((-1 . 1)))) (SRD6 (((1 . 1))))
                      (SR2D6 (((-1 . 1)))) (SR3D6 (((1 . 1))))
                      (SR4D6 (((-1 . 1)))) (SR5D6 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (R2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R3D6 (((-1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (R4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (R5D6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SD6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SR2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR3D6 (((-1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (SR4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (SR5D6
                       (((1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2)))))
                    'REAL) 
(SET*REPRESENTATION 'D6
                    '(REALTYPE (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RD6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (R3D6 (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (R4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2))))
                      (R5D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (SD6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SRD6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR2D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2))))
                      (SR3D6 (((1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (SR4D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2) (1 . 2))))
                      (SR5D6
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (1 . 2)))))
                    'REAL) 
(SET*AVAILABLE 'D6) 
(SET*ELEMS*GROUP 'C3 '(ID RC3 R2C3)) 
(SET*GENERATORS 'C3 '(RC3)) 
(SET*RELATIONS 'C3 '(((RC3 RC3 RC3) (ID)))) 
(SET*GROUPTABLE 'C3
                '((GROUPTABLE ID RC3 R2C3) (ID ID RC3 R2C3) (RC3 RC3 R2C3 ID)
                  (R2C3 R2C3 ID RC3))) 
(SET*INVERSE 'C3 '((ID RC3 R2C3) (ID R2C3 RC3))) 
(SET*ELEMASGEN 'C3 '(((RC3) (RC3)) ((R2C3) (RC3 RC3)))) 
(SET*GROUP 'C3 '((ID) (RC3) (R2C3))) 
(SET*REPRESENTATION 'C3
                    '((ID (((1 . 1)))) (RC3 (((1 . 1)))) (R2C3 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C3
                    '((ID (((1 . 1))))
                      (RC3
                       (((((((EXPT 3 (QUOTIENT 1 2)) . 1) ((I . 1) . 1)) . -1)
                          . 2))))
                      (R2C3
                       (((((((EXPT 3 (QUOTIENT 1 2)) . 1) ((I . 1) . -1)) . -1)
                          . 2)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C3
                    '((ID (((1 . 1))))
                      (RC3
                       (((((((EXPT 3 (QUOTIENT 1 2)) . 1) ((I . 1) . -1)) . -1)
                          . 2))))
                      (R2C3
                       (((((((EXPT 3 (QUOTIENT 1 2)) . 1) ((I . 1) . 1)) . -1)
                          . 2)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C3
                    '(REALTYPE (ID (((1 . 1)))) (RC3 (((1 . 1))))
                      (R2C3 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'C3
                    '(COMPLEXTYPE
                      (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RC3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2)
                         (-1 . 2))))
                      (R2C3
                       (((-1 . 2) (((((EXPT 3 (QUOTIENT 1 2)) . 1) . 1)) . 2))
                        ((((((EXPT 3 (QUOTIENT 1 2)) . 1) . -1)) . 2)
                         (-1 . 2)))))
                    'REAL) 
(SET*AVAILABLE 'C3) 
(SET*ELEMS*GROUP 'C4 '(ID RC4 R2C4 R3C4)) 
(SET*GENERATORS 'C4 '(RC4)) 
(SET*RELATIONS 'C4 '(((RC4 RC4 RC4 RC4) (ID)))) 
(SET*GROUPTABLE 'C4
                '((GROUPTABLE ID RC4 R2C4 R3C4) (ID ID RC4 R2C4 R3C4)
                  (RC4 RC4 R2C4 R3C4 ID) (R2C4 R2C4 R3C4 ID RC4)
                  (R3C4 R3C4 ID RC4 R2C4))) 
(SET*INVERSE 'C4 '((ID RC4 R2C4 R3C4) (ID R3C4 R2C4 RC4))) 
(SET*ELEMASGEN 'C4 '(((RC4) (RC4)) ((R2C4) (RC4 RC4)) ((R3C4) (RC4 RC4 RC4)))) 
(SET*GROUP 'C4 '((ID) (RC4) (R2C4) (R3C4))) 
(SET*REPRESENTATION 'C4
                    '((ID (((1 . 1)))) (RC4 (((1 . 1)))) (R2C4 (((1 . 1))))
                      (R3C4 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C4
                    '((ID (((1 . 1)))) (RC4 (((-1 . 1)))) (R2C4 (((1 . 1))))
                      (R3C4 (((-1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C4
                    '((ID (((1 . 1)))) (RC4 ((((((I . 1) . 1)) . 1))))
                      (R2C4 (((-1 . 1)))) (R3C4 ((((((I . 1) . -1)) . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C4
                    '((ID (((1 . 1)))) (RC4 ((((((I . 1) . -1)) . 1))))
                      (R2C4 (((-1 . 1)))) (R3C4 ((((((I . 1) . 1)) . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C4
                    '(REALTYPE (ID (((1 . 1)))) (RC4 (((1 . 1))))
                      (R2C4 (((1 . 1)))) (R3C4 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'C4
                    '(REALTYPE (ID (((1 . 1)))) (RC4 (((-1 . 1))))
                      (R2C4 (((1 . 1)))) (R3C4 (((-1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'C4
                    '(COMPLEXTYPE
                      (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RC4 (((NIL . 1) (-1 . 1)) ((1 . 1) (NIL . 1))))
                      (R2C4 (((-1 . 1) (NIL . 1)) ((NIL . 1) (-1 . 1))))
                      (R3C4 (((NIL . 1) (1 . 1)) ((-1 . 1) (NIL . 1)))))
                    'REAL) 
(SET*AVAILABLE 'C4) 
(SET*ELEMS*GROUP 'C5 '(ID RC5 R2C5 R3C5 R4C5)) 
(SET*GENERATORS 'C5 '(RC5)) 
(SET*RELATIONS 'C5 '(((RC5 RC5 RC5 RC5 RC5) (ID)))) 
(SET*GROUPTABLE 'C5
                '((GROUPTABLE ID RC5 R2C5 R3C5 R4C5) (ID ID RC5 R2C5 R3C5 R4C5)
                  (RC5 RC5 R2C5 R3C5 R4C5 ID) (R2C5 R2C5 R3C5 R4C5 ID RC5)
                  (R3C5 R3C5 R4C5 ID RC5 R2C5) (R4C5 R4C5 ID RC5 R2C5 R3C5))) 
(SET*INVERSE 'C5 '((ID RC5 R2C5 R3C5 R4C5) (ID R4C5 R3C5 R2C5 RC5))) 
(SET*ELEMASGEN 'C5
               '(((RC5) (RC5)) ((R2C5) (RC5 RC5)) ((R3C5) (RC5 RC5 RC5))
                 ((R4C5) (RC5 RC5 RC5 RC5)))) 
(SET*GROUP 'C5 '((ID) (RC5) (R2C5) (R3C5) (R4C5))) 
(SET*REPRESENTATION 'C5
                    '((ID (((1 . 1)))) (RC5 (((1 . 1)))) (R2C5 (((1 . 1))))
                      (R3C5 (((1 . 1)))) (R4C5 (((1 . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C5
                    '((ID (((1 . 1))))
                      (RC5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            ((I . 1) . 1))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1))
                          . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1)
                             ((I . 1) . 2)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            ((I . 1) . -1))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2)
                             ((I . 1) . 3)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1)
                             ((I . 1) . -4)))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3)
                             ((I . 1) . 4)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C5
                    '((ID (((1 . 1))))
                      (RC5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            ((I . 1) . 1))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1))
                          . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1)
                             ((I . 1) . 2)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            ((I . 1) . -1))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2)
                             ((I . 1) . 3)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1)
                             ((I . 1) . -4)))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3)
                             ((I . 1) . 4)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C5
                    '((ID (((1 . 1))))
                      (RC5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            ((I . 1) . -1))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1))
                          . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1)
                             ((I . 1) . -2)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            ((I . 1) . 1))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2)
                             ((I . 1) . -3)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1)
                             ((I . 1) . 4)))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3)
                             ((I . 1) . -4)))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C5
                    '((ID (((1 . 1))))
                      (RC5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            ((I . 1) . -1))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1))
                          . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1)
                             ((I . 1) . -2)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            ((I . 1) . 1))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2)
                             ((I . 1) . -3)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1)
                             ((I . 1) . 4)))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3)
                             ((I . 1) . -4)))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)))))
                    'COMPLEX) 
(SET*REPRESENTATION 'C5
                    '(REALTYPE (ID (((1 . 1)))) (RC5 (((1 . 1))))
                      (R2C5 (((1 . 1)))) (R3C5 (((1 . 1)))) (R4C5 (((1 . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'C5
                    '(COMPLEXTYPE
                      (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RC5
                       (((((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 1)) . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 2 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 2 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 2 PI) 5)) . 4) . 1))
                          . 1)))))
                    'REAL) 
(SET*REPRESENTATION 'C5
                    '(COMPLEXTYPE
                      (ID (((1 . 1) (NIL . 1)) ((NIL . 1) (1 . 1))))
                      (RC5
                       (((((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . -1)) . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1)
                         (((((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 1)) . 1))))
                      (R2C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -2)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 2)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2) . -1)
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 1))
                          . 1))))
                      (R3C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -3)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3) . -1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . 3)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -3))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 1))
                          . 1))))
                      (R4C5
                       (((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . 4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . -4)))
                          . 1))
                        ((((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 3)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 1) . -4))
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 1)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 3) . 4)))
                          . 1)
                         (((((SIN (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1)
                           (((SIN (QUOTIENT (TIMES 4 PI) 5)) . 2)
                            (((COS (QUOTIENT (TIMES 4 PI) 5)) . 2) . -6))
                           (((COS (QUOTIENT (TIMES 4 PI) 5)) . 4) . 1))
                          . 1)))))
                    'REAL) 
(SET*AVAILABLE 'C5) 
(ENDMODULE) 