(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'TOWER)) 
(FLUID '(*PROTFG CURR_PCKG*)) 
(SETQ *ARGNOCHK NIL) 
(PUT 'TYPE_REDUCE 'NUMBER-OF-ARGS 2) 
(PUT 'TYPE_REDUCE 'DEFINED-ON-LINE '32) 
(PUT 'TYPE_REDUCE 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_REDUCE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE TYPE_REDUCE (U V) (TYPE_REDUCE1 (LIST V U))) 
(PUT 'TYPE_REDUCE2 'NUMBER-OF-ARGS 3) 
(PUT 'TYPE_REDUCE2 'DEFINED-ON-LINE '37) 
(PUT 'TYPE_REDUCE2 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_REDUCE2 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE TYPE_REDUCE2 (U V W)
    (COND ((NULL W) (MKOBJECT U V)) ((NULL (CDR W)) (TYPE_REDUCE U (CAR W)))
          (T
           ((LAMBDA (X)
              (COND ((AND X (SETQ X (APPLY2 X U V))) (TYPE_REDUCE X (CAR W)))
                    (T (TYPE_REDUCE2 U V (CDR W)))))
            (AND (TYPE_IN_PCKGP (CAR W)) (GET (CAR W) 'BOOLFN)))))) 
(PUT 'DELRELATEDTYPE 'NUMBER-OF-ARGS 2) 
(PUT 'DELRELATEDTYPE 'DEFINED-ON-LINE '45) 
(PUT 'DELRELATEDTYPE 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'DELRELATEDTYPE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE DELRELATEDTYPE (U V)
    (COND ((NULL V) NIL) ((XTYPE1 (CAR V) U) (CDR V))
          (T (CONS (CAR V) (DELRELATEDTYPE U (CDR V)))))) 
(PUT 'TYPE_REDUCE5 'NUMBER-OF-ARGS 1) 
(PUT 'TYPE_REDUCE5 'DEFINED-ON-LINE '50) 
(PUT 'TYPE_REDUCE5 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_REDUCE5 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE TYPE_REDUCE5 (U)
    (PROG (X Y Z *PROTFG)
      (SETQ *PROTFG T)
      (COND ((NULL (SETQ X (GET (TYPE U) '*NULLARY*))) (RETURN U)))
      (SETQ Z (GET (TYPE U) 'TYPETREE))
     A
      (COND ((NULL X) (RETURN (MKOBJECT (VALUE U) (CAR Z)))))
      (COND
       ((AND
         (NULL
          (ERRORP
           (SETQ Y (ERRORSET (LIST 'APPLY1 (MKQUOTE X) (MKQUOTE U)) NIL NIL))))
         (CAR Y))
        (PROGN (SETQ X (APPLY1 (CAAR Y) U)) (RETURN (TYPE_REDUCE1 X)))))
      (PROG (J)
        (SETQ J (CDADDR X))
       LAB
        (COND ((NULL J) (RETURN NIL)))
        ((LAMBDA (J) (SETQ Z (DELRELATEDTYPE (CADR (CADADR J)) Z))) (CAR J))
        (SETQ J (CDR J))
        (GO LAB))
      (RETURN (COND ((NULL Z) U) (T (MKOBJECT (VALUE U) (CAR Z)))))
      (GO A))) 
(PUT 'TYPE_REDUCE1 'NUMBER-OF-ARGS 1) 
(PUT 'TYPE_REDUCE1 'DEFINED-ON-LINE '66) 
(PUT 'TYPE_REDUCE1 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_REDUCE1 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE TYPE_REDUCE1 (U)
    (PROG (X Y)
      (COND
       ((OR (NULL (TYPE_IN_PCKGP (TYPE U)))
            (NULL (SETQ X (GET (TYPE U) '*NULLARY*))))
        (RETURN U)))
      (COND
       ((SETQ Y (APPLY1 X U))
        (PROGN (SETQ X (APPLY1 (CAR Y) U)) (RETURN (TYPE_REDUCE1 X)))))
      (RETURN U))) 
(PUT 'TYPE_FUNCTION 'NUMBER-OF-ARGS 3) 
(PUT 'TYPE_FUNCTION 'DEFINED-ON-LINE '78) 
(PUT 'TYPE_FUNCTION 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_FUNCTION 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE TYPE_FUNCTION (FN TYPELIST ARGS)
    (PROG (X)
      (RETURN
       (COND
        ((AND (SETQ X (GET FN 'RANKS)) (SETQ X (ASSOC (LENGTH TYPELIST) X))
              (SETQ X (TYPE_ASSOC TYPELIST (CDR X) ARGS)))
         X)
        (T NIL))))) 
(PUT 'TYPE_ASSOC 'NUMBER-OF-ARGS 3) 
(PUT 'TYPE_ASSOC 'DEFINED-ON-LINE '87) 
(PUT 'TYPE_ASSOC 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_ASSOC 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE TYPE_ASSOC (TYPELIST TYPE_ASSOC_LIST ARGS)
    (PROG (X)
      (COND
       ((SETQ X
                (TYPE_ASSOC1 (CAR TYPELIST) (CDR TYPELIST) TYPE_ASSOC_LIST
                 ARGS))
        (RETURN X))
       ((SETQ X (ATSOC 'GENERIC TYPE_ASSOC_LIST)) (RETURN (CDR X)))
       (T (RETURN NIL))))) 
(PUT 'TYPE_ASSOC1 'NUMBER-OF-ARGS 4) 
(PUT 'TYPE_ASSOC1 'DEFINED-ON-LINE '97) 
(PUT 'TYPE_ASSOC1 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_ASSOC1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE TYPE_ASSOC1 (TYPE TYPELIST TYPE_ASSOC_LIST ARGS)
    (PROG (X Y Z)
      (COND
       ((AND (TYPE_IN_PCKGP TYPE) (SETQ X (TYPE_ASSOC0 TYPE TYPE_ASSOC_LIST)))
        (COND
         ((NULL TYPELIST)
          (RETURN
           (PCKG_OP_CHK
            (COND
             ((ATOM (CADR X))
              (COND ((ATOM (CADDR X)) (CDR X))
                    ((SETQ Z (CONSTRAINT_APPLY (CDR X) ARGS)) Z) (T NIL)))))))
         ((SETQ Y (TYPE_ASSOC1 (CAR TYPELIST) (CDR TYPELIST) (CDR X) ARGS))
          (RETURN Y)))))
      (COND
       ((SETQ Z (GET TYPE 'UPTREE))
        (PROGN
         (PROG ()
          WHILELABEL
           (COND
            ((NOT
              (AND Z
                   (NOT
                    (SETQ X
                            (TYPE_ASSOC1 (CAR Z) TYPELIST TYPE_ASSOC_LIST
                             ARGS)))))
             (RETURN NIL)))
           (SETQ Z (CDR Z))
           (GO WHILELABEL))
         (RETURN X)))
       (T (RETURN NIL))))) 
(PUT 'CONSTRAINT_APPLY 'NUMBER-OF-ARGS 2) 
(PUT 'CONSTRAINT_APPLY 'DEFINED-ON-LINE '118) 
(PUT 'CONSTRAINT_APPLY 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'CONSTRAINT_APPLY 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE CONSTRAINT_APPLY (U V) (APPLY U V)) 
(PUT 'TYPE_ASSOC0 'NUMBER-OF-ARGS 2) 
(PUT 'TYPE_ASSOC0 'DEFINED-ON-LINE '121) 
(PUT 'TYPE_ASSOC0 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'TYPE_ASSOC0 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE TYPE_ASSOC0 (TYPE TYPE_ASSOC_LIST) (ASSOC TYPE TYPE_ASSOC_LIST)) 
(PUT 'CHECK_TYPE 'NUMBER-OF-ARGS 2) 
(PUT 'CHECK_TYPE 'DEFINED-ON-LINE '125) 
(PUT 'CHECK_TYPE 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'CHECK_TYPE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE CHECK_TYPE (U T_TYPE)
    (COND ((XTYPE1 (TYPE U) T_TYPE) U)
          (T
           (REDERR
            (LIST "Ceiling target type" T_TYPE "is unrelated to result type"
                  (TYPE U)))))) 
(PUT 'GET_DISAMBOP 'NUMBER-OF-ARGS 3) 
(PUT 'GET_DISAMBOP 'DEFINED-ON-LINE '133) 
(PUT 'GET_DISAMBOP 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'GET_DISAMBOP 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE GET_DISAMBOP (NAME ARITY COARITY)
    (PROG (X)
      (RETURN
       (COND
        ((AND (SETQ X (GET NAME 'RANKS)) (SETQ X (ASSOC (LENGTH ARITY) X))
              (SETQ X (DISAMBOP_ASSOC ARITY (CDR X) COARITY)))
         X)
        (T NIL))))) 
(PUT 'DISAMBOP_ASSOC 'NUMBER-OF-ARGS 3) 
(PUT 'DISAMBOP_ASSOC 'DEFINED-ON-LINE '142) 
(PUT 'DISAMBOP_ASSOC 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'DISAMBOP_ASSOC 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE DISAMBOP_ASSOC (TYPELIST TYPE_ASSOC_LIST COARITY)
    (PROG (X)
      (COND
       ((SETQ X
                (DISAMBOP_ASSOC1 (CAR TYPELIST) (CDR TYPELIST) TYPE_ASSOC_LIST
                 COARITY))
        (RETURN X))
       ((SETQ X (ATSOC 'GENERIC TYPE_ASSOC_LIST)) (RETURN (CDR X)))
       (T (RETURN NIL))))) 
(PUT 'DISAMBOP_ASSOC1 'NUMBER-OF-ARGS 4) 
(PUT 'DISAMBOP_ASSOC1 'DEFINED-ON-LINE '152) 
(PUT 'DISAMBOP_ASSOC1 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'DISAMBOP_ASSOC1 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL GENERAL) GENERAL)) 
(DE DISAMBOP_ASSOC1 (TYPE TYPELIST TYPE_ASSOC_LIST COARITY)
    (PROG (X Y Z)
      (COND
       ((AND (TYPE_IN_PCKGP TYPE) (SETQ X (ASSOC TYPE TYPE_ASSOC_LIST)))
        (COND
         ((NULL TYPELIST)
          (RETURN
           (PCKG_OP_CHK
            (COND ((SETQ Z (ASSOC_COARITY COARITY (CDR (CADDDR X)))) Z)
                  (T NIL)))))
         ((SETQ Y
                  (DISAMBOP_ASSOC1 (CAR TYPELIST) (CDR TYPELIST) (CDR X)
                   COARITY))
          (RETURN Y)))))
      (COND
       ((SETQ Z (GET TYPE 'UPTREE))
        (PROGN
         (PROG ()
          WHILELABEL
           (COND
            ((NOT
              (AND Z
                   (NOT
                    (SETQ X
                            (DISAMBOP_ASSOC1 (CAR Z) TYPELIST TYPE_ASSOC_LIST
                             COARITY)))))
             (RETURN NIL)))
           (SETQ Z (CDR Z))
           (GO WHILELABEL))
         (RETURN X)))
       (T (RETURN NIL))))) 
(PUT 'ASSOC_COARITY 'NUMBER-OF-ARGS 2) 
(PUT 'ASSOC_COARITY 'DEFINED-ON-LINE '174) 
(PUT 'ASSOC_COARITY 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'ASSOC_COARITY 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE ASSOC_COARITY (COARITY U)
    (PROG ()
     A
      (COND ((NULL U) (RETURN NIL)))
      (COND ((EQ (CADAR (CDADAR U)) COARITY) (RETURN (CAAR (CDADAR U)))))
      (SETQ U (CDR U))
      (GO A))) 
(PUT 'COERCABLE 'NUMBER-OF-ARGS 2) 
(PUT 'COERCABLE 'DEFINED-ON-LINE '182) 
(PUT 'COERCABLE 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'COERCABLE 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE COERCABLE (U V) (OR (EQUAL U V) (COERCABLELIS U (GET V 'TYPETREE)))) 
(PUT 'COERCABLELIS 'NUMBER-OF-ARGS 2) 
(PUT 'COERCABLELIS 'DEFINED-ON-LINE '186) 
(PUT 'COERCABLELIS 'DEFINED-IN-FILE 'REDUCE4/TOWER.RED) 
(PUT 'COERCABLELIS 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE COERCABLELIS (U V)
    (AND V (OR (COERCABLE U (CAR V)) (COERCABLELIS U (CDR V))))) 
(ENDMODULE) 