(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'WHERE)) 
(PUT 'FORMWHERE 'NUMBER-OF-ARGS 3) 
(PUT 'FORMWHERE 'DEFINED-ON-LINE '34) 
(PUT 'FORMWHERE 'DEFINED-IN-FILE 'RLISP/WHERE.RED) 
(PUT 'FORMWHERE 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE FORMWHERE (U VARS MODE)
    (PROG (EXPN EQUIVS Y Z)
      (SETQ EXPN (CADR U))
      (SETQ EQUIVS (REMCOMMA (CADDR U)))
      (COND
       ((NOT (EQUAL MODE 'SYMBOLIC))
        (RETURN (FORM1 (LIST 'WHEREEXP (CONS 'LIST EQUIVS) EXPN) VARS MODE))))
      (PROG (J)
        (SETQ J EQUIVS)
       LAB
        (COND ((NULL J) (RETURN NIL)))
        ((LAMBDA (J)
           (COND
            ((AND (NOT (ATOM J)) (MEMQ (CAR J) '(EQUAL SETQ)))
             (PROGN (SETQ Y (CONS (CADDR J) Y)) (SETQ Z (CONS (CADR J) Z))))
            (T (RERROR 'RLISP 17 (LIST J "invalid in WHERE statement")))))
         (CAR J))
        (SETQ J (CDR J))
        (GO LAB))
      (RETURN
       (FORMC (CONS (LIST 'LAMBDA (REVERSIP Z) EXPN) (REVERSIP Y)) VARS MODE)))) 
(PUT 'WHERE 'FORMFN 'FORMWHERE) 
(ENDMODULE) 