(load "../sl-on-cl")
(load "module")
(load "clprolo")
(load "rlisp")
(load "smacros")
;(load "module")
(load "switch")
(load "rsupport")
(load "clrend")
(load "newtok")
(load "infix")
(load "poly")
(load "alg")
(load "arith")
(load "rtools")
(load "mathpr")
(load "lpri")
(load "form")
(load "dmode")
(load "physop")
(load "superv")
(load "simp")
(load "entry")
(load "excalc")
;;
(load "tok")   ;; readch1
(load "xread") ;; xread1
(load "reval") ;; aeval
(load "intro") ;; redmsg
(load "mksp")  ;; mksq
(load "lifted") ;; carx
(load "proc")   ;; mkhash 
(load "kernel") ;; fkern
(load "polrep") ;; multsq,invsq,addsq,negsqm,...
(load "gcd")    ;; gcdf
(load "dmodeop") :: :minus
(load "exptchk") ;;
(load "sub") 
(load "prep")
(load "reord")
(load "subs2q")
(load "order")
(load "opmtch")
(load "depend")
(load "makevars")
(load "diff")
(load "conj")
(load "linop")
(load "symint")
(load "parser")
(load "forall")
(load "part")
(load "partdf")
(load "smacro")
(load "rmsubs")
(load "algdcl")
(load "array")
(load "statmisc")
(load "list")
(load "exptf")
(load "extout")
(load "exintro")
(load "contact")
(load "mprint")
(load "ratprin")
(load "rlfi")
;(load "remake")
;;;
;;; ok up to here  ...
;;; rest?


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#|
(load "ezgcd")
(load "factor")
(load "hephys")
(load "int")
(load "matrix")
(load "rlisp88")
(load "rprint")
(load "fmprint")
(load "pretty")
;(load "solve")
(load "desir")
;(load "ineq")
;(load "modsr")
(load "rsolve")
;(load "algint")
(load "arnum")
(load "assist")
;(load "dummy")
(load "cantens")
(load "atensor")
(load "avector")
(load "invbase")
(load "misc")
;(load "boolean")
(load "cedit")
;(load "rcref")
(load "reset")
(load "cali")
(load "camal")
(load "changevr")
(load "compact")
;(load "dfpart")
(load "lie")
(load "assert")
(load "odesolve")
(load "pf")
(load "trigd")
(load "cvit")
(load "noncom2")
;(load "physop")
(load "gentran")
(load "fide1")
;(load "fide")
(load "numeric")
(load "economise")
(load "randpoly")
(load "reacteqn")
(load "roots")
(load "rlfi")
;(load "roots2")
(load "sets")
(load "xideal")
;(load "eds")
(load "dipoly")
(load "groebner")
(load "groebnr2")
;(load "ideals")
(load "linalg")
(load "ncpoly")
(load "normform")
;(load "orthovec")
(load "plot")
(load "gnuplot")
;(load "laplace")
(load "pm")
;(load "qsum")
(load "scope")
(load "sparse")
(load "spde")
(load "ellipfn")
(load "specfn")
;(load "specfn2")
;(load "specfaux")
(load "specbess")
(load "sfgamma")
(load "tps")
(load "limits")
;(load "defint")
;(load "fps")
(load "trigint")
(load "ratint")
;(load "mathml")
(load "mathmlom")
(load "rlsupport")
(load "rltools")
;(load "redlog")
;(load "cgb")
(load "cl")
;(load "ofsf")
;(load "dvfsf")
;(load "acfsf")
;(load "dcfsf")
;(load "ibalp")
;(load "pasf")
;(load "qqe")
;(load "qqe_ofsf")
;(load "mri")
;(load "mri_ofsf")
;(load "mri_pasf")
(load "redfront")
(load "reduce4")
(load "tables")
;(load "talp")
(load "sum")
(load "zeilberg")
(load "symaux")
(load "symmetry")
(load "taylor")
(load "mrvlimit")
;(load "residue")
;(load "susy2")
(load "tri")
(load "trigsimp")
(load "crack")
(load "liepde")
(load "applysym")
;(load "conlaw")
;(load "v3tools")
(load "xcolor")
(load "wu")
(load "ztrans")
(load "geoprover")
(load "rataprx")
(load "rtrace")
;(load "tmprint")
(load "libreduce")
(load "utf8")
;(load "lpdo")
;(load "guardian")
;(load "breduce")
(load "cdiff")
(load "bibasis")
;(load "clprl")
;(load "gcref")
(load "turtle")
(load "logoturtle")
(load "profile")
;(load "pident")
;(load "pgauss")
(load "qhull")
(load "smt")
(load "rubi_red")
(load "lalr")
(load "ranum")
(load "listvecops")
(load "cde")
;(load "sstools")
(load "coeff2")
(load "grinder")
(load "f5")

|#

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;; (load "../fasl-loader.lisp")

;;;
; (in-package :sl)
; (begin)
; (algebraic)
 




