(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'BIBASIS)) 
(CREATE-PACKAGE
 '(BIBASIS BIBASIS_MONOM BIBASIS_POLYNOM BIBASIS_TRIPLE BIBASIS_JANET_TREE
   BIBASIS_QSET BIBASIS_TSET BIBASIS_INVOLUTIVE BIBASIS_INTERFACE)
 NIL) 
(FLUID
 '(FLUIDBIBASISVARIABLES FLUIDBIBASISREVERSEDVARIABLES
   FLUIDBIBASISMONOMIALORDER FLUIDBIBASISSINGLEVARIABLEMONOMIALSA
   FLUIDBIBASISSINGLEVARIABLEMONOMIALSS FLUIDBIBASISNUMBEROFVARIABLES
   FLUIDBIBASISSETQ FLUIDBIBASISSETT FLUIDBIBASISTRIPLEID
   FLUIDBIBASISJANETTREEROOTNODE FLUIDBIBASISREDUCTIONSMADE
   FLUIDBIBASISNORMALFORMS FLUIDBIBASISNONZERONORMALFORMS
   FLUIDBIBASISRUNNINGTIME FLUIDBIBASISGCTIME)) 
(ENDMODULE) 