(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'CDE)) 
(PRIN2T "This is CDE, a REDUCE package for calculus on differential equations") 
(PRIN2T "version 3.0, 14 April 2020") 
(PRIN2T "by Raffaele Vitolo") 
(FLUID
 '(INDEP_VAR DEP_VAR ODD_VAR TOTAL_ORDER PRINCIPAL_DER DE PRINCIPAL_ODD DE_ODD
   DEG_INDEP_VAR DEG_DEP_VAR DEG_ODD_VAR INDEP_VAR* DEP_VAR* ODD_VAR*
   PRINCIPAL_DER* DE* PRINCIPAL_ODD* DE_ODD* DEG_INDEP_VAR* DEG_DEP_VAR*
   DEG_ODD_VAR* ID_TOT_DER* N_INDEP_VAR ALL_MIND_TABLE* ALL_DER_MIND*
   ALL_ODD_MIND* ALL_MIND* ALL_DER_ID* ALL_ODD_ID* ALL_DER_ID ALL_ODD_ID
   N_ALL_EXT I2M_JETSPACE* I2M_JETSPACE_ODD* I2O_JETSPACE* I2O_JETSPACE_ODD*
   ALL_PRINCIPAL_DER* ALL_PARAMETRIC_DER* ALL_PRINCIPAL_DER ALL_PARAMETRIC_DER
   ALL_PRINCIPAL_ODD* ALL_PARAMETRIC_ODD* ALL_PRINCIPAL_ODD ALL_PARAMETRIC_ODD
   N_ALL_PRINCIPAL_EXT N_ALL_PARAMETRIC_EXT TOT_DER* LETOP
   PRIMARY_DIFFCON_DER_TOT* PRIMARY_DIFFCON_ODD_TOT* PRIMARY_DIFFCON_DER*
   PRIMARY_DIFFCON_ODD* DIFFCON_DER* DIFFCON_ODD* DIFFCON_COMP_DER*
   DIFFCON_COMP_ODD* DIFFCON_COMP_EXT* DIFFCON_PARAM_DER* DIFFCON_PARAM_EXT*
   REPPRINCPARAM_DER REPPRINCPARAM_EXT REPPRINCPARAM_ODD)) 
(SHARE
 (LIST 'ALL_DER_ID 'ALL_ODD_ID 'ALL_PARAMETRIC_DER 'ALL_PRINCIPAL_DER
       'ALL_PARAMETRIC_ODD 'ALL_PRINCIPAL_ODD 'REPPRINCPARAM_DER
       'REPPRINCPARAM_ODD)) 
(SWITCH (LIST 'CHECKORD)) 
(SETQ *CHECKORD T) 
(SWITCH (LIST 'EXPAND_TD)) 
(SETQ *EXPAND_TD T) 
(LOAD_PACKAGE (LIST 'CDIFF)) 
(CREATE-PACKAGE
 '(CDE CDE_TOOLS CDE_JETSPACE CDE_PARAMETRIC CDE_TOTALDER CDE_DIFFCON CDE_CDIFF
   CDE_SUPERFUN CDE_VARCALC CDE_VECTORFIELD CDE_CDCALC CDE_WEAKLYNL CDE_ANSATZ
   CDE_INIT)
 NIL) 
(ENDMODULE) 