(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'COEFF)) 
(FLUID '(*RATARG)) 
(GLOBAL '(HIPOW* LOWPOW*)) 
(SWITCH (LIST 'RATARG)) 
(FLAG '(HIPOW* LOWPOW*) 'SHARE) 
(PUT 'COEFFEVAL 'NUMBER-OF-ARGS 1) 
(PUT 'COEFFEVAL 'DEFINED-ON-LINE '42) 
(PUT 'COEFFEVAL 'DEFINED-IN-FILE 'ALG/COEFF.RED) 
(PUT 'COEFFEVAL 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE COEFFEVAL (U)
    (PROG (N)
      (SETQ N 0)
      (SETQ N (LENGTH U))
      (COND
       ((OR (LESSP N 2) (GREATERP N 3))
        (RERROR 'ALG 28 "COEFF called with wrong number of arguments"))
       (T
        (RETURN
         (COEFF1 (CAR U) (CADR U)
                 (COND ((NULL (CDDR U)) NIL) (T (CADDR U))))))))) 
(PUT 'COEFF 'PSOPFN 'COEFFEVAL) 
(PUT 'COEFF1 'NUMBER-OF-ARGS 3) 
(PUT 'COEFF1 'DEFINED-ON-LINE '54) 
(PUT 'COEFF1 'DEFINED-IN-FILE 'ALG/COEFF.RED) 
(PUT 'COEFF1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE COEFF1 (U V W)
    ((LAMBDA (*EXP)
       (PROG (*FACTOR BOOL X Y Z)
         (COND
          ((AND (EQCAR U '*SQ) (NULL *EXP))
           (PROGN (SETQ *EXP T) (SETQ U (RESIMP (CADR U)))))
          (T (PROGN (SETQ *EXP T) (SETQ U (SIMP* U)))))
         (SETQ V (*A2KWOWEIGHT V))
         (SETQ BOOL (OR *RATARG (FREEOF (PREPF (CDR U)) V)))
         (COND ((NULL BOOL) (SETQ U (*Q2F U))))
         (SETQ X (UPDKORDER V))
         (COND ((NULL BOOL) (PROGN (SETQ Y (REORDER U)) (SETQ U 1)))
               (T (PROGN (SETQ Y (REORDER (CAR U))) (SETQ U (CDR U)))))
         (SETKORDER X)
         (COND ((NULL Y) (GO A)))
         (PROG ()
          WHILELABEL
           (COND
            ((NOT (AND (NOT (OR (ATOM Y) (ATOM (CAR Y)))) (EQUAL (CAAAR Y) V)))
             (RETURN NIL)))
           (PROGN
            (SETQ Z (CONS (CONS (CDAAR Y) (*FF2A (CDAR Y) U)) Z))
            (SETQ Y (CDR Y)))
           (GO WHILELABEL))
         (COND ((NULL Y) (GO B)))
        A
         (SETQ Z (CONS (CONS 0 (*FF2A Y U)) Z))
        B
         (SETQ LOWPOW* (PROGN (SETQ ALGLIST* (CONS NIL NIL)) (CAAR Z)))
         (SETQ Z (REVERSE Z))
         (SETQ HIPOW* (PROGN (SETQ ALGLIST* (CONS NIL NIL)) (CAAR Z)))
         (SETQ Z (MULTIPLE-RESULT Z W))
         (RETURN (COND ((NULL W) Z) (T HIPOW*)))))
     *EXP)) 
(PUT 'COEFFN 'NUMBER-OF-ARGS 3) 
(PUT 'COEFFN 'DEFINED-ON-LINE '80) 
(PUT 'COEFFN 'DEFINED-IN-FILE 'ALG/COEFF.RED) 
(PUT 'COEFFN 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE COEFFN (U V N)
    (PROG (*EXP *FACTOR BOOL X Y)
      (SETQ *EXP T)
      (SETQ N (REVAL1 N T))
      (COND ((OR (NOT (FIXP N)) (MINUSP N)) (TYPERR N "COEFFN index")))
      (SETQ V (*A2KWOWEIGHT V))
      (SETQ U (SIMP* U))
      (SETQ BOOL (OR *RATARG (FREEOF (PREPF (CDR U)) V)))
      (COND ((NULL BOOL) (SETQ U (*Q2F U))))
      (SETQ X (UPDKORDER V))
      (COND ((NULL BOOL) (PROGN (SETQ Y (REORDER U)) (SETQ U 1)))
            (T (PROGN (SETQ Y (REORDER (CAR U))) (SETQ U (CDR U)))))
      (SETKORDER X)
      (COND ((NULL Y) (RETURN 0)))
     B
      (COND
       ((OR (OR (ATOM Y) (ATOM (CAR Y))) (NEQ (CAAAR Y) V))
        (RETURN (COND ((EQUAL N 0) (*FF2A Y U)) (T 0))))
       ((EQUAL N (CDAAR Y)) (RETURN (*FF2A (CDAR Y) U)))
       ((GREATERP N (CDAAR Y)) (RETURN 0))
       (T (PROGN (SETQ Y (CDR Y)) (GO B)))))) 
(FLAG '(COEFFN) 'OPFN) 
(FLAG '(COEFFN) 'NOVAL) 
(ENDMODULE) 