(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'DUMMY)) 
(CREATE-PACKAGE '(DUMMY PERMS BACKTRCK DUMMYCNT) '(CONTRIB ASSIST)) 
(LOAD_PACKAGE (LIST 'ASSIST)) 
(PUT 'FULLCOPY 'NUMBER-OF-ARGS 1) 
(PUT 'FULLCOPY 'DEFINED-ON-LINE '61) 
(PUT 'FULLCOPY 'DEFINED-IN-FILE 'ASSIST/DUMMY.RED) 
(PUT 'FULLCOPY 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE FULLCOPY (S)
    (COND ((PAIRP S) (CONS (FULLCOPY (CAR S)) (FULLCOPY (CDR S))))
          ((VECTORP S)
           (PROG (COP SI)
             (SETQ SI 0)
             (SETQ SI (UPBV S))
             (SETQ COP (MKVECT SI))
             (PROG (I)
               (SETQ I 0)
              LAB
               (COND ((MINUSP (DIFFERENCE SI I)) (RETURN NIL)))
               (PUTV COP I (FULLCOPY (GETV S I)))
               (SETQ I (PLUS2 I 1))
               (GO LAB))
             (RETURN COP)))
          (T S))) 
(ENDMODULE) 