(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'GENTRAN)) 
(CREATE-PACKAGE
 '(GENTRAN UTILS INTRFC TEMPLT PRE GPARSER REDLSP SEGMNT LSPFOR LSPRAT LSPC
   LSPPASC GOUTPUT)
 '(CONTRIB GENTRAN)) 
(DE SMALLFLOATP (U) (ATOM U)) 
(PUT 'SMALLFLOATP 'NUMBER-OF-ARGS 1) 
(PUT 'SMALLFLOATP 'DEFINED-ON-LINE '36) 
(PUT 'SMALLFLOATP 'DEFINED-IN-FILE 'GENTRAN/GENTRAN.RED) 
(PUT 'SMALLFLOATP 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(PUTC 'SMALLFLOATP 'INLINE '(LAMBDA (U) (ATOM U))) 
(ENDMODULE) 