(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'GNUPLOT)) 
(CREATE-PACKAGE '(GNUPLOT GNUINTFC GNUPLDRV) NIL) 
(GLOBAL
 '(PLOTDTA* PLOTDTA*2 PLOTMAX* PLOTMIN* PLOTCMDS* PLOTCOMMAND* PLOTDRIVER*)) 
(SETQ PLOTDRIVER* 'GNUPLOT) 
(PUT 'GNUPLOT 'DO 'GP-DO) 
(PUT 'GNUPLOT 'OPTION 'GP-OPTION) 
(LOAD_PACKAGE (LIST 'PLOT)) 
(ENDMODULE) 