(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'GROEBNR2)) 
(CREATE-PACKAGE
 '(GROEBNR2 GROEBMAN GLEXCONV GROEBMES GROEBRST GROEBTRA GROEWEAK HILBERTS
   HILBERTP HGGROEB KUECHL GREDUO)
 '(CONTRIB GROEBNER)) 
(LOAD-PACKAGE 'GROEBNER) 
(IMPORTS
 (LIST 'A2VDP 'F2VDP 'A2VBC 'VDP2A 'VDP2F 'VBC2A 'VDPFMON 'VDPAPPENDVDP 'VDPLBC
       'VDPRED 'VDPLASTMON 'VEVNTH 'VDPZERO? 'VDPREDZERO? 'VDPONE? 'VEVZERO?
       'VBCPLUS? 'VBCONE? 'VBCNUMBERP? 'VEVDIVIDES? 'VEVCOMPLESS? 'VDPEQUAL
       'VDPMEMBER 'VEVEQUAL 'VDPSUM 'VDPPROD 'VDPDIVMON 'CDPCANCELVEV
       'VDPLCOMB1 'VDPCONTENT 'VDPSIMPCONT 'VDPLCM 'VDPRESIMP 'VBCSUM 'VBCDIF
       'VBCNEG 'VBCPROD 'VBCQUOT 'VBCINV 'VBCGCD 'VEVSUM 'VEVSUM0 'VEVDIF
       'VEVTDEG 'VEVZERO 'VDPILCOMB1 'VDPPRIN2 'VDPPUTPROP 'VDPGETPROP
       'VDPLSORT 'VDPLSORTIN 'VDPPRINT 'VDPPRIN3T 'VDPRECTOINT 'GROEBMESS24
       'GROEBMESS4 'GROEBMESS2 'GROEBMESS51 'GROEBMESS8 'GROEBMESSFF
       'GROEBMESS5 'GROEBMESS34 'GROEBMESS29 'GROEBMESS32 'GROEBMESS30
       'GROEBMESS31 'GROEBMESS36 'GROEBMESS37 'GROEBMESS35 'GROEBMESS33
       'VEVWEIGHTEDCOMP2 'VDPVBCPROD 'VDPCANELMVEV 'GSETSUGAR '|RNONEP:|
       '|RNTIMES:| '*I2RN '|RNMINUSP:| '|RNDIFFERENCE:| '|RNZEROP:| '|RNPLUS:|
       '|RNQUOTIENT:| 'RNEQUIV '|RNPREP:| 'MKRN 'VDPCOEFFCIENTSFROMDOMAIN?
       'SIMP 'ADDSQ 'MULTSQ 'RERROR 'VDPCLEANUP 'TORDER2)) 
(EXPORTS
 (LIST 'GDIMENSIONEVAL 'GLEXCONVERT 'GREDUCE 'PREDUCE 'GROEBNERT 'DD_GROEBNER
       'HILBERTPOLYNOMIAL 'GSORT 'GSPLIT 'GSPOLY 'GZERODIM? 'GROEB-W1)) 
(ENDMODULE) 