(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'LINMODP)) 
(FLUID '(PRIME-BASE)) 
(PUT 'LU-FACTORIZE-MOD-P 'NUMBER-OF-ARGS 2) 
(PUT 'LU-FACTORIZE-MOD-P 'DEFINED-ON-LINE '32) 
(PUT 'LU-FACTORIZE-MOD-P 'DEFINED-IN-FILE 'FACTOR/LINMODP.RED) 
(PUT 'LU-FACTORIZE-MOD-P 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE LU-FACTORIZE-MOD-P (A N)
    (PROG (W)
      (PROG (I)
        (SETQ I 1)
       LAB
        (COND ((MINUSP (DIFFERENCE N I)) (RETURN NIL)))
        (PROG (II PIVOT)
          (COND ((EQ W 'SINGULAR) (RETURN NIL)))
          (SETQ II I)
          (PROG ()
           WHILELABEL
            (COND
             ((NOT
               (AND (GEQ N II)
                    (OR (EQUAL (SETQ PIVOT (GETV (GETV A II) I)) 0)
                        (EQUAL (IREMAINDER PIVOT PRIME-BASE) 0))))
              (RETURN NIL)))
            (SETQ II (PLUS II 1))
            (GO WHILELABEL))
          (COND ((GREATERP II N) (RETURN (SETQ W 'SINGULAR))))
          (COND
           ((NOT (EQUAL II I))
            (PROG (TEMP)
              (SETQ TEMP (GETV A I))
              (PUTV A I (GETV A II))
              (PUTV A II TEMP))))
          (PUTV (GETV A I) 0 II)
          (SETQ PIVOT (MODULAR-RECIPROCAL PIVOT))
          (PUTV (GETV A I) I PIVOT)
          (PROG (J)
            (SETQ J (PLUS I 1))
           LAB
            (COND ((MINUSP (DIFFERENCE N J)) (RETURN NIL)))
            (PUTV (GETV A I) J
                  (REMAINDER (TIMES PIVOT (GETV (GETV A I) J))
                             CURRENT-MODULUS))
            (SETQ J (PLUS2 J 1))
            (GO LAB))
          (PROG (II)
            (SETQ II (PLUS I 1))
           LAB
            (COND ((MINUSP (DIFFERENCE N II)) (RETURN NIL)))
            (PROG (MULTIPLE)
              (SETQ MULTIPLE (GETV (GETV A II) I))
              (PROG (J)
                (SETQ J (PLUS I 1))
               LAB
                (COND ((MINUSP (DIFFERENCE N J)) (RETURN NIL)))
                (PUTV (GETV A II) J
                      (PROG (RESULT)
                        (SETQ RESULT
                                (IDIFFERENCE (GETV (GETV A II) J)
                                             (REMAINDER
                                              (TIMES MULTIPLE
                                                     (GETV (GETV A I) J))
                                              CURRENT-MODULUS)))
                        (COND
                         ((IMINUSP RESULT)
                          (SETQ RESULT (IPLUS2 RESULT CURRENT-MODULUS))))
                        (RETURN RESULT)))
                (SETQ J (PLUS2 J 1))
                (GO LAB)))
            (SETQ II (PLUS2 II 1))
            (GO LAB)))
        (SETQ I (PLUS2 I 1))
        (GO LAB))
      (RETURN W))) 
(PUT 'BACK-SUBSTITUTE 'NUMBER-OF-ARGS 3) 
(PUT 'BACK-SUBSTITUTE 'DEFINED-ON-LINE '61) 
(PUT 'BACK-SUBSTITUTE 'DEFINED-IN-FILE 'FACTOR/LINMODP.RED) 
(PUT 'BACK-SUBSTITUTE 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE BACK-SUBSTITUTE (A V N)
    (PROG ()
      (PROG (I)
        (SETQ I 1)
       LAB
        (COND ((MINUSP (DIFFERENCE N I)) (RETURN NIL)))
        (PROG (II)
          (SETQ II (GETV (GETV A I) 0))
          (COND
           ((NEQ II I)
            (PROG (TEMP)
              (SETQ TEMP (GETV V I))
              (PUTV V I (GETV V II))
              (PUTV V II TEMP)))))
        (SETQ I (PLUS2 I 1))
        (GO LAB))
      (PROG (I)
        (SETQ I 1)
       LAB
        (COND ((MINUSP (DIFFERENCE N I)) (RETURN NIL)))
        (PROG ()
          (PUTV V I
                (TIMES-MOD-P
                 ((LAMBDA (U) (COND ((ZEROP U) NIL) (T U)))
                  (GETV (GETV A I) I))
                 (GETV V I)))
          (PROG (II)
            (SETQ II (PLUS I 1))
           LAB
            (COND ((MINUSP (DIFFERENCE N II)) (RETURN NIL)))
            (PUTV V II
                  (DIFFERENCE-MOD-P (GETV V II)
                   (TIMES-MOD-P (GETV V I)
                    ((LAMBDA (U) (COND ((ZEROP U) NIL) (T U)))
                     (GETV (GETV A II) I)))))
            (SETQ II (PLUS2 II 1))
            (GO LAB)))
        (SETQ I (PLUS2 I 1))
        (GO LAB))
      (PROG (I)
        (SETQ I (DIFFERENCE N 1))
       LAB
        (COND ((MINUSP (TIMES (MINUS 1) (DIFFERENCE 1 I))) (RETURN NIL)))
        (PROG (J)
          (SETQ J (PLUS I 1))
         LAB
          (COND ((MINUSP (DIFFERENCE N J)) (RETURN NIL)))
          (PUTV V I
                (DIFFERENCE-MOD-P (GETV V I)
                 (TIMES-MOD-P
                  ((LAMBDA (U) (COND ((ZEROP U) NIL) (T U)))
                   (GETV (GETV A I) J))
                  (GETV V J))))
          (SETQ J (PLUS2 J 1))
          (GO LAB))
        (SETQ I (PLUS2 I (MINUS 1)))
        (GO LAB))
      (RETURN V))) 
(ENDMODULE) 