(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'LIQSIMP1)) 
(FLUID '(LIQSIMP1BOUNDS*)) 
(PUT 'LIQSIMP1-MAXMIN 'NUMBER-OF-ARGS 1) 
(PUT 'LIQSIMP1-MAXMIN 'DEFINED-ON-LINE '31) 
(PUT 'LIQSIMP1-MAXMIN 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-MAXMIN 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE LIQSIMP1-MAXMIN (W) ((LAMBDA (LIQSIMP1BOUNDS*) (LIQSIMP1-MAXMIN1 W)) NIL)) 
(PUT 'LIQSIMP1-MAXMIN1 'NUMBER-OF-ARGS 1) 
(PUT 'LIQSIMP1-MAXMIN1 'DEFINED-ON-LINE '40) 
(PUT 'LIQSIMP1-MAXMIN1 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-MAXMIN1 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE LIQSIMP1-MAXMIN1 (W)
    (PROG (X L U R)
      (SETQ X (CAAAR W))
      (SETQ L (CADAR W))
      (SETQ U (CADDAR W))
      (COND
       ((CDR W)
        (PROGN
         (SETQ R (LIQSIMP1-MAXMIN1 (CDR W)))
         (SETQ L (LIQSIMP1-REDUCECASES L))
         (SETQ U (LIQSIMP1-REDUCECASES U))
         NIL)))
      (SETQ LIQSIMP1BOUNDS*
              (CONS (LIST X (LIQSIMP1-MAXMIN1LEAF L) (LIQSIMP1-MAXMIN1LEAF U))
                    LIQSIMP1BOUNDS*))
      (RETURN (CONS (LIST (CAAR W) L U) R)))) 
(PUT 'LIQSIMP1-REDUCECASES 'NUMBER-OF-ARGS 1) 
(PUT 'LIQSIMP1-REDUCECASES 'DEFINED-ON-LINE '55) 
(PUT 'LIQSIMP1-REDUCECASES 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-REDUCECASES 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE LIQSIMP1-REDUCECASES (W)
    (PROG (OP L TST D U)
      (COND ((OR (ATOM W) (NOT (MEMQ (CAR W) '(MAX MIN)))) (RETURN W)))
      (SETQ OP (CAR W))
      (SETQ L
              (PROG (U FORALL-RESULT FORALL-ENDPTR)
                (SETQ U (CDR W))
                (COND ((NULL U) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS ((LAMBDA (U) (CONS U (SIMP U))) (CAR U))
                                      NIL)))
               LOOPLABEL
                (SETQ U (CDR U))
                (COND ((NULL U) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS ((LAMBDA (U) (CONS U (SIMP U))) (CAR U)) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (PROG (E)
        (SETQ E L)
       LAB
        (COND ((NULL E) (RETURN NIL)))
        ((LAMBDA (E)
           (PROGN
            (SETQ TST NIL)
            (PROG (D)
              (SETQ D L)
             LAB
              (COND ((NULL D) (RETURN NIL)))
              ((LAMBDA (D)
                 (COND
                  ((AND (NEQ D E) (NOT TST))
                   (PROGN
                    (SETQ U (ADDSQ (CDR D) (NEGSQ (CDR E))))
                    (SETQ TST (LIQSIMP1-CHECK U LIQSIMP1BOUNDS* OP))
                    NIL))))
               (CAR D))
              (SETQ D (CDR D))
              (GO LAB))
            (COND (TST (SETQ L (DELETE E L))))
            NIL))
         (CAR E))
        (SETQ E (CDR E))
        (GO LAB))
      (SETQ L
              (PROG (U FORALL-RESULT FORALL-ENDPTR)
                (SETQ U L)
                (COND ((NULL U) (RETURN NIL)))
                (SETQ FORALL-RESULT
                        (SETQ FORALL-ENDPTR
                                (CONS ((LAMBDA (U) (CAR U)) (CAR U)) NIL)))
               LOOPLABEL
                (SETQ U (CDR U))
                (COND ((NULL U) (RETURN FORALL-RESULT)))
                (RPLACD FORALL-ENDPTR
                        (CONS ((LAMBDA (U) (CAR U)) (CAR U)) NIL))
                (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
                (GO LOOPLABEL)))
      (RETURN (COND ((CDR L) (CONS OP L)) (T (CAR L)))))) 
(PUT 'LIQSIMP1-CHECK 'NUMBER-OF-ARGS 3) 
(PUT 'LIQSIMP1-CHECK 'DEFINED-ON-LINE '80) 
(PUT 'LIQSIMP1-CHECK 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-CHECK 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE LIQSIMP1-CHECK (U BOUNDS M)
    (COND ((EQUAL M 'MIN) (LIQSIMP1-CHECK1 (NEGSQ U) BOUNDS))
          (T (LIQSIMP1-CHECK1 U BOUNDS)))) 
(PUT 'LIQSIMP1-CHECK1 'NUMBER-OF-ARGS 2) 
(PUT 'LIQSIMP1-CHECK1 'DEFINED-ON-LINE '84) 
(PUT 'LIQSIMP1-CHECK1 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-CHECK1 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE LIQSIMP1-CHECK1 (U BOUNDS)
    (COND
     ((OR (ATOM (CAR U)) (ATOM (CAR (CAR U))))
      (OR (NOT (MINUSF (CAR U))) (NULL (CAR U))))
     ((NULL BOUNDS) NIL)
     ((NEQ (CAAAR (CAR U)) (CAAR BOUNDS)) (LIQSIMP1-CHECK1 U (CDR BOUNDS)))
     (T
      (PROG (X C R D TST BDS)
        (SETQ X (CAAR BOUNDS))
        (SETQ D (CONS (CDR U) 1))
        (SETQ C (CONS (CDAR (CAR U)) 1))
        (SETQ R (CONS (CDR (CAR U)) 1))
        (COND ((LIQSIMP1-CHECK1 C BOUNDS) (SETQ BDS (CADAR BOUNDS)))
              (T (SETQ BDS (CADDAR BOUNDS))))
        (PROG (B)
          (SETQ B BDS)
         LAB
          (COND ((NULL B) (RETURN NIL)))
          ((LAMBDA (B)
             (SETQ TST
                     (OR TST
                         (LIQSIMP1-CHECK1 (ADDSQ (MULTSQ C B) R)
                          (CDR BOUNDS)))))
           (CAR B))
          (SETQ B (CDR B))
          (GO LAB))
        (RETURN TST))))) 
(PUT 'LIQSIMP1-MAXMIN1LEAF 'NUMBER-OF-ARGS 1) 
(PUT 'LIQSIMP1-MAXMIN1LEAF 'DEFINED-ON-LINE '107) 
(PUT 'LIQSIMP1-MAXMIN1LEAF 'DEFINED-IN-FILE 'SOLVE/LIQSIMP1.RED) 
(PUT 'LIQSIMP1-MAXMIN1LEAF 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE LIQSIMP1-MAXMIN1LEAF (Q)
    (COND ((OR (EQUAL Q 'INFINITY) (EQUAL Q '(MINUS INFINITY))) NIL)
          (T
           (PROG (W FORALL-RESULT FORALL-ENDPTR)
             (SETQ W
                     (COND ((AND (PAIRP Q) (MEMQ (CAR Q) '(MAX MIN))) (CDR Q))
                           (T (LIST Q))))
             (COND ((NULL W) (RETURN NIL)))
             (SETQ FORALL-RESULT
                     (SETQ FORALL-ENDPTR
                             (CONS ((LAMBDA (W) (SIMP W)) (CAR W)) NIL)))
            LOOPLABEL
             (SETQ W (CDR W))
             (COND ((NULL W) (RETURN FORALL-RESULT)))
             (RPLACD FORALL-ENDPTR (CONS ((LAMBDA (W) (SIMP W)) (CAR W)) NIL))
             (SETQ FORALL-ENDPTR (CDR FORALL-ENDPTR))
             (GO LOOPLABEL))))) 
(ENDMODULE) 