(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'MATHMLOM)) 
(FLUID
 '(*F* SAFE_ATTS CHAR CH ATTS OMFUNCS* INTERVAL* MMLTYPES* CONSTANTSOM* COUNT
   TEMP SPACE TEMP2 MMLATTS CONSTANTS* FUNCTIONS* RELATIONS* CONSTRUCTORS*
   IR2MML* VALID_OM* SPECIAL_CASES* SPECIAL_CASES2* MMLEQ*)) 
(CREATE-PACKAGE '(MATHMLOM MTABLES TOOLS IR2OM OM2IR MML_IR) NIL) 
(ENDMODULE) 