(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'MATPROC)) 
(GLOBAL '(CURSYM*)) 
(PUT 'READMATPROC 'NUMBER-OF-ARGS 0) 
(PUT 'READMATPROC 'DEFINED-ON-LINE '33) 
(PUT 'READMATPROC 'DEFINED-IN-FILE 'MATRIX/MATPROC.RED) 
(PUT 'READMATPROC 'PROCEDURE_TYPE '(ARROW UNIT GENERAL)) 
(DE READMATPROC NIL
    (PROG (X)
      (SETQ CURSYM* 'PROCEDURE)
      (SETQ X (PROCSTAT1 'ALGEBRAIC))
      (COND ((EQCAR X 'PROCEDURE) (SETQ X (CONS 'MATPROC X)))
            (T
             (SETQ X
                     (PROG (J FORALL-RESULT FORALL-ENDPTR)
                       (SETQ J X)
                      STARTOVER
                       (COND ((NULL J) (RETURN NIL)))
                       (SETQ FORALL-RESULT
                               ((LAMBDA (J)
                                  (COND
                                   ((EQCAR J 'PROCEDURE) (CONS 'MATPROC J))))
                                (CAR J)))
                       (SETQ FORALL-ENDPTR (LASTPAIR FORALL-RESULT))
                       (SETQ J (CDR J))
                       (COND ((ATOM FORALL-ENDPTR) (GO STARTOVER)))
                      LOOPLABEL
                       (COND ((NULL J) (RETURN FORALL-RESULT)))
                       (RPLACD FORALL-ENDPTR
                               ((LAMBDA (J)
                                  (COND
                                   ((EQCAR J 'PROCEDURE) (CONS 'MATPROC J))))
                                (CAR J)))
                       (SETQ FORALL-ENDPTR (LASTPAIR FORALL-ENDPTR))
                       (SETQ J (CDR J))
                       (GO LOOPLABEL)))))
      (RETURN X))) 
(PUT 'MATRIXPROC 'STAT 'READMATPROC) 
(PUT 'FORMMATPROC 'NUMBER-OF-ARGS 3) 
(PUT 'FORMMATPROC 'DEFINED-ON-LINE '44) 
(PUT 'FORMMATPROC 'DEFINED-IN-FILE 'MATRIX/MATPROC.RED) 
(PUT 'FORMMATPROC 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE FORMMATPROC (U V W)
    (PROG (X)
      (FLAG (LIST (CADDR U)) 'FORMC)
      (SETQ X (FORMPROC (CDR U) V W))
      (RETURN
       (CONS (CAR X)
             (CONS (CADR X)
                   (CONS
                    (LIST 'PUT (MKQUOTE (CADDR U)) ''RTYPEFN
                          ''(LAMBDA (X) 'MATRIX))
                    (CONS
                     (LIST 'PUT (MKQUOTE (CADDR U)) ''MATRIXFN
                           (LIST 'LIST ''LAMBDA ''(X Y)
                                 (LIST 'LIST ''MATPROCEVAL
                                       (MKQUOTE (MKQUOTE (CADDR U))) ''X ''Y)))
                     (CDDDR X)))))))) 
(PUT 'MATPROC 'FORMFN 'FORMMATPROC) 
(PUT 'MATPROCEVAL 'NUMBER-OF-ARGS 3) 
(PUT 'MATPROCEVAL 'DEFINED-ON-LINE '58) 
(PUT 'MATPROCEVAL 'DEFINED-IN-FILE 'MATRIX/MATPROC.RED) 
(PUT 'MATPROCEVAL 'PROCEDURE_TYPE
     '(ARROW (TIMES GENERAL GENERAL GENERAL) GENERAL)) 
(DE MATPROCEVAL (OP U V) (REVAL1 (OPFNEVAL (CONS OP U)) V)) 
(PUT 'GETMATSTRUCTELEM 'NUMBER-OF-ARGS 1) 
(PUT 'GETMATSTRUCTELEM 'DEFINED-ON-LINE '64) 
(PUT 'GETMATSTRUCTELEM 'DEFINED-IN-FILE 'MATRIX/MATPROC.RED) 
(PUT 'GETMATSTRUCTELEM 'PROCEDURE_TYPE '(ARROW GENERAL GENERAL)) 
(DE GETMATSTRUCTELEM (U)
    (PROG (X Y)
      (SETQ X (CAR U))
      (SETQ Y (REVAL_WITHOUT_MOD (CADR U)))
      (COND ((OR (NOT (FIXP Y)) (LEQ Y 0)) (TYPERR Y "positive integer")))
      (SETQ X (NTH (CDR X) Y))
      (SETQ Y (REVAL_WITHOUT_MOD (CADDR U)))
      (COND ((OR (NOT (FIXP Y)) (LEQ Y 0)) (TYPERR Y "positive integer")))
      (RETURN (NTH X Y)))) 
(PUT 'MAT 'STRUCTFN 'GETMATSTRUCTELEM) 
(PUT 'SETMATSTRUCTELEM 'NUMBER-OF-ARGS 2) 
(PUT 'SETMATSTRUCTELEM 'DEFINED-ON-LINE '77) 
(PUT 'SETMATSTRUCTELEM 'DEFINED-IN-FILE 'MATRIX/MATPROC.RED) 
(PUT 'SETMATSTRUCTELEM 'PROCEDURE_TYPE '(ARROW (TIMES GENERAL GENERAL) GENERAL)) 
(DE SETMATSTRUCTELEM (U V)
    (PROG (X Y)
      (SETQ X (CAR U))
      (SETQ Y (CDR U))
      (SETQ Y (REVAL_WITHOUT_MOD (CADR U)))
      (COND ((OR (NOT (FIXP Y)) (LEQ Y 0)) (TYPERR Y "positive integer")))
      (SETQ X (NTH (CDR X) Y))
      (SETQ Y (REVAL_WITHOUT_MOD (CADDR U)))
      (COND ((OR (NOT (FIXP Y)) (LEQ Y 0)) (TYPERR Y "positive integer")))
      (RETURN (RPLACA (PNTH X Y) V)))) 
(PUT 'MAT 'SETSTRUCTFN 'SETMATSTRUCTELEM) 
(ENDMODULE) 