(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'SPECFAUX)) 
(CREATE-PACKAGE '(SPECFAUX SFBDATA) '(CONTRIB SPECFN)) 
(LOAD-PACKAGE 'SPECFN) 
(ENDMODULE) 