(cl:declaim (cl:optimize cl:debug cl:safety))
(cl:declaim (sb-ext:muffle-conditions sb-ext:compiler-note cl:style-warning))
(MODULE (LIST 'TABLES)) 
(CREATE-PACKAGE '(TABLES TABLE1 TABLE2 TABLE3 MATRIX4) NIL) 
(LOAD_PACKAGE (LIST 'REDUCE4)) 
(ENDMODULE) 